- index.js
> Fix xpack check

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- package.json
- Support for Elasticsearch 7.1
- No major changes
- Version upgrade in pom file
- All Unit Tests Passed
> Support for Elasticsearch 7.1

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- package.json
* Support for Elasticsearch 7.1
* No major changes
* Version upgrade in pom file
> Support for Elasticsearch 7.1 (#38)

- public/apps/multitenancy/multitenancy.js
This proposed solution is related to issue #40.
> Avoid javascript error

- public/apps/configuration/sections/rolesmapping/controller.js
> Fix wrong property name in rolesmapping config controller

- build.sh
Fixes a small typo and adds a check for GPG command. As commented in #27.
> Add small fixes to build.sh

- build.sh
Reverts opendistro-for-elasticsearch/security-kibana-plugin#29
> Revert "Add small fixes to build.sh"

- package.json
- pom.xml
- Support for Kibana version oss-6.8.1
- All Unit Tests Passing
- All Integration Tests Passing
> Opendistro-For-Elasticsearch Security Kibana Plugin 0.10.0.0

- lib/backend/opendistro_security.js
- lib/multitenancy/headers.js
- lib/multitenancy/migrate_tenants.js
Fixing tenant migration issue. 
--calling tenantinfo with InternalUser
> Fixing tenant migration issue: tenantinfo with InternalUser

- opendistro-elasticsearch-security-kibana-plugin.release-notes
Updating release notes for OpenDistro-1.0 for releasing minor version v1.0.0.3
> Updating release notes for OpenDistro-1.0

- opendistro-elasticsearch-security-kibana-plugin.release-notes
Updating release notes for v0.9.0.1
> Updating release notes for v0.9.0.1

- opendistro-elasticsearch-security-kibana-plugin.release-notes
Creating release notes for v0.10.0.0
> Creating release notes for v0.10.0.0

- lib/multitenancy/headers.js
- lib/multitenancy/migrate_tenants.js
#52 has typos.
Tested by running the plugin.
> Fixing typos in PR #52

- lib/multitenancy/headers.js
- lib/multitenancy/migrate_tenants.js
> Opendistro 0.10

- pom.xml
Tested by running build.sh and verified it builds successfully.
> Use 0.10.0.0 tag in security parent

- pom.template.xml
- pom.xml
- public/apps/configuration/backend_api/securityconfiguration.js
Fix API path on Authentication and Authorization
> Fix API path on Authentication and Authorization on OD-1.1

- pom.xml
- public/apps/configuration/backend_api/securityconfiguration.js
Fix API path on Authentication and Authorization.
> Opendistro 0.9 bugfix - fix API path on Authentication and Authorization

- pom.xml
- public/apps/configuration/backend_api/securityconfiguration.js
Fix API path on Authentication and Authorization and test with opendistro-for-elasticsearch:0.10.0 docker image.
> Opendistro 0.10 bugfix - fix API path on Authentication and Authorization

- pom.template.xml
- pom.xml
- public/apps/configuration/backend_api/securityconfiguration.js
Fix API path on Authentication and Authorization
>  Fix API path on Authentication and Authorization on OD-1.0

- lib/configuration/routes/routes.js
- lib/utils/helpers.js
- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.xml
- public/apps/accountinfo/accountinfo.js
- public/apps/configuration/backend_api/client.js
- public/apps/configuration/backend_api/internalusers.js
- public/apps/configuration/base_controller.js
- public/apps/configuration/sections/internalusers/controller.js
- public/apps/configuration/sections/roles/controller.js
- public/apps/multitenancy/multitenancy.js
Fix password validation error and test with opendistro-for-elasticsearch:1.1.0 docker image.
> Opendistro 1.1 bugfix - fix password validation error

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- package.json
- pom.template.xml
- pom.xml
- public/apps/configuration/backend_api/securityconfiguration.js
> Support for ES 7.2.0

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.template.xml
- pom.xml
Update pom file, pom.template, and release note for v1.2.0.1
> Update pom and release note for v1.2.0.1

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.template.xml
- pom.xml
Update pom file, pom.template, and release note for v1.1.0.4
> Update pom and release note for v1.1.0.4

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.template.xml
- pom.xml
Support for ES 7.2.1 and test with elasticsearch-oss-7.2.1-darwin-x86_64.tar.gz.
> Support for ES 7.2.1

- public/apps/configuration/configuration.html
- This PR fixes the console error where it is trying to get SVG.
- This is the correct format to use the image tag.
Fixes: 
Issue: #101 
Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>
> Fix 404 svg not found console error

- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.template.xml
- pom.xml
Support for ES 7.2.1 and test with elasticsearch-oss-7.2.1-darwin-x86_64.tar.gz.
> Update Opendsitro subversion 1.2.1.0 for security kibana plugin

- public/apps/configuration/sections/internalusers/controller.js
- public/apps/configuration/sections/internalusers/views/edit.html
Tested with elasticsearch-oss-7.3.2-darwin-x86_64.tar.gz.
> Add dropdown menu for adding additional field (opendistro_secuirty_roles) for internal user CRUD

- public/apps/configuration/sections/internalusers/controller.js
Tested with elasticsearch-oss-7.3.2-darwin-x86_64.tar.gz.
> Fix cannot add new internal user without role issue

- public/apps/configuration/directives/confirmationmodal/confirmationmodal.html
- public/apps/configuration/directives/confirmationmodal/confirmationmodal.js
> Fix overlay confirmation modal dialog

- index.js
- lib/multitenancy/headers.js
- lib/multitenancy/migrate_tenants.js
- package.json
- pom.template.xml
- pom.xml
- public/apps/accountinfo/accountinfo.js
- public/apps/configuration/directives/confirmationmodal/confirmationmodal.html
- public/apps/configuration/directives/confirmationmodal/confirmationmodal.js
Support version 7.5.2
Downgraded security-parent as 1.4.0.0 is not pushed to maven central. Will be removing security-parent dependency soon.
> Support version Kibana 7.5.2

- .babelrc
- index.js
- lib/auth/types/AuthType.js
- lib/auth/types/basicauth/BasicAuth.js
- lib/auth/types/jwt/Jwt.js
- lib/auth/types/openid/OpenId.js
- lib/auth/types/proxycache/ProxyCache.js
- lib/auth/types/saml/Saml.js
- lib/session/sessionPlugin.js
- opendistro-elasticsearch-security-kibana-plugin.release-notes
- package.json
- public/apps/customerror/customerror.js
- public/apps/multitenancy/multitenancy.js
- tests/AuthType.test.js
- Apply all fixes for ODFE 1.4.0.0 into master (to be used in 1.5.0.0)
- Fixes
#136 #137 #139  #143
> Merging opendistro-1.4 changes back into master

- package.json
- pom.xml
Bump to support v6.8.6 to resolve https://github.com/opendistro-for-elasticsearch/community/issues/159
> bump to v6.8.6

- lib/auth/types/AuthType.js
- lib/session/sessionPlugin.js
- public/apps/multitenancy/multitenancy.js
- tests/AuthType.test.js
- tests/Mocks.js
- tests/SessionPlugin.test.js
Bring opendistro-1.4 change into opendistro-1.5
> Specify headers to be stored in sesssion

- lib/auth/types/AuthType.js
- lib/session/sessionPlugin.js
- public/apps/multitenancy/multitenancy.js
- tests/AuthType.test.js
- tests/Mocks.js
- tests/SessionPlugin.test.js
Bring opendistro-1.4 changes into master
> Specify headers to be stored in session.

- server/auth/types/basic/basic_auth.ts
When accessing a kibana page, almost all requests go through the auth handler. In case of using basic auth, and the auth cooke is not valid, auth handler will redirect the request to basic auth login page, and put the original request URL in the query parameter `nextUrl`. Once the user is authenticated by type in the username and password from login page, login page can redirect the browser to the original requested page.
> Redirect to login page in basic auth handler when accessing kibana page

- .gitignore
- NOTICE
- kibana.json
- public/apps/login/login-page.tsx
- public/plugin.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/auth/user.ts
- server/backend/opendistro_security_client.ts
- server/index.ts
- server/multitenancy/routes.ts
- server/multitenancy/tenant_index.ts
- server/multitenancy/tenant_resolver.ts
- server/plugin.ts
- server/routes/index.ts
- server/routes/test_routes.ts
this PR is a repost of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/165 , I messed up my fork and ended up with recreate my fork branches, and recreate this PR, I will address comments in the previous PR in next commit.
> Add multitenant APIs and tenant index management logic

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-list.tsx
Add a table to show security roles.
Mockup:
Current Implementation:
The screenshot is based on an implementation of data transformation. It uses an additional 3rd party lib and under license review, so not included in this PR.
> Add role table

- public/apps/configuration/panels/role-list.tsx
*Issue #, if available: N/A
*Description of changes:
Fix warning: Each child in a list should have a unique "key" prop
> Fix warning: Each child in a list should have a unique "key" prop

- package.json
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/auth/user.ts
- server/backend/opendistro_security_configuration_plugin.ts
- server/backend/opendistro_security_plugin.ts
- server/index.ts
- server/multitenancy/routes.ts
- server/multitenancy/tenant_index.ts
- server/multitenancy/tenant_resolver.ts
- server/routes/index.ts
- server/routes/test_routes.ts
- server/session/security_cookie.ts
> Prettify server plugin code

- public/apps/configuration/panels/role-list.tsx
*Issue #, if available:N/A
*Description of changes:*  
* Table - allow selection
* Table - allow sorting 
* Header - add an actions popover menu.
Mockup: 
> Add selection, sorting and actions popover menu.

- .eslintignore
- .eslintrc.js
- .gitignore
- .sass-lint.yml
- build_tools/build_plugin.js
- package.json
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/auth/user.ts
- server/backend/opendistro_security_client.ts
- server/multitenancy/routes.ts
- server/multitenancy/tenant_index.ts
- server/multitenancy/tenant_resolver.ts
- server/plugin.ts
- server/routes/index.ts
- server/routes/test_routes.ts
- server/utils/filter_auth_headers.ts
Add following lint related config files:
* `.eslintrc.js`
* `.eslintignore`
* `.sass-lint.yml`
to execute lint run following command from plugin root directory:
`yarn lint`
or only run lint against typescript/javascript code only or scss only:
```
yarn lint:es
```
or
```
yarn lint:sass
```
to get CLI options for eslint, run:
```
yarn lint:es --help
```
**Testing**
lint output for server side code so far:
```
% yarn lint:es --ignore-pattern "public/**/*"
yarn run v1.22.0
$ node ../../scripts/eslint --ignore-pattern 'public/**/*'
/Users/zengyan/kibana-security-workspace/kibana/plugins/opendistro_security/build_tools/build_plugin.js
1:1  error  File must start with a license header  @kbn/eslint/require-license-header …
```
> Add lint configurations and fix lint issues

- package.json
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/utils/role-list-utils.tsx
*Issue #, if available: N/A
Process data for table rendering:
1. Join role and rolesMapping data by key
2. Unbox index permissions and tenants
> Transform Data for role table

- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/utils/role-list-utils.tsx
> Improve code style

- public/apps/configuration/utils/role-list-utils.tsx
Bug fix of misuse of lodash forEach introduced in #181 
> Bug fix of misuse of lodash forEach

- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/utils/role-list-utils.tsx
Add search box and filters.
*Mockup:*
*Implementation:*
> Add search box and filters

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-edit.tsx
- public/apps/configuration/utils/panel-with-header.tsx
Add role edit page skeleton.
Mockup:
Implemtation:
> Add role edit page skeleton

- public/apps/configuration/utils/action-groups-utils.tsx
- public/apps/configuration/utils/form-row.tsx
- public/apps/configuration/utils/role-detail-utils.tsx
#191 Is a partial checkin, this is the missing part (dependency util files) for it.
> Add missing file for #191

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
- public/apps/configuration/panels/role-edit/index-permission-panel.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-edit/tenant-panel.tsx
- public/apps/configuration/panels/role-edit/types.tsx
- public/apps/configuration/utils/array-state-utils.tsx
Break down large file; Fix a bug for remove element from array state.
> Break down large file; Fix a bug for remove element from array state.

- .eslintrc.js
- common/index.ts
- public/apps/configuration/app-router.tsx
- public/apps/configuration/configuration-app.tsx
- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/nav-panel.tsx
- public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-edit/tenant-panel.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/utils/array-state-utils.tsx
- public/apps/configuration/utils/panel-with-header.tsx
- public/apps/configuration/utils/role-detail-utils.tsx
- public/apps/login/login-app.tsx
- public/apps/login/login-page.tsx
- public/apps/types.ts
- public/plugin.ts
Fix some eslint issues. 
Override `no_console` to 0 since both front-end and back-end has relies on console to output some message.
> Fix eslint issues

- server/auth/types/jwt/jwt_auth.ts
- server/plugin.ts
*Description of changes:* Add JWT (JsonWebToken) authentication.
> Add JWT authentication

- public/apps/configuration/constants.tsx
Improve API endpoint related constants.
> Improve API endpoint related constants

- server/auth/types/saml/routes.ts
- server/auth/types/saml/saml_auth.ts
- server/backend/opendistro_security_client.ts
- server/plugin.ts
- server/routes/index.ts
- server/session/security_cookie.ts
*Description of changes:* Add support for SAML authentication
> Add support for SAML authentication

- public/apps/configuration/panels/role-edit/index-permission-panel.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-edit/tenant-panel.tsx
- public/apps/configuration/utils/role-detail-utils.tsx
Add update/cancel button on role edit page.
Screenshots:
Mockup:
> Add update/cancel button on role edit page

- public/apps/configuration/app-router.tsx
- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/internal-user-list-utils.tsx
- public/apps/configuration/utils/role-list-utils.tsx
Add internal user listing.
TODO: 'Current' user badge.
Screenshots:
Mockup:
> Add internal user listing

- common/index.ts
- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/plugin.ts
See the related PR which was accidentally closed
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/228
> add redirect for duplicate role button

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/url-builder.tsx
- public/apps/types.ts
* Add a url builder
* Resolve redirection TODOs
* Add breadcrumbs
Screenshots for breadcrumbs:
Mockup:
Implementation
> Add a url builder, resolve redirection TODOs, add breadcrumbs

- common/index.ts
- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
> Refactor to use buildHashUrl

- common/index.ts
- public/apps/configuration/panels/user-list.tsx
- public/types.ts
- public/utils/auth-info-utils.tsx
Add current user badge on user listing page.
Mockup:
> Add current user badge on user listing page

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/url-builder.tsx
* Add user listing page
* Fix create action
* Fix edit link on user listing page
Mockup:
Current implementation:
> Add user listing page, fix create action, fix edit link on user listing page

- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/utils/password-edit-panel.tsx
Add password update form.
Note: replaced help text to current server side rule.
Screenshot:
Validation failed (in this case not 8 chars long)
Mockup:
> Add password update form

- package.json
- pom.xml
- release-notes/opendistro-for-elasticsearch.security-kibana.release-notes-1.8.1.0.md
bump up version to support ODFE 1.8.1
> support ODFE 1.8.1

- public/apps/configuration/panels/internal-user-edit/attribute-panel.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/internal-user-edit/types.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/internal-user-detail-utils.tsx
- public/apps/configuration/utils/panel-with-header.tsx
Add attributes panel.
Screenshot:
Mockup:
> Add attributes panel

- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/proxy/routes.ts
- server/plugin.ts
*Description of changes:* Implement Proxy authentication.
test endpoint: http://52.37.123.133/_plugin/kibana , only open to Amazon IP 
> Add support for Proxy authentication

- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
Bug fix for internal user editing - add missing import.
> Bug fix for internal user editing

- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/internal-user-detail-utils.tsx
Add user update function.
*Screenshots:*
Mockup:
Failure: Frontend doesn't know whether ES backend has hard limit on password pattern or not. The error message will be refined at server end.
Success:
> Add user update function

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/user-list.tsx
1. Fix a bug that create page doesn't work.
2. Add create/duplicate/export link on user listing.
3. Add create link on role listing.
Before fix:
After fix:
> Improve links

- package.json
- public/apps/configuration/configuration.js
> Drop 'ace' import

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/permission-list.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/action-groups-utils.tsx
- public/apps/configuration/utils/display-utils.tsx
Add permission listing page. Work in progress.
Screenshots:
Mockup:
> Add permission listing page

- public/apps/configuration/panels/permission-list.tsx
- public/apps/configuration/utils/action-groups-utils.tsx
Permission listing - union cluster and index single permissions from local constant.
Mockup:
> Permission listing - union cluster and index single permissions

- server/auth/auth_handler_factory.ts
- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/openid/openid_auth.ts
- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/saml/saml_auth.ts
- server/plugin.ts
- server/routes/index.ts
* move esClient and logger to route handler context
* created an enum for authentication types
* some minor code refactor
> Refactor code, using route handler context

- server/auth/auth_handler_factory.ts
- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/openid/openid_auth.ts
- server/auth/types/openid/routes.ts
- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/saml/saml_auth.ts
- server/backend/opendistro_security_client.ts
- server/multitenancy/tenant_index.ts
- server/plugin.ts
Kibana core refactored `IClusterClient` interface, update plugin to be in sync with kibana master branch
> Catch up Kibana core changes

- .gitignore
- babel.config.js
- package.json
- server/auth/auth_handler_factory.test.ts
- server/auth/auth_handler_factory.ts
- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/openid/openid_auth.ts
- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/saml/saml_auth.ts
- test/jest.config.js
- test/setupTests.ts
*Description of changes:* Add jest config and babel config to allow unit test using Jest
> Add jest and one unit test suite

- index.js
- lib/configuration/backend/opendistro_security_configuration_backend.js
- lib/configuration/validation/audit.js
- public/apps/audit/app.js
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/DisplaySettingGroup.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/EditorBox.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/index.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
- public/apps/configuration/base_controller.js
- public/apps/configuration/configuration.html
- public/apps/configuration/configuration_controller.js
- public/assets/audit_logs.svg
- public/chrome/configuration/enable_configuration.js
(cherry picked from commit f8dd5c71cf4db2151a2ac7374346471ecc56a979)
Backporting commit f8dd5c71cf4db2151a2ac7374346471ecc56a979
> Opendistro-1.4 Audit logging UI changes (#270)

- index.js
- lib/configuration/backend/opendistro_security_configuration_backend.js
- lib/configuration/validation/audit.js
- public/apps/audit/app.js
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/DisplaySettingGroup.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/EditorBox.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/index.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
- public/apps/configuration/base_controller.js
- public/apps/configuration/configuration.html
- public/apps/configuration/configuration_controller.js
- public/assets/audit_logs.svg
- public/chrome/configuration/enable_configuration.js
- Backporting commit f8dd5c71cf4db2151a2ac7374346471ecc56a979
- Adjusted code for react 16.6.0 which is used by Kibana 7.1.1 
- used Fragment instead of <></>
- used state object instead of useState
- fetching data in componentDidMount instead of useEffect
- change the components from function components to class components for Main and EditorBox as state object can be used inside them
- updated functions to be class functions instead of const type
> Opendistro-1.1 Audit logging UI changes (#270)

- index.js
- lib/configuration/backend/opendistro_security_configuration_backend.js
- lib/configuration/validation/audit.js
- public/apps/audit/app.js
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/DisplaySettingGroup.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/EditorBox.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/index.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
- public/apps/configuration/base_controller.js
- public/apps/configuration/configuration.html
- public/apps/configuration/configuration_controller.js
- public/assets/audit_logs.svg
- public/chrome/configuration/enable_configuration.js
(cherry picked from commit b1f87c4e8b463a73441cd80235858e92748d5297)
Audit logging changes cherry-picked from commit b1f87c4e8b463a73441cd80235858e92748d5297
Additional changes:
- Added an import in app.js`import 'ui/autoload/styles';` to autoload styles in Kibana 6.8.6. The styles don't load if this import is not present
> Opendistro-0.10 Audit logging UI changes

- index.js
- lib/configuration/backend/opendistro_security_configuration_backend.js
- lib/configuration/validation/audit.js
- public/apps/audit/app.js
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/DisplaySettingGroup.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/EditorBox.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/index.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
- public/apps/configuration/base_controller.js
- public/apps/configuration/configuration.html
- public/apps/configuration/configuration_controller.js
- public/assets/audit_logs.svg
- public/chrome/configuration/enable_configuration.js
(cherry picked from commit b1f87c4e8b463a73441cd80235858e92748d5297)
Audit logging changes cherry-picked from commit b1f87c4
Additional changes:
- Added an import in app.js `import 'ui/autoload/styles';` to autoload styles in Kibana 6.7.1. The styles don't load if this import is not present
> Opendistro-0.9 Audit logging UI changes

- public/apps/configuration/panels/permission-list.tsx
Permission listing - Add row expansion to view sub permissions. It is an interim solution, will switch to tree view after it is developed in role detail page.
Mockup:
> Add row expansion

- public/apps/configuration/app-router.tsx
> Fix type definition.

- babel.config.js
- server/auth/auth_handler_factory.test.ts
- server/auth/auth_handler_factory.ts
- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/auth/types/index.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/openid/openid_auth.ts
- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/proxy/routes.ts
- server/auth/types/saml/saml_auth.ts
- server/errors/index.ts
- server/errors/no_available_tenant_error.ts
- server/errors/unauthenticated_error.ts
- server/multitenancy/tenant_resolver.ts
- test/jest.config.js
*Description of changes:* Unify common logic for different auth types, tested with basic auth, saml and openid setup
> Unify auth types

- server/auth/types/authentication_type.ts
*Description of changes:* fix a typo
> Fix typo that caused bundles not loading

- index.js
- lib/configuration/validation/audit.js
- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.template.xml
- pom.xml
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
Please check PR https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/310 for additional details and screenshots. This is a backport PR 
> Backport audit logging UI changes & version bump to 1.4.0.1

- index.js
- lib/configuration/validation/audit.js
- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.template.xml
- pom.xml
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
Please check PR #310 for additional details and screenshots. This is a backport PR
> Backport audit logging UI changes & version bump to 1.1.0.6

- index.js
- lib/configuration/validation/audit.js
- opendistro-elasticsearch-security-kibana-plugin.release-notes
- pom.xml
- public/apps/audit/components/main/ContentPanel.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/main.js
- public/apps/audit/components/main/utils.js
Please check PR #320 for additional details and screenshots. This is a backport PR
> Backport audit logging UI changes & version bump to 0.9.0.7

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
- public/apps/configuration/panels/role-mapping/external-identities-panel.tsx
- public/apps/configuration/panels/role-mapping/internal-users-panel.tsx
- public/apps/configuration/panels/role-mapping/types.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/types.ts
- public/apps/configuration/utils/internal-user-list-utils.tsx
- public/apps/configuration/utils/role-mapping-utils.tsx
- public/apps/configuration/utils/toast-utils.tsx
- public/apps/configuration/utils/url-builder.tsx
Implement UI to map users and external identities to role.
**Screenshots:**
_Mockup:_
> Implement Map user page

- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/utils/action-groups-utils.tsx
- server/routes/index.ts
Submit permission group change to server.
TODO: the error message on a toast is not good (under the overlay), need to have a better presentation.
Mockup:
Success:
Failure
> Submit permission group change to server

- public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
- public/apps/configuration/panels/audit-logging/audit-logging.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/utils/toast-utils.tsx
Optimize Toast related code. Refactor to have a shared util function for toast.
> Optimize Toast related code

- common/index.ts
- server/backend/opendistro_security_configuration_plugin.ts
- server/multitenancy/routes.ts
- server/plugin.ts
- server/routes/index.ts
* Add comments including request/response format to APIs
* Fix some API parameter validation
* Added multitenant API registration
* Add a few APIs that were missing comparing to legacy plugin
> Refine Kibana APIs

- lib/auth/types/saml/routes.js
> Fix saml acs url for IDPInitiated login

- server/auth/types/authentication_type.ts
- server/multitenancy/routes.ts
- server/multitenancy/tenant_resolver.ts
*Description of changes:* empty string `''` is used to indicate the user is using global tenant. but if fails the check like `if (tenant)` in ts code. This PR addresses this issue.
*testing*
current tenant is `test_tenant`:
```
% curl -H 'kbn-version: 8.0.0' --include --cookie 'security_authentication=Fe26.2**8631df6c74dc912ea5a106ac7da68fd7a64fa5261aae943f09e344ae80ca40c3*-9uNaKhft5Vw5VVzxSbAmw*2SndzVuhWZF3QVwBYNWY2ceYjZTUBmgnIW0MlPQfU--mxDV_J_yAgqI3C4OU-G13klmcX69RFMsF44nu3L4Tk4zB4vow1y67mOlrEn3hsJx7PXNCv1l8Z-g8-UQmabw6QUBEsekDX4iYLCwJAH8Zx7NFn8IMFzqPJfYZMYdtBbObVGA7-TyuPQ6XUImy1zarINd_sw7KpETwl3yAIB1daCDVsXcUzD99KpuWROR7bz4U8slUW9JBt_05qBRli_0j**c819d51d5c5790851f2793a4c1c014e22e82a5cebbedfec0e693277cf2509300*eKTDcSfWkrik2DqKEKk3HGXi4wHIzv3aobbd4E2TwDE' …
```
> Fix empty tenant string issue

- public/apps/audit/components/main/DisplaySettingGroup.js
- public/apps/audit/components/main/EditSettingGroup.js
- public/apps/audit/components/main/config.js
- public/apps/audit/components/main/main.js
- Removed call outs and integrated message with description
- Removed inner panels for compliance config
- Reduced opacity of sample code to 0.6 as its drawing attention
- Removed language to remove syntax highlighting
- Added helper text for pattern fields
- Removed compliance mode
> Update audit UI

- public/plugin.ts
Fix the issue that 401 error is not handled.
*Test*
Before the change,
After the change,
> handle 401 error during plugin setup

- lib/auth/routes_authtype.js
> Fix: /api/authtype should use APP_ROOT instead of API_ROOT

- public/apps/account/account-app.tsx
- public/apps/account/account-nav-button.tsx
- public/apps/account/constants.tsx
- public/apps/account/types.ts
- public/apps/account/utils.tsx
- public/plugin.ts
Add account menu to top nav.
Mockup:
Confirmed with UX designer on long username: set max width to 256px and wrap text.
> Add account menu to top nav

- public/apps/configuration/utils/role-list-utils.tsx
Fix a bug that tenant is not shown on role listing page
> Fix a bug that tenant is not shown on role listing page

- public/apps/account/role-info-panel.tsx
Fix warning "Each child in a list should have a unique "key" prop." on role-info-panel
> Fix warning "Each child in a list should have a unique "key" prop." on role-info-panel

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro-1.1 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro-0.9 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro-0.10 Backport missing roles fix + authtype change #353 #354

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro-1.0 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.2 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.4 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.3 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.5 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.6 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.7 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.9 Backport missing roles fix + authtype change

- index.js
- lib/auth/routes_authtype.js
- lib/auth/types/saml/routes.js
> Opendistro 1.8 Backport missing roles fix + authtype change

- common/index.ts
- public/apps/account/account-nav-button.tsx
- public/apps/account/utils.tsx
- server/auth/types/basic/routes.ts
Add logout function. After logout, redirect to root page (then kibana will redirect to kibana page then to the login page since authorized).
> Add logout function

- public/apps/configuration/app-router.tsx
Unify breadcrumbs to top nav.
Screenshot:
Before:
After:
> Unify breadcrumbs style

- public/apps/account/password-reset-panel.tsx
Fix deps type issue.
This app runs from start (not from setup). Not sure how to get other deps values. So just pass single CoreStart.
> Fix deps type issue

- public/apps/configuration/panels/get-started.tsx
Updated landing page as per the revised UI.
_mockup_:
> [Landing page] edits as per revised security UI

- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/utils/role-list-utils.test.tsx
- public/apps/configuration/utils/role-list-utils.tsx
* Add type for role listing
* Add unit test for role listing utils
* Fix for some labels on role listing page
Screenshots:
Mockup:
Before change:
After change:
> Add type and unit test for role listing.

- common/index.ts
- public/apps/account/account-nav-button.tsx
- public/apps/account/tenant-selection-page.tsx
- public/apps/account/tenant-switch-panel.tsx
- public/apps/login/login-page.tsx
- public/plugin.ts
* Add tenant selection page
* Fix some type reference on tenant selection modal
Conditions to skip this page:
1. Multi-tenancy disabled
2. Security admin
Screenshot:
Mockup:
> Add tenant selection page

- public/apps/configuration/panels/tenant-list/tenant-list.tsx
Refactoring of delete confirm modal code in Tenant list page
> Tenant List: refactor delete confirm modal

- public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
This is to address UX feedback to add default desc sorting for Authentication table.
*Test*
> add default desc sorting for Authentication table

- package.json
- pom.xml
- public/apps/accountinfo/accountinfo.js
- public/apps/configuration/configuration.js
- public/apps/configuration/sections/actiongroups/index.js
- public/apps/configuration/sections/internalusers/index.js
- public/apps/configuration/sections/roles/index.js
- public/apps/configuration/sections/rolesmapping/index.js
- public/apps/configuration/sections/securityconfiguration/index.js
- public/apps/configuration/sections/tenants/index.js
- public/apps/customerror/customerror.js
- public/apps/login/login.js
- public/apps/multitenancy/multitenancy.js
*Changes for new odfe version 1.10 release *
> Support OD Version 1.10.0

- public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
> add a period to subtitle of authentication table

- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- Tenant name on the toast resolved for global and private.
- Fix toast for View/Create Dashboard and View/Create Visualization.
**Before this fix:**
**After this fix:**
> Fix tenant name on the toast

- public/apps/configuration/constants.tsx
- public/plugin.ts
- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/backend/opendistro_security_client.ts
- server/backend/opendistro_security_configuration_plugin.ts
- server/backend/opendistro_security_plugin.ts
- server/plugin.ts
- server/session/security_cookie.ts
- test/jest.config.integration.js
- test/jest_integration/basic_auth.test.ts
*Description of changes:* Support anonymous auth
see: https://docs.search-guard.com/latest/kibana-authentication-anonymous#using-kibana-with-anonymous-authentication
*Test:
```
% curl http://localhost:5601/jpo/auth/anonymous
{"username":"opendistro_security_anonymous","tenants":{"opendistro_security_anonymous":true},"roles":["own_index"],"backendroles":["opendistro_security_anonymous_backendrole"],"selectedTenants":"__user__"}
```
> Add support for anonymous auth

- public/apps/configuration/panels/expression-modal.tsx
Make view expression column left aligned.
**Screenshot:**
> Make view expression column left aligned

- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/utils/context-menu.tsx
Change context menu button text color from black to blue (normal) and red (delete).
Screenshots:
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/63078162/91230656-c0354200-e6e0-11ea-985c-314909e96a79.png)|![image](https://user-images.githubusercontent.com/63078162/91230266-0f2ea780-e6e0-11ea-9ebc-bfeb584d5526.png)|
|![image](https://user-images.githubusercontent.com/63078162/91230406-4bfa9e80-e6e0-11ea-95ea-3410ac87d608.png)|![image](https://user-images.githubusercontent.com/63078162/91230537-8ebc7680-e6e0-11ea-99c5-a5736536cb6f.png)|
|![image](https://user-images.githubusercontent.com/63078162/91230695-d2af7b80-e6e0-11ea-8f44-5ccfbf41cc64.png)|![image](https://user-images.githubusercontent.com/63078162/91230308- …
> Change context menu color to blue/red

- public/apps/configuration/app-router.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/utils/context-menu.tsx
* Enable edit/delete on role detail page.
* Fix some `Each child in a list should have a unique "key" prop` warning.
|Mockup|Implementation|
|--|--|
|![image](https://user-images.githubusercontent.com/63078162/91359067-b414b780-e7a8-11ea-8b2d-7139cf92ddcf.png)|![image](https://user-images.githubusercontent.com/63078162/91356436-89c0fb00-e7a4-11ea-9b3b-23df14da45b5.png)|
|![image](https://user-images.githubusercontent.com/63078162/91358707-20db8200-e7a8-11ea-810b-22d747a2aaf0.png)|![image](https://user-images.githubusercontent.com/63078162/91346151-414e1100-e795-11ea-807f-80476f517a97.png)|
|N/A|![image](https://user-images.githubusercontent.com/63078162/91358598-f38ed400-e7a7-11ea-9005-5c133c9634a7.png)| …
> Enable edit/delete on role detail page

- public/apps/configuration/_index.scss
- public/apps/configuration/panels/get-started.tsx
Make Open in new window button right aligned to the container. 
As main content panel becomes narrow, button shifts to top-right corner which can easily missed out by the user. This change is to address that concern.
**Before:**
**After this change:**
> Make button right aligned to the container

- public/apps/account/password-reset-panel.tsx
- public/apps/configuration/panels/internal-user-edit/attribute-panel.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/permission-list/edit-modal.tsx
- public/apps/configuration/panels/role-mapping/external-identities-panel.tsx
- public/apps/configuration/utils/password-edit-panel.tsx
* Add missing ending periods. 
* Fix a typo.
> Add missing ending periods. Fix typo

- public/apps/account/account-nav-button.tsx
Update "View roles" button text to "View roles and identities" since it shows both roles and external identities.
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/63078162/91479366-2b545500-e856-11ea-97b6-c0191a0b17ec.png)|![image](https://user-images.githubusercontent.com/63078162/91479445-4aeb7d80-e856-11ea-9395-32e17cca3f81.png)|
> Update "View roles" button text

- public/apps/configuration/app-router.tsx
> shorten name for authentication and authorization

- public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
- public/apps/configuration/panels/auth-view/authorization-panel.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-view/index-permission-panel.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/panels/role-view/tenants-panel.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/user-list.tsx
Set auto column width on all tables
Before:
After:
> Set auto column width on all tables

- public/apps/configuration/panels/get-started.tsx
Update the instruction message on landing page.
*Test*
Implementation
Mockup
> [AuditLogging] update the instruction message on the landing page

- .github/workflows/ci.yml
- package.json
- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/openid/helper.ts
- server/auth/types/openid/openid_auth.ts
- server/auth/types/openid/routes.ts
- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/saml/saml_auth.ts
- server/utils/next_url.ts
* add support for OIDC token refresh
* support nextUrl in OIDC workflow
Tested manually
> Fix OIDC token refresh and nextUrl

- pom.xml
> Changed tag version for scm

- package.json
- public/apps/configuration/utils/toast-utils.test.tsx
Add unit test for Toast custom hook and toast util
*UT result:*
```
% yarn test:jest public/apps/configuration/utils/toast-utils* --coverage --collectCoverageFrom=public/apps/configuration/utils/toast-utils.tsx
$ NODE_PATH=../../node_modules ../../node_modules/.bin/jest --config ./test/jest.config.js public/apps/configuration/utils/toast-utils.test.tsx public/apps/configuration/utils/toast-utils.tsx --coverage --collectCoverageFrom=public/apps/configuration/utils/toast-utils.tsx
PASS  public/apps/configuration/utils/toast-utils.test.tsx
Toast utils
useToastState
✓ should return an empty array when there is no toasts (12ms)
✓ should add a toast (3ms)
✓ should add multiple toasts (2ms)
✓ should remove a toast (1ms)
Create …
```
> Add unit test for Toast custom hook

- public/apps/configuration/panels/get-started.tsx
Address UX feedback to update the button text.
*Test*
> [AuditLogging] update the button text on landing page

- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/audit-logging/audit-logging.tsx
- public/apps/configuration/panels/get-started.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/utils/form-row.tsx
- public/apps/configuration/utils/panel-with-header.tsx
Add the help link to the target documentation link.
*Test*:
Verified that the doc is opened in a separate tab.
> [AuditLogging] add the help link for storage location

- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-edit/index-permission-panel.tsx
- public/apps/configuration/panels/role-edit/tenant-panel.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/user-list.tsx
- Fix text defects (spelling, grammar correction)
> Fix text defects

- server/auth/types/authentication_type.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/jwt/routes.ts
*Description of changes:* Add a jwt logout API, fix jwt handling in auth handler
> Add jwt logout and fix JWT header handling

- public/apps/account/log-out-button.tsx
- server/auth/types/saml/routes.ts
*Description of changes:* Fix saml logout, use get method to avoid CORS error
> Fix SAML logout

- public/apps/account/account-nav-button.tsx
- public/apps/account/log-out-button.tsx
*Description of changes:* When using proxy auth, hide the log out button.
> Hide logout button for proxy authentication

- public/apps/configuration/_index.scss
- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/audit-logging/audit-logging.tsx
- public/apps/configuration/panels/auth-view/auth-view.tsx
- public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
- public/apps/configuration/panels/auth-view/authorization-panel.tsx
- public/apps/configuration/panels/get-started.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/utils/display-utils.tsx
- public/apps/configuration/utils/form-row.tsx
- public/apps/configuration/utils/panel-with-header.tsx
Create a component for external link. 
Also added a few doc links for authentication & authentication.
Lint has optimized some whitespace and wrapping. Verified on UI that the whitespace is still there.
> refactor external link to component

- public/apps/configuration/panels/audit-logging/constants.tsx
Address some text description requested by UX designers.
*Test*
> [AuditLogging] update some text description

- package.json
- pom.xml
- public/app.css
- release-notes/opendistro-for-elasticsearch-security-kibana.release-notes-1.10.1.0.md
Updating plugin to work with Kibana 7.9.1
All unit tests pass.
Bug fixes for euiBadge display
> Support OD 1.10.1 and bug fixes

- public/apps/configuration/panels/user-list.test.tsx
- public/apps/configuration/panels/user-list.tsx
Add unit test for user listing page.
Coverage report:
**Before:**
% yarn test:jest --coverage
$ NODE_PATH=../../node_modules ../../node_modules/.bin/jest --config ./test/jest.config.js --coverage
PASS  public/apps/configuration/panels/role-edit/tenant-panel.test.tsx (13.711s)
PASS  public/apps/configuration/panels/role-edit/role-edit.test.tsx (13.799s)
PASS  public/apps/configuration/panels/role-list.test.tsx (14.341s)
PASS  public/apps/configuration/utils/toast-utils.test.tsx
PASS  server/auth/auth_handler_factory.test.ts
PASS  public/apps/configuration/panels/role-edit/index-permission-panel.test.tsx
PASS  public/apps/configuration/utils/tenant-utils.test.tsx
PASS …
> Add unit test for user listing page

- public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
- public/apps/configuration/panels/audit-logging/audit-logging.tsx
- public/apps/configuration/panels/audit-logging/code-editor.tsx
- public/apps/configuration/panels/audit-logging/constants.tsx
- public/apps/configuration/panels/audit-logging/test/audit-logging-edit-settings.test.tsx
- public/apps/configuration/panels/audit-logging/test/audit-logging.test.tsx
- public/apps/configuration/panels/audit-logging/test/code-editor.test.tsx
- public/apps/configuration/panels/audit-logging/test/edit-setting-group.test.tsx
- public/apps/configuration/panels/audit-logging/test/view-setting-group.test.tsx
- public/apps/configuration/utils/audit-logging-utils.tsx
Add unit tests for audit logging related components.
**Before this change**
- All files
yarn test:jest --coverage
-----------------------------------------------|---------|----------|---------|---------|-------------------
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------------------------|---------|----------|---------|---------|-------------------
All files                                      |   11.58 |    10.24 |   13.25 |    11.3 |
- Limit the coverage to audit logging directory only.
_zero_
**After this change**
Current coverage.
- All files
yarn test:jest --coverage
-----------------------------------------------|---------|----------|---------|- …
> [AuditLogging] add unit tests

- public/apps/configuration/panels/auth-view/auth-view.tsx
- public/apps/configuration/panels/auth-view/instruction-view.tsx
- public/apps/configuration/panels/auth-view/test/auth-view.test.tsx
- public/apps/configuration/panels/auth-view/test/authentication-sequence-panel.test.tsx
- public/apps/configuration/panels/auth-view/test/authorization-panel.test.tsx
- public/apps/configuration/panels/auth-view/test/instruction-view.test.tsx
- public/apps/configuration/utils/auth-view-utils.tsx
add unit test for authc & authz
Coverage
Before this change,
1. all front end pages
`yarn test:jest --coverage --collectCoverageFrom=public/**`
-----------------------------------------------|---------|----------|---------|---------|-------------------
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------------------------|---------|----------|---------|---------|-------------------
All files                                      |    32.2 |    31.99 |   27.92 |   32.27 |
-----------------------------------------------|---------|----------|---------|---------|-------------------
After this change,
1. all front end pages
`yarn test:jest --coverage …
> add unit test for authc & authz

- public/apps/account/utils.tsx
- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/utils/request-utils.ts
- public/apps/configuration/utils/role-list-utils.tsx
- public/apps/configuration/utils/role-mapping-utils.tsx
* Introduce a utility function that can ignore some http error code, and apply the function to wherever applicable
* Delete also role mappings when deleting a role
> Delete also role mappings when deleting a role

- public/apps/configuration/_index.scss
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-view/index-permission-panel.tsx
- public/apps/configuration/panels/role-view/tenants-panel.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/user-list.tsx
- public/apps/configuration/utils/display-utils.tsx
Fix the font size of table items to be same.
Screenshots:
> Fix the font size of table items

- public/apps/configuration/panels/auth-view/auth-view.tsx
- public/apps/configuration/panels/auth-view/authorization-panel.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/user-list.tsx
* Fix a bug that auth listing not showing
* Update help text
> Fix a bug that auth listing not showing, update help text

- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/user-list.tsx
> Fix text defect

- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/internal-user-edit/attribute-panel.tsx
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/permission-list/permission-list.tsx
- public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
- public/apps/configuration/panels/role-edit/index-permission-panel.tsx
- public/apps/configuration/panels/role-edit/role-edit.tsx
- public/apps/configuration/panels/role-edit/tenant-panel.tsx
- public/apps/configuration/panels/role-list.tsx
- public/apps/configuration/panels/role-mapping/external-identities-panel.tsx
- public/apps/configuration/panels/role-mapping/internal-users-panel.tsx
- public/apps/configuration/panels/role-view/cluster-permission-panel.tsx
- public/apps/configuration/panels/role-view/index-permission-panel.tsx
- public/apps/configuration/panels/role-view/tenants-panel.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/user-list.tsx
> Make learn more links active

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- build_tools/build_plugin.js
- package.json
*Description of changes:* build plugin in github actions
tested:  https://github.com/zengyan-amazon/security-kibana-plugin-1/actions/runs/267759964
> Update GitHub action

- .github/workflows/cd.yml
> Fix plugin name in CD workflow

- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.test.tsx
- public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
- public/apps/configuration/panels/role-mapping/external-identities-panel.test.tsx
- public/apps/configuration/panels/role-mapping/external-identities-panel.tsx
- public/apps/configuration/panels/role-mapping/internal-users-panel.test.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.test.tsx
Add unit test for role-mapping edit page
Coverage:
Folder-level:
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------|---------|----------|---------|---------|-----------------------------------
public/apps/configuration/panels/role-mapping       |   87.72 |       90 |      90 |    87.5 |                                                                 
RoleEditMappedUser.tsx                             |   82.05 |       75 |      75 |   82.05 | 74-75,87-88,100,125,161                                         
external-identities-panel.tsx                      |     100 |      100 |     100 |     100 |                                                                 
internal-users-panel.tsx …
> Add unit test for role-mapping edit page

- server/routes/index.ts
*Description of changes:* Update entity id regex to make sure entity id not starting with punctuations.
> Update entity id regex

- .github/workflows/cd.yml
- .github/workflows/ci.yml
*Description of changes:* Update CI/CD workflow not to use hard coded kibana version
test run: https://github.com/zengyan-amazon/security-kibana-plugin-1/runs/1153342708
> GitHub action refactor

- server/multitenancy/tenant_resolver.ts
*Description of changes:* Fix readonly tenant switch issue
> Fix readonly tenant switch

- server/plugin.ts
- server/routes/auty_type_routes.ts
```
% curl localhost:5601/vbp/api/authtype
{"authtype":"basicauth"}
```
> Add auth type API

- public/apps/configuration/panels/role-view/cluster-permission-panel.test.tsx
- public/apps/configuration/panels/role-view/cluster-permission-panel.tsx
- public/apps/configuration/panels/role-view/index-permission-panel.test.tsx
- public/apps/configuration/panels/role-view/index-permission-panel.tsx
- public/apps/configuration/panels/role-view/role-view.test.tsx
- public/apps/configuration/panels/role-view/role-view.tsx
- public/apps/configuration/panels/role-view/tenants-panel.test.tsx
- public/apps/configuration/panels/role-view/tenants-panel.tsx
Add unit test for role view
Coverage:
Folder-level:
File                                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                               
-----------------------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------
public/apps/configuration/panels/role-view          |   70.68 |    57.14 |      50 |   71.21 |                                                                 
cluster-permission-panel.tsx                       |      75 |       75 |      50 |      75 | 43                                                              
index-permission-panel.tsx                         | …
> Add unit test for role view

- .github/workflows/ci.yml
- README.md
*Description of changes:* Update branch name
> Update branch name in README and CI workflow

- THIRD-PARTY
*Description of changes:* Add THIRD-PARTY file
> Add THIRD PARTY file

- public/apps/login/login-page.tsx
Fix login button trigger on Enter. Passed `component="form"` to EuiForm so that it will render as Form.
> Fix login button trigger on Enter

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.10.1.1.md
*Description of changes:* Add release note file
> Release notes dir

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.10.1.1.md
*Description of changes:* Categorize changes in release note
> Categorize changes in release note

- public/apps/configuration/panels/__snapshots__/get-started.test.tsx.snap
- public/apps/configuration/panels/get-started.test.tsx
- public/apps/configuration/panels/get-started.tsx
Add unit test for landing page
```
% yarn test:jest_ui public/apps/configuration/panels/get-started**                                                                                  
$ node ./test/run_jest_tests.js --config ./test/jest.config.ui.js public/apps/configuration/panels/get-started.test.tsx public/apps/configuration/panels/get-started.tsx
PASS  public/apps/configuration/panels/get-started.test.tsx
Get started (landing page)
✓ renders (11ms)
should handle assignments to window.location.href correctly
✓ Review authentication and authorization button click (19ms)
✓ Explore existing roles button click (9ms)
✓ Create new role button click (9ms)
✓ Map users to a role button click (12ms)
✓ Create internal user button …
```
> Add unit test for landing page

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.10.1.1.md
*Description of changes:* Refine release node
> Refine release note

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.10.1.2.md
*Description of changes:* add release note for 1.10.1.2
> Add release note for v1.10.1.2

- public/apps/configuration/panels/permission-list/edit-modal.tsx
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/530
Allow adding arbitrary permission.
Note: this will not add the arbitrary permission to permission table.
> Allow adding arbitrary permission.

- public/plugin.ts
*[Issue](https://issues.amazon.com/issues/Kibana-1000)*
*As per requirement Security is pushed under Management Category*
> changes for Kibana side menu

- public/apps/configuration/panels/get-started.tsx
Fixed button overflow issue on landing page.
Before:
After:
> Fix button overflow issue

- public/apps/account/account-app.tsx
- public/apps/account/account-nav-button.tsx
- public/apps/account/tenant-switch-panel.tsx
- public/apps/account/types.ts
Fix tenant name in Profile menu
Screenshots:
_mockup_
_Implementation_
> Fix tenant name in Profile menu

- kibana.json
- package.json
- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.11.0.0.md
*[Issue](https://issues.amazon.com/issues/Kibana-999)*
*Bumped up the odfe version*
> Support OD version 1.11.0

- public/apps/account/account-nav-button.tsx
- public/apps/account/tenant-selection-page.tsx
- public/apps/account/tenant-switch-panel.tsx
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/523
*Description of changes:*  
Adding another function to distinguish 'confirm' and 'cancel'. Refresh page on 'confirm'.
> Refresh page after switching tenant 

- server/auth/types/authentication_type.ts
*Description of changes:* Only extend session when keepalive is configured
> Only extend session when keepalive is configured

- server/auth/types/authentication_type.ts
- server/auth/types/basic/basic_auth.ts
- server/auth/types/jwt/jwt_auth.ts
- server/auth/types/openid/openid_auth.ts
- server/auth/types/proxy/proxy_auth.ts
- server/auth/types/saml/saml_auth.ts
- server/multitenancy/tenant_resolver.ts
*Issue #, if available:* #523
*Description of changes:* Use tenant in cookie for proxy auth
> Use tenant in cookie for proxy auth

- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/get-started.tsx
Add purge cache button. This is a feature parity to security plugin before 1.10.
> Add purge cache button

- build_tools/build_plugin.js
Fix a bug the build is incomplete when folder name is differ from plugin id
> Fix a bug the build is incomplete 

- server/index.ts
- server/session/security_cookie.ts
*Description of changes:* Read and set `sameSite` option for cookie from config
> Add cookie sameSite settings

- server/auth/types/openid/routes.ts
- server/auth/types/proxy/routes.ts
- server/auth/types/saml/routes.ts
- server/utils/next_url.ts
*Description of changes:* Validate nextUrl parameter, make sure the `nextUrl` is relative url to avoid malicious redirection
> validate nextUrl to be relative URL

- public/apps/configuration/panels/audit-logging/constants.tsx
- Update description for audit logging log diffs. 
> Update description for audit logging log diffs

- common/index.ts
- public/apps/account/account-app.tsx
- public/apps/customerror/_index.scss
- public/apps/customerror/custom-error.tsx
- public/plugin.ts
> Add missing role error page

- server/multitenancy/tenant_index.ts
*Description of changes:* when index migration failed, exit kibana process. see comment in code for reasoning
> Fail Kibana process when index migration failed

- public/apps/configuration/panels/expression-modal.tsx
- public/apps/configuration/panels/test/__snapshots__/expression-modal.test.tsx.snap
- public/apps/configuration/panels/test/__snapshots__/nav-panel.test.tsx.snap
- public/apps/configuration/panels/test/expression-modal.test.tsx
- public/apps/configuration/panels/test/nav-panel.test.tsx
- public/apps/configuration/utils/test/__snapshots__/display-utils.test.tsx.snap
- unit test for expression modal and nav panel
*Folder level:*
File                                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                    
-----------------------------------------------------|---------|----------|---------|---------|--------------------------------
expression-modal.tsx                               |     100 |      100 |     100 |     100 |       
nav-panel.tsx                                      |     100 |      100 |     100 |     100 |     
Before this PR: …
> Unit test for expression modal and nav panel

- .codecov.yml
- README.md
- Adds coverage icon to README
> Adds coverage icon to README

- package.json
- server/utils/next_url.ts
*Description of changes:* Update nextUrl validation function
> Update nextUrl validation function

- server/auth/types/openid/openid_auth.ts
*Description of changes:* Fix response code for unauthenticated request, should return 401, not 403.
> Fix response code for unauthenticated request

- public/types.ts
- server/index.ts
*Description of changes:* Add a new configuration for ui rendering
> Add a new config

- public/apps/configuration/app-router.tsx
- Updates Navigation “Authc & authz” to “Authentication”
Screenshot:
> Update Navigation Authc & authz to Authentication

- kibana.json
- package.json
**Description**
Bump up security kibana plugin version to 1.12.  Targeting kibana 7.10
File change in kibana.json, package.json
> For ODFE 1.12 release

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.12.0.0.md
> Add version 1.12 that targeting kibana 7.10 and release note. (#627)

- public/plugin.ts
Adjust the side menu bar for kibana security plugin
> Kibana side menu bar adjust for security plugin

- .github/workflows/cd.yml
Fix a bug of file name in CD workflow. 
> CD testing

- public/plugin.ts
Decide to remove the logo for the side bar
> remove logo for side bar

- .github/workflows/cd.yml
- kibana.json
Update plugin name to match opendistro kibana plugin naming convention.
> Update plugin name to match opendistro kibana plugin naming convention

- .github/workflows/integration-test.yml
- public/plugin.ts
- server/auth/types/openid/routes.ts
- server/index.ts
- test/constant.ts
- test/jest.config.server.js
- test/jest_integration/basic_auth.test.ts
- test/jest_integration/multi_tenancy.test.ts
- test/jest_integration/security_entity_api.test.ts
> Merge main to 1.12

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.12.0.0.md
Change the release note format following: https://quip-amazon.com/CcyaAm4vFLaL/ODFE-Plugin-Release-Notes-Unified-Format-for-All-Plugin-Owners
> make change of release notes

- .github/workflows/integration-test.yml
* Use Java 14 instead of 11 (supported since es 7.7: https://www.elastic.co/support/matrix#matrix_jvm)
* Use linux distribution instead of darwin
> Improve CI env setup

- public/apps/account/account-nav-button.tsx
- public/apps/account/tenant-switch-panel.tsx
- public/apps/account/test/__snapshots__/account-nav-button.test.tsx.snap
- public/apps/account/test/__snapshots__/tenant-switch-panel.test.tsx.snap
- public/apps/account/test/account-nav-button.test.tsx
- public/apps/account/test/tenant-switch-panel.test.tsx
* Sort custom tenant name by ASCII
* Replace EuiSuperSelect with EuiComboBox to enable search function
Screenshots:
|Func|Before|After|
|--|--|--|
|Sorting|![image](https://user-images.githubusercontent.com/63078162/103834017-2474f480-5037-11eb-87fa-ef8f4402ae14.png)|![image](https://user-images.githubusercontent.com/63078162/103833961-06a78f80-5037-11eb-8576-826028daf79f.png)|
|Search||![image](https://user-images.githubusercontent.com/63078162/103833884-e546a380-5036-11eb-9660-7a5f03b6e9bb.png)|
> Tenant selection panel improvement

- server/auth/types/openid/helper.test.ts
- server/auth/types/openid/helper.ts
- server/auth/types/openid/routes.ts
*Issue #, if available:* #600
*Description of changes:* Allow customer to use custom OIDC logout url with query parameters.
> Allow adding query parameters to OIDC logout url

- kibana.json
- package.json
> Add support for 7.10.2

- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.13.0.0.md
> Add release note for 1.13

- .github/workflows/ci.yml
- kibana.json
- package.json
- public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
- public/apps/configuration/panels/internal-user-edit/test/internal-user-edit.test.tsx
- public/apps/configuration/types.ts
- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.13.0.0.md
- server/routes/index.ts
> Merge 1.13 into main

- server/auth/types/authentication_type.ts
*Description of changes:* backport session keepalive fix (#547) to v1.11 branch 
> Only extend session when keepalive is configured (#547)

- kibana.json
- package.json
- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.13.0.0.md
- release-notes/opendistro-for-elasticsearch-security-kibana-plugin.release-notes-1.13.0.1.md
Improve release note for 1.13. Categorize PRs. 
> Improve release note for 1.13

- public/apps/account/tenant-switch-panel.tsx
- public/apps/account/test/__snapshots__/tenant-switch-panel.test.tsx.snap
*Issue #, if available:* [#718](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/718)
Cherry-pick the change of [#722](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/722) from main to 7.9.1
> Save tenant selection by default and remove the checkbox

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
N/A
Add DCO to the CONTRIBUTING doc and included the PR template.
> Update Contributing doc and add PR template

- public/apps/configuration/constants.tsx
> Update list of permissions available in UI

- README.md
- public/apps/configuration/panels/audit-logging/audit-logging.tsx
Follow up with https://github.com/opensearch-project/security-dashboards-plugin/pull/751
> fix readme badge and audit log text

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-beta1.md
…ta1.md
Documentation
N/A
Update content for `1.0.0.0-beta1` release notes
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in …
> Update 1.0.0.0-beta1 release notes

- README.md
- public/apps/configuration/constants.tsx
- public/apps/configuration/panels/audit-logging/test/__snapshots__/audit-logging.test.tsx.snap
- public/apps/configuration/panels/role-view/test/__snapshots__/role-view.test.tsx.snap
- public/apps/configuration/panels/tenant-list/test/__snapshots__/tenant-list.test.tsx.snap
- public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
Maintenance, Documentation
N/A
Changes all document links to point at opensearch.org documents
Unit tests, manual tests …
> Point document links to opensearch.org

- public/apps/account/utils.tsx
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- test/jest_integration/basic_auth.test.ts
re-push for https://github.com/opensearch-project/security-dashboards-plugin/pull/765
> Changes regarding the anonymous auth flow

- .github/workflows/integration-test.yml
- server/auth/types/saml/routes.ts
- server/backend/opensearch_security_configuration_plugin.ts
- server/backend/opensearch_security_plugin.ts
- test/jest_integration/basic_auth.test.ts
Enhancement
Points security dashboards plugin to updated security plugin APIs
Unit testing, integration testing
Change …
> Point OpenSearch Dashboards to to new back end APIs

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-beta1.md
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-rc1.md
Maintenance
Create release notes for rc-1 and Bump version to 1.0.0.0-rc1
OpenSearch RC1 release
No changes in behavior
IT
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of …
> Create release notes for rc-1 and Bump version to 1.0.0.0-rc1

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-beta1.md
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-rc1.md
Maintenance
Change the titles of release notes
RC1 release
No change in behavior
8. __Is it backport from main branch?__ …
> Change the titles of release notes

- public/apps/account/utils.tsx
- public/apps/login/login-page.tsx
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/utils/next_url.ts
1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_): Bug fix
2. __Github Issue # or road-map entry, if available:__ #741 
3. __Description of changes:__ making the redirect path url safe.
4. __Why these changes are required?__ :  these changes are required so that users can redirect properly to the requested url.
5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_): in old behaviour we were just using the `request.url.pathname` as is, if it contains `/` that would give a `http 400 bad request`, we need to encode the `nextUrl` so that it is url safe
6. __Testing …
> Refactoring the redirect logic for anonymous auth, added new type ParsedUrlQueryParams

- public/apps/account/utils.tsx
- public/apps/login/login-page.tsx
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/utils/next_url.ts
- test/jest_integration/basic_auth.test.ts
Backporting
2. __Github Issue # or road-map entry, if available:__ #741 
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_) 
Yes, #768 …
> Backport Issue(#768) to branch opendistro-1.12

- public/apps/account/utils.tsx
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/utils/next_url.ts
- test/jest_integration/basic_auth.test.ts
Backporting
2. __Github Issue # or road-map entry, if available:__ #741 
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_) 
Yes, #768 …
> Backport Issue(#768) to branch opendistro-1.11

- public/apps/account/utils.tsx
- public/apps/login/login-page.tsx
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/utils/next_url.ts
- test/jest_integration/basic_auth.test.ts
Backporting
2. __Github Issue # or road-map entry, if available:__ #741 
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_) 
Yes, #768 …
> Backport Issue(#768) to branch opendistro-1.13

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-ga.md
Maintenance
Add 1.0.0.0-GA release notes
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …
> add ga release notes

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-ga.md
> remove rc1 postfixes

- server/auth/types/saml/routes.ts
(cherry picked from commit 08d94f7dade0018005462df99a4d83c7cda70f4e)
8. __Is it backport from main branch?__ (_If yes, …
> [opensearch-1.0.0.0-beta1][backport] Fixing JSON parsing in SAML for strings that contain '\' character

- server/auth/types/saml/routes.ts
> [opendistro-1.13][backport] Fixing JSON parsing in SAML for strings that contain '\' character

- server/auth/types/saml/routes.ts
> [opendistro-1.12][backport] Fixing JSON parsing in SAML for strings that contain '\' character

- server/auth/types/basic/routes.ts
- server/auth/types/openid/routes.ts
- server/auth/types/saml/routes.ts
> [opendistro-1.11][backport] Fixing JSON parsing in SAML for strings that contain '\' character

- .github/workflows/integration-test.yml
- server/index.ts
> Fix CI test for opensearch 1.0.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-ga.md
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.0.0-rc1.md
> Update ga release notes with rc1 PRs

- public/apps/account/utils.tsx
- server/auth/types/basic/basic_auth.ts
- server/auth/types/basic/routes.ts
- server/auth/types/saml/routes.ts
- server/utils/next_url.ts
- test/jest_integration/basic_auth.test.ts
Enhancement
Merge branch `opendistro-1.11` to branch `7.9.1`, for accommodate changes made on both side
Features required on `opendistro-1.11` is only implemented on branch `7.9.1`
7. __TO-DOs, if any:__ (_Please describe …
> Merge odfe 1.11 to 7.9.1

- public/apps/configuration/constants.tsx
Co-authored-by: kevinhwang <hellokevinhwang@gmail.com>
Bug fix
Add back resolve permission in UI which was accidentally removed
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of …
> add resolve pemission to UI

- public/apps/account/account-app.tsx
Bug fix
The fix is to address the bug reported at issue #805 
Add refresh page to `account-app.tsx`
The refresh page is required to update the tenant when a different user login
Previously, after logging to a new user, the tenant displayed on upper right panel was not be the actual tenant loaded in frontend server, it was the tenant for …
> Add refresh page to account-app.tsx to solve the tenant display issue

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.1.0.md
> Bump plugin version to 1.0.1.0

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.1.0.0.md
> Bump version to 1.1.0.0

- .github/workflows/integration-test.yml
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.1.0.0.md
> Build OpenSearch 1.1 branch in CI

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.2.0.0
> Bump version to 1.2.0

- .github/workflows/dco.yml
Adding DCO check 
#835 
DCO check in GitHub workflows
No DCO check on commits prior to this PR.
N/A
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github …
> Adding DCO check to repo. Closes #835

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.2.0.0
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.2.0.0.md
> update release note

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.2.0.0.md
Maintenance
Added copyright notice updates to release notes for 1.2
8. …
> Updated release notes for 1.2 with copyright updates

- .github/workflows/integration-test.yml
> Remove jobs building os core in integration test

- .github/workflows/integration-test.yml
- .github/workflows/unit-test.yml
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.2.0.0.md
Signed-off-by: Jason <hsiang@amazon.com>
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …
> remove job building os core in integration test (#860)

- server/auth/types/saml/routes.ts
Bug Fix
Removing escaping \ as it is handled by backend security
8. __Is it backport from main branch?__ (_If yes, please …
> Removing escaping \ as it is handled by backend security

- .eslintrc.js
- .github/workflows/unit-test.yml
Unit tests currently run using the `main` branch of Dashboards as opposed to `1.x` as everything else. This is causing UTs to fail.
Maintenance
N/A
7. __TO-DOs, if any:__ …
> Using 1.x branch of Dashboards for unit tests

- DEVELOPER_GUIDE.md
- README.md
Improved developer guide and readme
Documentation
N/A
8. __Is it backport …
> Improved developer guide

- .github/workflows/integration-test.yml
Signed-off-by: Jason <hsiang@amazon.com>
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …
> change ci backend version to 1.2.4

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- public/apps/account/account-app.tsx
- public/apps/configuration/constants.tsx
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.0.1.0.md
> Backport to 1.0

- DEVELOPER_GUIDE.md
#887 removed a portion of the developer guide by mistake. Adding back.
Documentation
Documentation was incomplete
N/A
N/A
N/A
> Added back removed portion of developer guide

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.0.0.md
Release notes for version 1.3.0.0
Maintenance
> Adds release notes for 1.3.0.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.0.0.md
Fixes typo introduced in: #918 and adds this PR to release notes
> Release notes 1.3

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.2.
> Incremented version to 1.3.2.

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.2.0.md
Followed the process used by #955 to create the release notes
> Release notes for 1.3.2

- .github/workflows/integration-test.yml
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation] Maintenance
ITs and UTs
> Build OSD 2.0 branch

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.1.0.md
Release-notes for 1.3.1
Followed steps in #955
Maintenance
> Adds 1.3.1.0 release notes

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Darshit Chanpura <dchanp@amazon.com>
(cherry picked from commit 426ec61840e468e2e88d5dd45b47f775406cebaf)
> [Backport 2.0] Fixes broken main build which was caused due to version mismatch (#989)

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Incremented version to 2.0.1.
However, this PR will need https://github.com/opensearch-project/security/pull/1881 merged first and start the build to get security artifacts.
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
> Incremented version to 2.0.1

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.1.0.0.md
> Adds release notes for 2.1.0

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.4 
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
> Incremented version to 1.3.4.

- server/multitenancy/tenant_resolver.ts
Backport https://github.com/opensearch-project/security-dashboards-plugin/pull/1024 to branches "1.3", "1.2", "1.1", 1.0"/
Follow up issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/1012
> Backport #1024 tenant resolver

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
> Increment version to 2.2.0.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.2.0.0.md
Updating release notes to use release note categories from https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md. 
Maintenance
> Update release notes for 2.2.0.0 release

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Version increment 2.2.1
Part of: https://github.com/opensearch-project/opensearch-build/issues/2481
> Version increment 2.2.1

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.3.0.0.md
Adds release notes for 2.3.0.0
https://github.com/opensearch-project/security-dashboards-plugin/issues/1089
> Add release notes for 2.3.0.0

- .github/workflows/integration-test.yml
- .github/workflows/prerequisite-test.yml
- opensearch_dashboards.json
- package.json
Increments version to 2.4.0.0
Maintenance
https://github.com/opensearch-project/security-dashboards-plugin/issues/1089
> Increment version to 2.4.0.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.6.0.md
Signed-off-by: Vinayak Kothari <vkothar@amazon.com>
Adding Release notes for 1.3.6 
Documentation
> Release notes 1.3.6

- .github/workflows/integration-test.yml
- .github/workflows/prerequisite-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.3.1 to prepare for next patch
> Bump version to 2.3.1

- .github/workflows/integration-test.yml
- .github/workflows/prerequisite-test.yml
- opensearch_dashboards.json
- package.json
Move to OpenSearch 3.0.0
- Resolves #1034
> Move to OpenSearch 3.0.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.6.0.md
Added new Commit to Release Note 
Commit link -  Fix for Tenancy info getting lost on re-login in SAML Authentication flow (https://github.com/opensearch-project/security-dashboards-plugin/pull/1090))
Documentation
Previous  Release Note did not have this change
> Release note 1.3.6

- .github/workflows/cypress-test.yml
Add a cypress workflow to run functional tests for aggregation view feature (#1142) 
New feature
Functional test
> [WIP]2.x cypress test ci

- public/plugin.tsx
- server/auth/types/authentication_type.ts
> [Feature Branch] Add constants and specify types

- server/saved_objects/saved_objects_wrapper.ts
> [Feature Branch] Define variables and functions

- .github/workflows/cypress-test.yml
> [Feature Branch] Change cypress path

- .github/workflows/cypress-test.yml
> [Feature Branch] Change the cypress functional test reference to functional test repo

- public/apps/account/tenant-switch-panel.tsx
- public/apps/configuration/utils/tenant-utils.tsx
- server/auth/types/authentication_type.ts
- server/multitenancy/tenant_resolver.ts
- server/saved_objects/saved_objects_wrapper.ts
> [Feature Branch] Resolve review comments

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.4.0.0.md
Add release notes for 2.4.0.0
* Resolved #1140 
> Add release notes for 2.4.0.0

- .github/workflows/integration-test.yml
Add Firefox driver to integration test workflow to adapt the latest update of Selenium
Enhancement
* Related #1228 
> Add Firefox driver to the integration test workflow

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Version bump to 1.3.7
> Version bump to 1.3.7

- .github/workflows/cypress-test.yml
- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.4.1
> Bump version to 2.4.1

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.4.1.0.md
Adds release notes for 2.4.1.0
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
Maintenance
> Add release notes for 2.4.1.0

- .github/workflows/cypress-test.yml
- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Increment version to 2.6.0
Maintenance
* Relate #1286 
* Relate https://github.com/opensearch-project/security/pull/2389
> Increment version to 2.6.0

- .github/actions/download-plugin/action.yml
- .github/actions/install-dashboards/action.yml
- .github/workflows/integration-test.yml
- .github/workflows/unit-test.yml
Windows CI support for 1.3 branch
Enhancement
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1235
> [Backport 1.3] Windows CI support for 1.3 branch

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.6.0.0.md
Adds release notes for 2.6.0.0
> Add release notes for 2.6.0.0

- DEVELOPER_GUIDE.md
- release-notes/opensearch-security-dashboards-plugin.release-notes-2.6.0.0.md
Updates the developer guide which had many outdated references to 1.x.
Documentation
> Update developer guide

- .github/actions/download-plugin/action.yml
- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Increment version to 1.3.9
Maintenance
> Increment version to 1.3.9

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.9.0.md
Add release notes for 1.3.9
Maintenance
* Relate: https://github.com/opensearch-project/opensearch-build/issues/3195
> Add release notes for 1.3.9

- .github/workflows/cypress-test.yml
- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
Increment version to 2.7.0
Maintenance
> Increment version to 2.7.0

- server/multitenancy/tenant_index.ts
- server/multitenancy/test/tenant_index.test.ts
Backport https://github.com/opensearch-project/security-dashboards-plugin/commit/b69a364ebb70e19dedb4dbf21b1764b47a49f250 from https://github.com/opensearch-project/security-dashboards-plugin/pull/1359
> [Backport opendistro-1.13]Replace legacy template with index template

- build_tools/rename_zip.js
- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.9.0.md
Fixes yarn build on Windows. #1390 
Bug fix.
To successfully build project on Windows.
It was an error building the project on Windows machines. This changes brings successfully run on Windows machines also on Linux.
#1390 
> Fix script for Windows

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.7.0.0.md
Add release notes for 2.7.0
Maintenance
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1392
> Add release notes for 2.7.0

- .github/workflows/cypress-test-tenancy-disabled.yml
- opensearch_dashboards.json
- public/apps/account/account-nav-button.tsx
- public/apps/account/test/account-nav-button.test.tsx
- public/apps/configuration/panels/tenant-list/manage_tab.tsx
- public/apps/configuration/panels/tenant-list/tenant-list.tsx
- public/apps/configuration/panels/tenant-list/test/tenant-list.test.tsx
- public/plugin.ts
- server/multitenancy/tenant_resolver.ts
- test/jest_integration/saml_auth.test.ts
Backport #1419 from main to 2.7
Changing Dashboards version from 2.7.0 to 2.7.1
> Fixing dynamic tenancy changes for issues 1412 (#1419)

- .github/workflows/cypress-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/prerequisite-test.yml
- opensearch_dashboards.json
- package.json
- test/jest_integration/multi_tenancy.test.ts
- test/jest_integration/security_entity_api.test.ts
Manual backport 2.x with password validation related fixes and version bump to 2.8.0
Bug fix & Maintenance
* Relate https://github.com/opensearch-project/security-dashboards-plugin/pull/1432
* Relate https://github.com/opensearch-project/security-dashboards-plugin/pull/1413
> Manual backport 2.x with password validation related fixes and version bump to 2.8.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.8.0.0.md
Add release notes for 2.8.0
Maintenance
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1433
> [Backport 2.8] Add release notes for 2.8.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.8.0.0.md
Update 2.8 release notes for security-dashboards
Maintenance
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1433
> [Backport 2.8] Update 2.8 release notes for security-dashboards

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.8.0.0.md
> Adds 2.8 release notes

- public/apps/configuration/constants.tsx
Backport #1444 and #1426 to 2.x
> [Backport 2.x] Add RESTAPI permissions and ISM control center permissions to dropdown

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.12.0.md
Adds release notes for 1.3.12.0 release.
Documentation
> Add release notes for 1.3.12.0

- babel.config.js
Updates babel imports in response to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5428
Resolves an issue seen here: https://github.com/opensearch-project/security-dashboards-plugin/pull/1649#issuecomment-1810284144
Maintenance
> Update babel imports

- yarn.lock
Re-run `yarn install` to update `yarn.lock`
Maintenance
> [1.3] Re-run yarn install to update yarn.lock

- package.json
- yarn.lock
Resolve debug, glob-parent to resolve https://github.com/advisories/GHSA-gxpj-cx7g-858c, https://github.com/advisories/GHSA-ww39-953v-wcq6
> [2.x] Resolve glob-parent, debug to address CVE-2017-16137, CVE-2020-28469

- package.json
- yarn.lock
Resolve debug, glob-parent to resolve CVE-2017-16137, CVE-2020-28469
> Resolve debug, glob-parent to resolve CVE-2017-16137, CVE-2020-28469

- .github/workflows/integration-test.yml
- opensearch_dashboards.json
- package.json
- test/jest_integration/saml_auth.test.ts
- test/jest_integration/saml_multiauth.test.ts
Incremented version to 2.10.1.0.
> [2.10] Increment version to 2.10.1.0

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.14.0.md
> [1.3] Add 1.3.14 release notes

- .github/workflows/cypress-test-oidc-e2e.yml
Refactors the OpenID cypress tests to use the new Run Cypress Tests action introduced in https://github.com/opensearch-project/security-dashboards-plugin/pull/1729.
Refactoring
> Refactor cypress OIDC tests to use Run Cypress Tests action

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.12.0.0.md
Add release notes for 2.12.0.0 release
Documentation
- https://github.com/opensearch-project/security-dashboards-plugin/issues/1606
> [2.12] Add release notes for 2.12.0.0 release

- public/apps/configuration/panels/get-started.tsx
- public/apps/configuration/panels/tenant-list/configure_tab1.tsx
- public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
- public/apps/configuration/panels/test/get-started.test.tsx
- public/services/shared-link.ts
- public/services/test/shared-link.test.ts
Bring latest changes from main to this feature branch
> Rebasing with main

- package.json
- release-notes/opensearch-security-dashboards-plugin.release-notes-2.13.0.0.md
Add release notes for 2.13 release (https://github.com/opensearch-project/security-dashboards-plugin/issues/1774)
> 2.13 release notes

- .github/CODEOWNERS
Add @derek-ho to CODEOWNERS file
Maintenance
> Add @derek-ho to CODEOWNERS

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.13.0.0.md
Remove date from 2.13 release notes
Documentation
> Remove date from release notes

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.16.0.md
> Adds 1.3.16 release notes

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.17.0.md
> Adds 1.3.17.0 release notes

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.15.0.0.md
Adds release notes for 2.15 release
Maintenance
Fix: #1938 
Fix: #1938 
None
> Add release notes for 2.15

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.16.0.0.md
> Adds 2.16 release notes

- server/auth/types/basic/routes.ts
- server/auth/types/openid/routes.ts
- server/auth/types/proxy/routes.ts
- server/auth/types/saml/routes.ts
- server/utils/next_url.test.ts
- server/utils/next_url.ts
> [Backport 1.3] Update nextUrl validation to incorporate serverBasePath (#2048)

- .github/CODEOWNERS
- MAINTAINERS.md
Moves Chang to emeritus maintainer
Maintenance
> Moves Chang to emeritus

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.19.0.md
Add release notes for 1.3.19 release
> Add release notes for 1.3.19 release

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.17.0.0.md
Adds release notes for 2.17 release
Maintenance
For releasing version 2.17
None
Related to: #2077 
None
> Adds release notes for 2.17

- public/plugin.ts
1. fit and finish change to update category label
> [Look&Feel]update category label

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.18.0.0.md
Adds release notes for 2.18 release
Maintenance
Release version 2.18
None
None
None
> Add release notes for 2.18 release

- release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.20.0.md
Add release notes for 1.3.20 release.
> Add release notes for 1.3.20 release

- release-notes/opensearch-security-dashboards-plugin.release-notes-2.19.0.0.md
Adds release notes for 2.19 release
Maintenance
2.19 release
None
None
None
> Add release notes for 2.19 release

- .github/actions/run-cypress-tests/action.yml
- .github/workflows/cypress-test-multiauth-e2e.yml
- .github/workflows/cypress-test-multidatasources-disabled-e2e.yml
- .github/workflows/cypress-test-multidatasources-enabled-e2e.yml
- .github/workflows/cypress-test-oidc-e2e.yml
- .github/workflows/cypress-test-saml-e2e.yml
- .github/workflows/cypress-test-tenancy-disabled.yml
- .github/workflows/cypress-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/verify-binary-installation.yml
- opensearch_dashboards.json
- package.json
This PR bumps the qualifier on main branch from alpha to beta.
Maintenance
Release beta 1
None
None
None
> Bump main to beta qual

- package.json
- yarn.lock
Bumps babel version to address: CVE-2025-27789
Maintenance
CVE
None
> Bump babel to address: CVE-2025-27789

- package.json
- yarn.lock
> [3.0] Fixes CVE 2024 52798

- release-notes/opensearch-security-dashboards-plugin.release-notes-3.0.0.0.md
Adds release notes for 3.0.0 release
Documentation
> Add release notes for 3.0.0 release

- .github/workflows/link-checker.yml
- .lycheeignore
This workflow is already present across many repos in the OpenSearch project, but its missing from this repo.
This PR adds a PR check to ensure that links in the codebase resolve successfully. 
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
Maintenance
Resolves: https://github.com/opensearch-project/security/issues/5347
> Add workflow using lychee to ensure that links in documentation files resolve

- .github/actions/run-cypress-tests/action.yml
- .github/workflows/cypress-test-multidatasources-enabled-e2e.yml
- .github/workflows/cypress-test-oidc-e2e.yml
- .github/workflows/cypress-test-resource-sharing-enabled-e2e.yml
- .github/workflows/cypress-test-tenancy-disabled.yml
- .github/workflows/cypress-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/verify-binary-installation.yml
- CHANGELOG.md
> Bump @derek-ho/start-opensearch to 9
