lib/multitenancy/migrate_tenants.js

Tenant index migration was failing because KibanaMigrator import statement was commented. Uncommenting that to resolve this issue.

Fix Tenant index migration was failing

---

public/apps/configuration/sections/internalusers/views/edit.html

- Fixed typo in parameter name that caused a UI error that prevented backend roles to added to internal users
- Sanity tested this feature

Fixed Backend Role button

---

lib/auth/types/basicauth/BasicAuth.js
lib/backend/opendistro_security.js
lib/session/sessionPlugin.js

Calls between Kibana and elasticsearch seem to ignore whitelisted headers. This PR is for passing those headers. The same behaviour is kept for a basic auth case.

Pass whitelisted headers from kibana to elasticsearch (non-basic auth)

---

public/apps/configuration/configuration.less

This was the bug that's causing alerting "run" button to be covered up.
Manually tested.

Fix ace_aditor css scope to only apply kibana security plugin

---

index.js
public/services/access_control.js

We need this checkin to allow the logout url to be configurable. This commit was a part of ODFE 0.8,0.9, but is missing from 1.1 and 1.0. There is a separate PR for master.

Add ability to configure logout url for 1.1 and 1.0

---

index.js

We need to allow the logout_url parameter to be read as a part of the auth config from inside kibana.yml ... This change allows for that. This change was part of a cherry-pick that wasn't done correctly. This is specific to master branch, we will need a different pull request for 1.1 and 1.0.

add the ability to configure logout_url for 1.2

---

index.js
lib/multitenancy/migrate_tenants.js

Currently, when we try to migrate from 6.8 to 7.1, we get the following exception when trying to access kibana. 
kibana.log:90:{"type":"error","@timestamp":"2019-09-18T21:16:30Z","tags":["error","migration"],"pid":11656,"level":"error","error":{"message":"[index_template_missing_exception] index_template [kibana_index_template:.kibana] missing","name":"Error","stack":"[index_template_missing_exception] index_template [kibana_index_template:.kibana] missing :: {\"path\":\"/_template/kibana_index_template%3A.kibana\",\"query\":{},\"statusCode\":404,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"index_template_missing_exception\\\",\\\"reason\\\":\\\"index_template [kibana_index_template:.kibana] missing\\\"}],\\\"type\\\":\\\"index_template_missing_exception\\\",\\\"rea …

Fix issue with migration of index templates

---

.babelrc
index.js
lib/auth/types/AuthType.js
lib/auth/types/basicauth/BasicAuth.js
lib/auth/types/jwt/Jwt.js
lib/auth/types/openid/OpenId.js
lib/auth/types/proxycache/ProxyCache.js
lib/auth/types/saml/Saml.js
package.json
public/apps/customerror/customerror.js
tests/AuthType.test.js

- Add whitelisted headers from kibana.yml `elasticsearch.requestHeadersWhitelist` field to requests
Run: `yarn test:jest`

Fix headers whitelist to throw missing role error

---

public/apps/multitenancy/multitenancy.js

Tested changes locally. 
Clicking on "Show Dashboard" button re-directs user to the /dashboards/ page.

Fix: Security Multitenancy "Show Dashboard" button should redirect users to the dashboards page

---

lib/auth/types/AuthType.js
lib/session/sessionPlugin.js
tests/AuthType.test.js
tests/Mocks.js
tests/SessionPlugin.test.js

Issue: Currently all headers (whitelisted and additional headers) are stored in session. Any request that comes in, the headers in session are applied to it causing incorrect headers to be passed with the request. Corresponding code is as follows. 
lib/auth/types/AuthType.js
```
addAdditionalAuthHeaders(request, authHeader, session) {
if (session.additionalAuthHeaders) {
for (let header in session.additionalAuthHeaders) {
authHeader[header] = session.additionalAuthHeaders[header];
}
}
}
```
Fix: Specify what headers need to be stored in session  Eg:`security_impersonate_as`

Specify headers to be stored in session

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.gitignore
build.sh
clean.sh
package.json
plugin.xml
pom.xml

Partially reverting back to using security-parent for packaging zip. 
There is a bug in one of the libraries used in Kibana 7.6.1 causing plugin-helpers build to fail.

Fix build scripts

---

lib/auth/types/AuthType.js
package.json
pom.xml

Support Kibana 7.6.1.
Skip auth for path `'/api/core/capabilities'`

Support Kibana 7.6.1

---

server/index.ts

Exposes login page configurations to browser application. on browser side, the plugin can retrieve the configs in the `setup(core)` lifecycle function like:
```
public setup(core: CoreSetup): OpendistroSecurityPluginSetup {
const config = this.initializerContext.config.get();
const enabled: boolean = config.enabled;
const loginTitle: string = config.ui.login.title;
}
```

Expose login page configurations to browser app

---

public/apps/login/login-app.tsx
public/apps/login/login-page.tsx

*Issue #, if available:* N/A
On successful login, parse `nextUrl` from url parameters and redirect to that. 
This works together with server behavior: when accessing a page without valid auth info, redirect to login page and put source page url to `nextUrl`.

Redirect according to url parameter 'nextUrl' after login

---

public/apps/configuration/app-router.tsx

Fix warning "React does not recognize the `computedMatch` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `computedmatch` instead. If you accidentally passed it from a parent component, remove it from the DOM element."  
It is due to that `Switch` will compare the component that not work for `<div>` so it should not have child `<div>` and `EuiPage` is creating a `<div>`. Moving `EuiPage` outside of `Switch` solves it.

Fix router warning

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/auth-view/auth-view.tsx
public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
public/apps/configuration/panels/auth-view/authorization-panel.tsx

This PR creates the basic layout of Auth list page. There will be follow up implementations for the details.
This is the screenshot of current implementation.
This is the screenshot of mockup for reviewers' reference.

add auth list page layout

---

.gitignore
package.json
server/auth/types/basic/basic_auth.ts
server/auth/types/basic/routes.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/openid/routes.ts
server/backend/opendistro_security_client.ts
server/multitenancy/routes.ts
server/multitenancy/tenant_resolver.ts
server/plugin.ts
server/session/security_cookie.ts

*Description of changes:* Add implementation of OpenID Connect (OIDC) authentication workflow.
* When user is not authenticated, redirect to /auth/openid/login API to initiate the oidc auth *code* workflow
* when oidc Idp redirect back with code, exchange the code with auth tokens
* save tokens in cookie for subsequent requests, then redirect back to kibana app

Implement OIDC auth workflow

---

index.js
public/app.css

Fixes the custom icon scaling issue. Adds formatting for the `figure` element which is how custom plugin icons used to be formatted by adding the css class [here](https://github.com/elastic/eui/blob/master/src/components/list_group/_list_group_item.scss#L109) to the `figure` element. This is no longer included in Kibana 7.7.X.
This fixes the scaling issue by adding this styling back in a separate `app.css` file.

Fix custom icon scaling issue

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/auth-view/auth-view.tsx
public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
public/apps/configuration/panels/auth-view/authorization-panel.tsx
public/apps/configuration/panels/auth-view/expression-modal.tsx
public/apps/configuration/utils/panel-with-header.tsx

Implement AuthC and AuthZ content display.
Since there is no UI to configure the data, I use the APIs to set some test data. See this for references.
https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#update-configuration
https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/configuration/
*Test:*
Run Kibana with the plugin locally. Also I have run lint.
1. Instruction page if there is no authentication configured
Mockup:
2. list view for both authentication and authorization
Mockup:
3. Modal popup to view HTTP configuration details
Mockup:
4. Modal popup to view Backend configuration details
Mockup:
same as 3
By …

implement AuthC/Z configurations view pages

---

.github/workflows/ci.yml

The current behavior is that the workflow will run against OD repository instead of the current repository. After Yuxiang's research, the default value of repository is the current one. Thus we do not need to explicitly set the value. The benefit is that the author will be able to know the workflow result before merging the changes.

use default current repository in ci workflow

---

.github/workflows/ci.yml

Address Yuxiang's offline feedback that developers may use branch names which are not "dev" for development. Thus this change is to increase the robustness of the ci check.
*Test:*
I would watch the CI of this change to suceed

enhance eslint ci to use current branch

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/role-view/role-view.tsx

Implement the layout of the role detail view page
*Test:*
Note that in my implementation, the "Duplicate role" button is put in EuiPageContentHeaderSection which looks a bit different from mockup. We can sync up with UX about this modification during UX review
mockup
actual

Implement role view page layout

---

public/apps/configuration/panels/user-list.tsx

Show `-` for empty attributes list on user listing page.
Screenshots:
Mockup:

Show - for empty attributes list on user listing page

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/types.ts

Implement the status panel.
**_The section "Configure Storage" is still under discussion whether or not support it_**. So, in this iteration, I won't implement it. Also the additional content for enabled view will be implemented later.
**_Also since the backend APIs are not ready, I have todo in the code to switch to actual API calls._**
This is the mockup for enabled.
This is the implementation for enabled.
This is the mockup for disabled.
This is the implementation for disabled.
*Test*
started local server and screenshots shared above.

add the audit logging status panel for enabled or disabled

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx

Add the backend support for audit logging. Previously it just used hardcoded value. Now with this change, it is fetching and parsing backend data. More information from the response will be used to render other components. 
Experienced some issues where the API is showing 404 return. After debugging, the API was added to a wrong place (under commons not configuration).
*Test*
The backend response has audit logging enabled. This is how the UI looks like. We can see that it is showing enabled status.

call auditlogging API to get data

---

public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/utils/audit-logging-view-utils.tsx
public/apps/configuration/utils/display-utils.tsx

This PR will add the read view for general settings and compliance settings.
This is the mockup
This is the implementation.

display general and compliance settings for audit logging

---

public/apps/configuration/panels/internal-user-edit/attribute-panel.tsx
public/apps/configuration/utils/password-edit-panel.tsx

1. Fix typo.
2. Fix a bug that set whole event object (instead of event.target.value) to state on a text change event.
3. Remove the password pattern requirement.
4. Fix a bug that still set invalid when repeating password is already identical to password.
5. Fix a bug that in this case: filling repeating password box first then password box, in this case it shows invalid since the validation is on text change event of repeating password box.

Remove password pattern requirement and bug fixes on user editing page

---

server/auth/types/basic/basic_auth.ts
server/auth/types/basic/routes.ts
server/auth/types/openid/routes.ts
server/auth/types/saml/routes.ts
server/auth/types/saml/saml_auth.ts
server/plugin.ts
server/routes/index.ts
server/session/security_cookie.ts

* Pass logger to route handler via context, refer to https://github.com/elastic/kibana/blob/master/src/core/MIGRATION.md#declare-a-custom-scoped-service
* update error message when failed to call ES API
e.g. when failed to create user, current response looks like:
```
{"statusCode":400,"error":"Bad Request","message":"Bad Request"}
```
updated response includes more informative message from ES:
```
{
"statusCode": 400,
"error": "Bad Request",
"message": "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit, and one special character."
}
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Pass logger to route handler via context, update error message when failed to call ES API

---

public/apps/configuration/panels/internal-user-edit/attribute-panel.tsx
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx
public/apps/configuration/panels/role-list.tsx

* Show an empty row if no data present for user/attributes, role/indexPermission, role/tenant. And remove empty entry before submit.
* Fix a bug that link to user creation instead of role creation on role listing page.
*Screenshots:*
*Before*
*After*

Show an empty row if no data present for user/attributes, role/indexPermission, role/tenant. And remove empty entry before submit.

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/types.tsx
public/apps/configuration/utils/audit-logging-view-utils.tsx
public/apps/configuration/utils/display-utils.tsx
server/backend/opendistro_security_configuration_plugin.ts
server/routes/index.ts

Add the backend interactions when users disable or enable the audit logging. Please note that during disabling, only the status itself is changed instead of wiping out all the configurations. This is the intended behavior.
*Test*
Initially enabled.
Then disabled
Then enabled again

add backend calls to enable or disable audit logging

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/audit-logging/audit-logging-compliance-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging-general-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/constants.tsx
public/apps/configuration/panels/audit-logging/edit-setting-group.tsx

This change implements the edit page for general settings. It creates a EditSettingGroup which can also be used for compliance setting edit page later.
*Test*
mockup
implementation:
initial load
note that "Sensitive headers" is enabled and "Ignored requests" has value "11111"
Next I am going to update "Sensitive headers" to disabled and add another value "22222" to "Ignored requests" and click save

implement edit view for general settings

---

index.js
lib/configuration/backend/opendistro_security_configuration_backend.js
lib/configuration/validation/audit.js
public/apps/audit/app.js
public/apps/audit/components/main/ContentPanel.js
public/apps/audit/components/main/DisplaySettingGroup.js
public/apps/audit/components/main/EditSettingGroup.js
public/apps/audit/components/main/EditorBox.js
public/apps/audit/components/main/config.js
public/apps/audit/components/main/index.js
public/apps/audit/components/main/main.js
public/apps/audit/components/main/utils.js
public/apps/configuration/base_controller.js
public/apps/configuration/configuration.html
public/apps/configuration/configuration_controller.js
public/assets/audit_logs.svg
public/chrome/configuration/enable_configuration.js

- Versions to be supported (all opendistro-1.x & opendistro-0.x)
- Implementation strategy:
- Creating a separate stand alone app page referenced from AngularJS
- Using ReactJS to build the UI page and elements to get the best out of EUI and AngularJS support is deprecated by Elastic
- Reusing the Kibana server API (using Hapi) endpoints for querying the security plugin 
- Based on permissions of signed in user, the audit configuration will be shown to customer. 
- Implementing audit logging UI for security kibana plugin

Audit logging UI changes

---

public/apps/configuration/panels/permission-list.tsx
public/apps/configuration/utils/action-groups-utils.tsx

1. add search option
2. add single permissions 
3. set default sorting by type
Mockup:

Permission listing page - add search option, add single permissions and set default sorting by type

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/constants.tsx

Before this change, the success toast will show on the same edit page. Based on UX feedback, after a successful save, it will redirect to the read view and display the toast with a corresponding success message.
*Test*:
Mockup:
starting page (edit view of compliance setting)
After saving successfully,

[AuditLogging] redirect to read view with toast after save success

---

public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/types.ts
public/apps/configuration/utils/role-mapping-utils.tsx

Implement UI to show the list of mapped users and external identities.
**Screenshots:**
1. When no user mapped to the selected role
_Mockup:_
2. When some users already has been mapped to the selected role
_Mockup:_

Implement role-mapping list page

---

public/apps/configuration/app-router.tsx

…t logging
This change is to add breadcrumbs display for audit logging pages. 
After checking the existing behavior of the code, it will only add breadcrumbs to the top of the right-side page if there is nav panel instead of treating nav panel + the right-side page as a whole.
I tried to follow the current logic for navpanel to add another Route for breadcrumbs. However, there are a few problems:
1) app-route becomes more complicated with branching logic. If only navpanel, it looks fine. But with another component, it starts becoming messy.
2) Within audit logging, there are a few pages whose breadcrumbs title needs to be update. E.g general vs compliance. It seems that the app-route only uses the initial values without dynamically …

add global breadcrumbs for audit log pages

---

index.js
lib/configuration/validation/audit.js
package.json
pom.xml
public/apps/audit/components/main/ContentPanel.js
public/apps/audit/components/main/EditSettingGroup.js
public/apps/audit/components/main/config.js
public/apps/audit/components/main/main.js
public/apps/audit/components/main/utils.js
release-notes/opendistro-for-elasticsearch.security-kibana.release-notes-1.8.1.1.md

- Bump version to v1.8.1.1
- Update disabled categories for Transport layer
- Detail audit logging UI
- Update title to "Audit logs"
- Remove call out messages and provide notes 
- Add line periods
- Remove labels for storage, enable audit log and enable compliance fields
- Fix padding and spacing 
Screenshots:

Bump version to v1.8.1.1, update audit configuration UI

---

index.js
lib/configuration/validation/audit.js
opendistro-elasticsearch-security-kibana-plugin.release-notes
pom.xml
public/apps/audit/components/main/ContentPanel.js
public/apps/audit/components/main/EditSettingGroup.js
public/apps/audit/components/main/config.js
public/apps/audit/components/main/main.js
public/apps/audit/components/main/utils.js

Please check PR #310 for additional details and screenshots. This is a backport PR

Backport audit logging UI changes & version bump to 0.10.1.1

---

public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/utils/action-groups-utils.tsx
public/apps/configuration/utils/internal-user-list-utils.tsx

1. Fix a bug that permission group deletion doesn't work
2. Fix a bug that delete button is enabled when selecting reserved permission
3. Some minor type fix.

Fix a bug that not able to delete permission group

---

lib/auth/types/saml/routes.js

Fix saml acs url for IDPInitiated login
Without this change, the kibana doesnt send /_plugin/kibana  in the acs url to the authinfo API and hence the SAML validation fails as the url sent by kibana and SAML doesnt match. 

Fix saml acs url for IDPInitiated login

---

public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/permission-tree.tsx
public/apps/configuration/utils/action-groups-utils.tsx

On permission listing page, show a expansible permission tree when expanding a row.
Since there is no existing component similar to mockup, using `EuiTree` as an interim solution.
Since the backend doesn't block circular reference, set max depth to 5 to avoid infinite loop.
Mockup:

Show permission tree on permission listing

---

common/index.ts
public/plugin.ts
server/auth/types/authentication_type.ts
server/auth/types/basic/basic_auth.ts
server/auth/types/basic/routes.ts

*Description of changes:* since we are now depending on client side rendering for login page, we need to bootstrap the client app before the browser side routing/rendering can work.
Register `/app/login` as resource and bootstrap an empty page, to prevent login popup when accessing kibana for the fisrt time.

Fix login popup when access login page for the fisrt time

---

server/auth/types/authentication_type.ts
server/auth/types/basic/basic_auth.ts
server/auth/types/jwt/jwt_auth.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/proxy/proxy_auth.ts
server/auth/types/saml/saml_auth.ts

*Description of changes:* in the past, when Kibana receives any unauthenticated request, it returns `302` to redirect user to login page, which doesn't work well for XHR request. the change is to let Kibana to return `302` when the unauthenticated request is to access `/app/xxx` URLs, while for rest URL paths, it returns `401` instead
*test*
request root url `/`
```
% curl -H 'kbn-version: 8.0.0' --include --header "Content-Type: application/json" http://localhost:5601/hgy/
HTTP/1.1 302 Found
location: /hgy/app/login?nextUrl=%2Fhgy%2F
kbn-name: f8ffc2227bb6.ant.amazon.com
vary: origin
cache-control: private, no-cache, no-store, must-revalidate
set-cookie: security_authentication=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; Path=/hgy …
```

update response for unauthenticated APIs

---

public/apps/configuration/constants.tsx
public/plugin.ts

This change adds some permission control about the security configuration pages. During plugin setup, it will check the user's permission information and only register configuration app if the user has "has_api_access" set to true. The reason to use this field to control access is that if the user has API access, then they will be able to configure the security setup by calling APIs either through dev tools or ES directly. Thus use the same logic to control the UX. (This is the same strategy for 6.x and 7.x experiences.)
*Test*:
If this field is false, this is how the UI looks like.
Side bar: note that the security icon is no longer shown.
If the user knows the URL, this is how it looks like if they enter URL directly.
By submitting this …

limit security configuration pages to users with API permission only

---

lib/auth/types/saml/routes.js

*Description of changes:* Redirecting to Missing Role Error Page in case saml auth failed due to missing role
Tested locally with SAML idp.

Showing Missing Role page if SAML auth fails due to missing role

---

public/apps/configuration/app-router.tsx
public/apps/configuration/configuration-app.tsx
public/apps/configuration/constants.tsx
public/apps/configuration/panels/tenant-list/edit-modal.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/types.ts
public/apps/configuration/utils/tenant-utils.tsx
public/apps/types.ts
public/plugin.ts
public/services/chrome_wrapper.ts
public/types.ts
server/index.ts

Implement UI for tenant management. Only admin can access this page.
> Tenant List:
_Mockup:_
> Create/edit/duplicate tenant modal:
_Mockup:_

Add tenant management

---

public/apps/account/account-app.tsx
public/apps/account/account-nav-button.tsx
public/apps/account/role-info-panel.tsx
public/apps/account/utils.tsx

Add account role info modal.
Diff from mockup:
* Confirmed with UX designer that backend role should be shown.
Mockup:

Add account role info modal

---

public/apps/configuration/panels/role-edit/index-permission-panel.tsx

Fix a bug that permission group and anonymization fields don't load on role edit page - index permission panel.

Fix a bug that permission group and anonymization fields don't load

---

public/apps/account/account-nav-button.tsx
public/apps/account/password-reset-panel.tsx
public/apps/configuration/utils/form-row.tsx

Currently the password reset button is just a placeholder. With this change, the modal can show to allow the user to reset their password. We may need to sync up with UX for a better error handling in case the reset fails. For now, we just show the input box as invalid and print the detailed error to the console.
*Test*
Mockup
**Happy case:**
**Current password invalid:**
**New password invalid:**

add password reset function to user profile button

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
public/apps/configuration/panels/auth-view/authorization-panel.tsx
public/apps/configuration/panels/expression-modal.tsx
public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx
public/apps/configuration/panels/role-edit/types.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/role-view/cluster-permission-panel.tsx
public/apps/configuration/panels/role-view/index-permission-panel.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/role-view/tenants-panel.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/types.ts
public/apps/configuration/utils/display-utils.tsx
public/apps/configuration/utils/index-permission-utils.tsx
public/apps/configuration/utils/tenant-utils.tsx

- Added permission tab in Role view page to show cluster, index and tenant permission associated to the selected role.
- Optimize code - moved common code used by multiple pages to single place.
**Screenshots:**
> Cluster permissions:
_Mockup:_
> If role is reserved
> Index permissions:
_Mockup:_
> View Expression:
> Tenants:
_Mockup:_
_Entire page mockup:_
_Entire page implementation:_

Add Permissions tab in role-view

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/user-list.tsx

Updated UI text on Landing page as per the revised copy for security UI from UX team. Also linked learn more links to the existing documentation assuming only content will change in the documentation.
**Updated UI of Get started**

[Landing page] update UI text and make learn more link active

---

lib/multitenancy/headers.js

Issue:
- `/api/status` request call is triggering `_opendistro/_security/authinfo` which is for authenticated users. Though the former request succeeds, the latter request fails.
- `/api/status` is commonly used by monitoring systems and can trigger a lot of failed requests in security backend plugin.
- `/api/status` is added by default to unauthenticated routes https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/index.js#L44 .
Fix:
- Skip auth and continue for unauthenticated routes

Skip unauthenticated routes in multitenancy pre auth

---

public/apps/account/account-app.tsx
public/apps/account/account-nav-button.tsx
public/apps/account/tenant-switch-panel.tsx
public/apps/apps-constants.tsx
public/plugin.ts
public/types.ts

This change adds the function to switch tenant on the user profile button. Note that the mockup only shows the happy case. However, there are different cases we need to handle depending on different combinations of configuration.
*Test*
**Mockup**
**Happy case**
Verified from network call that the right parameters are passed to backend.
**No target tenant is selected.**
**Multi tenancy is disabled**
**Global and private disabled by config**
**Global and private have no access**

implement switching tenant function on user profile button

---

.gitignore
package.json
test/constant.ts
test/es/elasticsearch_helper.ts
test/es/setup_es.js
test/helper/sleep.ts
test/jest.config.integration.js
test/jest_integ_test.js
test/jest_integration/integration.test.ts

*Description of changes:* add integ test command and one test suite
```
% yarn test:jest_integ
yarn run v1.22.0
$ node ./test/jest_integ_test.js
console.log
Using esRootDir: /Users/zengyan/kibana-security-workspace/kibana/plugins/opendistro_security/.es/elasticsearch-7.8.0
at startElasticsearch (plugins/opendistro_security/test/es/elasticsearch_helper.ts:53:13)
console.log
Starting Elasticsearch...
at startElasticsearch (plugins/opendistro_security/test/es/elasticsearch_helper.ts:56:11)
console.log
Elasticsearch pid: 99403
at startElasticsearch (plugins/opendistro_security/test/es/elasticsearch_helper.ts:59:11)
console.log
Waiting for Elasticsearch to start
at startElasticsearch (plugins/opendistro_security/test/es/elasticsearch_helper.ts:64:11)
console.log …
```

Integ test

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/utils/delete-confirm-modal-utils.tsx

… add delete confirm modal
- Before this change, the success toast was showing on the same edit page. This change will redirect to the read view of role mapping after a successful save and display the toast with a corresponding success message.
- Also added Delete confirm modal.
_Testing:_
> Show Success toast
> Delete Confirm Modal

[RoleMapping] redirect to read view with toast after save success

---

public/apps/configuration/panels/audit-logging/constants.tsx
public/apps/configuration/panels/audit-logging/edit-setting-group.tsx

This change is to address latest UX changes. Specifically, this will remove the callout instruction from edit page.
*Test*:
**Current Mockup**
**new implementation**
**Old implementation**

[AuditLogging] remove callout from edit instructions

---

public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
public/apps/configuration/panels/auth-view/authorization-panel.tsx
public/apps/configuration/panels/expression-modal.tsx
public/apps/configuration/panels/role-view/index-permission-panel.tsx
public/apps/configuration/utils/display-utils.tsx

Stringify input to the expression modal to fix the broken display in current authc & authz page.
*Test*
Current error
After the fix
Also verify that the fix didn't impact the role view page.

stringify http expression before passing to expression render

---

public/apps/configuration/panels/get-started.tsx

Address comments from UX team on Get started page. 
- Outline button with blue border
- Modified the space between steps so that title, description and actions appears as same visual group.
_Please note: I can not modify the space between step title and step content. In order to do that I need to override euistep_content style. To be consistent with other existing steps, I have added extra space between two steps._
**Get started with these modification:**

UI fixes for Get started

---

public/plugin.ts

During testing, 500 errors from backend may lead the APP to an error status. Thus make the call default to false by assuming that user has no API permission (admin).

default to API permission call to false

---

public/apps/account/password-reset-panel.tsx
public/apps/apps-constants.tsx
public/apps/configuration/utils/password-edit-panel.tsx

Modify password instruction message per UX feedback. Use "should" instead of "must" since this is not enforced in ODFE.
*Test*

modify password instruction message

---

public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/user-list.tsx
public/apps/configuration/utils/delete-confirm-modal-utils.tsx

1. Update the delete confirmation message to 'Do you really want to delete selected {entity(s)}?' from 'Do you really want to delete selected {count} {entity}?'
2. Remove the returning `closeDeleteConfirmModal` function
3. Add delete confirmation modal to deletion on both role listing and internal user listing page.
|Before|After|
|--|--|
|N/A|![image](https://user-images.githubusercontent.com/63078162/90944354-0cc40900-e3d3-11ea-9cec-cae287bf0540.png)|
|N/A|![image](https://user-images.githubusercontent.com/63078162/90944343-fb7afc80-e3d2-11ea-8510-6adfe63a3905.png)|
|N/A|![image](https://user-images.githubusercontent.com/63078162/91095163-be03b280-e610-11ea-812b-865602ec2d9e.png)| …

Improve delete modal and apply to all listing pages

---

public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx

- Made the page description 75% width of the container. 
- Added hint text to cluster permission combobox.
- Open the first accordion of index permission by default so that user can scan what expected to be filled.
- modified hint text of tenant permission to 'Search tenant name or add a tenant pattern'

UI fixes for create role page

---

public/apps/configuration/app-router.tsx
public/apps/configuration/cross-page-toast.tsx
public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/constants.tsx
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/utils/storage-utils.tsx

* Refactor cross page toast. The current method for audit logging and role mapping is appending some additional constant to the url. In this way, on a success toast page, if user refreshes, or user nav to another page and use backward button to go back, the toast shows again. This PR migrate to a session storage so 1) the toast only shows once; 2) lift the cross page up to show at app router level to avoid the rendering on each page component.
* Add success toast for role/user update. 
Screenshot:
Role mapping and audit logging: manually verified and found no change.

Add success toast for role/user update. Refactor cross page toast.

---

public/apps/configuration/utils/display-utils.tsx

Make customization column icon vertically align and add spacing between icon and text.
**Screenshots:**
> Role-list:
> Permissions:
> Tenants:

ui fix for customization column icon

---

public/apps/configuration/panels/role-view/index-permission-panel.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/tenant-list/edit-modal.tsx
public/apps/configuration/panels/user-list.tsx
public/apps/configuration/ui-constants.tsx
public/apps/configuration/utils/display-utils.tsx

- change all dashes/hyphens into em-dash
- Make map user buttons center aligned and update subtext
- stretch text fields in tenant edit modal to full width

UI fixes in all listing, map user page and tenant edit modal

---

public/apps/configuration/panels/permission-tree.tsx
public/apps/configuration/panels/permission-tree/_index.scss
public/apps/configuration/panels/permission-tree/index.ts
public/apps/configuration/panels/permission-tree/permission-tree.tsx

1. Use smaller dot on permission tree.
2. Limit max-height to 200px and add scroll bar.
Screenshot:
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/63078162/91475918-204af600-e851-11ea-80c9-e4024512210d.png)|![image](https://user-images.githubusercontent.com/63078162/91474823-99e1e480-e84f-11ea-89a5-1032dab56813.png)|

Improve layout on permission tree

---

public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx

Fix a bug that not redirecting to map user page after mapping saved.

Fix a bug that not redirecting to map user page after mapping saved

---

public/apps/configuration/panels/auth-view/_index.scss
public/apps/configuration/panels/auth-view/auth-view.tsx

Fix the style for instruction text.
*Test*
The new look when browser window is small.
The new look when browser window is max.

adjust sytle for instruction text in authentication view

---

public/apps/configuration/utils/form-row.tsx

Update form row title to primary (black) from subdued (grey)
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/63078162/91483717-fe577080-e85c-11ea-8f85-1fe9a2b26aa1.png)|![image](https://user-images.githubusercontent.com/63078162/91483663-e384fc00-e85c-11ea-9672-94a262378042.png)|

Fix a UI bug that form row label is grey

---

public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-mapping/RoleEditMappedUser.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx

Add object name (e.g. role name, user name etc.) to success toast.
**Some Screenshots:**

Add object name (e.g. role name, user name etc.) to success toast

---

public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/constants.tsx

This is to address a UX feedback to add a whitespace between two words.
Also address two comments from a previous PR
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/426
*Test*
whitespace fix
Before
after
Verified the max width and horizontal margin are still working.

[AuditLogging] remove extra whitespace and follow up code improvement

---

kibana.json
public/apps/account/tenant-switch-panel.tsx
public/apps/configuration/panels/audit-logging/edit-setting-group.tsx
public/apps/configuration/panels/audit-logging/view-setting-group.tsx
public/apps/configuration/panels/auth-view/auth-view.tsx
public/apps/configuration/utils/array-state-utils.tsx
public/apps/configuration/utils/combo-box-utils.tsx

*Description of changes:* switch to track Kibana v7.9.0
Notes:
* tested locally by running kibana dev server. it works ok.
* for browser app which is not compatible, I tried to fix it, e.g. replace lodash `StringRepresentable` with `PropertyName`, and add `@ts-ignore` to those syntax problems, please fix them after this PR is merged in.
* Please make sure to use Kibana tag `v7.9.0` when switching your dev env, the 7.9 branch is not tracking latest 7.9 release

Port to v7.9.0

---

public/apps/configuration/utils/tenant-utils.test.tsx
public/apps/configuration/utils/tenant-utils.tsx

- Add unit test for tenant utils
*UT result:*
```
% yarn test:jest public/apps/configuration/utils/tenant-utils.test.tsx
$ NODE_PATH=../../node_modules ../../node_modules/.bin/jest --config ./test/jest.config.js public/apps/configuration/utils/tenant-utils.test.tsx
PASS  public/apps/configuration/utils/tenant-utils.test.tsx
Tenant list utils
transform to listing data
✓ transform global tenant (3ms)
✓ transform private tenant (1ms)
✓ transform global and custom tenant (1ms)
✓ transform global, private and custom tenant (1ms)
Resolve tenant name
✓ resolve to global tenant when tenant name is empty
✓ resolve to global tenant when tenant name is undefined
✓ resolve to private tenant when tenant name is user name
✓ resolve to …
```

Add unit test for tenant utils

---

public/apps/configuration/panels/role-list.test.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/utils/role-list-utils.tsx
test/setupTests.ts

Add unit test for role list component.
*Coverage:* (the failure are integration test that should be excluded)
**Before**:
% yarn test:jest --coverage
$ NODE_PATH=../../node_modules ../../node_modules/.bin/jest --config ./test/jest.config.js --coverage
PASS  server/auth/auth_handler_factory.test.ts (7.199s)
PASS  public/apps/configuration/utils/tenant-utils.test.tsx (7.224s)
PASS  public/apps/configuration/utils/role-list-utils.test.tsx (7.279s)
FAIL  test/jest_integration/multi_tenancy.test.ts
-----------------------------------------------------|---------|----------|---------|---------|------------------- …

Add unit test for role list component

---

server/backend/opendistro_security_client.ts

*Description of changes:* the old version Security plugin somehow allows auth token call from kibanaserver user, while the new version doesn't. Using scoped client to fix this

Fix SAML authtoken call

---

public/apps/account/tenant-switch-panel.tsx

This is to address one UX feedback on tenant switch. Originally we tested the case that user clicks the radio icon first and then select. However, user can also go directly to the dropdown to select. So, this fix is to select the radio ID if the dropdown is changed.
*Test*
With the change, the workflow looks like this.

set radio ID when custom tenant is selected

---

public/apps/account/account-nav-button.tsx
public/apps/account/log-out-button.tsx
public/types.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/openid/routes.ts
server/index.ts

*Description of changes:* Fix OIDC logout.
* The OIDC logout used to be a XHR `POST` request. It will redirect user to IDP logout endpoint, which will be blocked by browser CORS policy. change it to `GET`
* refactor logout parameters, do URL encoding

Fix OIDC logout

---

public/plugin.ts
public/types.ts
server/index.ts

Add readonly mode that can only see dashboards (configured by `readonly_modes.roles`, default to "kibana_read_only").
Known defects:
This PR didn't disable home app, on home app there are a number of links (e.g. dashboards, visualizations), click thru them will see an "Application not found error". But we didn't find a way to change default app to dashboards, means if we disable home app, after login user will be redirect to home app and see "Application not found error".
Screenshots:

Add readonly mode

---

__mocks__/fileMock.js
__mocks__/styleMock.js
public/apps/configuration/panels/role-edit/cluster-permission-panel.test.tsx
public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.test.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/role-edit.test.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-edit/tenant-panel.test.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx
test/jest.config.js

Add unit test for role edit - tenant panel.
Coverage:
**Before**
% yarn test:jest --coverage
$ NODE_PATH=../../node_modules ../../node_modules/.bin/jest --config ./test/jest.config.js --coverage
-----------------------------------------------------|---------|----------|---------|---------|------------------------
All files                                            |    6.25 |     7.77 |    5.19 |    6.04 |
public/apps/configuration/panels/role-edit          |       0 |        0 |       0 |       0 |
tenant-panel.tsx                                   |       0 |        0 |       0 |       0 | 39-147
Test …

Add unit test for role edit

---

public/apps/configuration/panels/permission-list/edit-modal.test.tsx
public/apps/configuration/panels/permission-list/edit-modal.tsx
public/apps/configuration/panels/permission-list/permission-list.test.tsx
public/apps/configuration/panels/permission-list/permission-list.tsx

Add unit test for permission listing page.
Coverage:
Folder-level:
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------|---------|----------|---------|---------|-----------------------------------
All files            |   80.82 |    66.67 |      60 |   81.94 |
edit-modal.tsx      |   66.67 |       25 |   66.67 |   66.67 | 56-59
permission-list.tsx |   82.81 |       75 |   59.09 |   84.13 | 75,93,220,234-256,274-275,303,313
All: 
Before:
-----------------------------------------------------|---------|----------|---------|---------|-------------------------------------------- …

Add unit test for permission listing page

---

public/apps/account/password-reset-panel.tsx

Address UX feedback to move password reset error to callout. Changed the message to be more generic since the actual error is from backend.
*Test*

move password reset error to callout

---

public/apps/configuration/panels/permission-tree/_index.scss
public/apps/configuration/panels/permission-tree/permission-tree.tsx

Remove hover state for permission tree leaf node by adding a cssClass for leaf node to override it.
Screenshots (not able to include the cursor)
Before:
After:

Remove hover state for permission tree leaf node

---

package.json
server/multitenancy/routes.ts
server/routes/index.ts

limit entity name allowed characters to numbers, letters, hyphen and underscore
test:
when creating internal user `a.b.c`
```
% curl -H "Content-Type: application/json" -H 'kbn-xsrf: true' -XPOST --include localhost:5601/nfh/api/v1/configuration/internalusers/a.b.c --cookie 'security_authentication=Fe26.2**d5ca53bbe4d1b6b6f67aadccd5754edc32003f069f16e88831add7e3ca88fb1c*99gIgfLsVDdzUs8cFpskZQ*9Ppr6Zy0JXSFz8z9_z0cGWwBRLXetInGl92Lbhc5mcNIGnccBCZ11KEbejDOrF9bmMWAgLg_VTnJQ2fpSV0uXXo62rp6LACUIcO2D6xuUshHhaD-5Sb6IwuynygzWBpsNbsQA_VLYq1UhIEzn2KQ9bvxCs5hJRHLZ5Vio3bzYj4DldBH-GLrSrSCqFAElvVBWbVb92TZyAdcGIzexvW22ksAbReZjHH3aJCAW-LLJhw**58a4f4b56956e60c9560c3f3b73b2e00feb1c39efcb165707cb09dbc5a1f6d61*a65_bMg-rjNWVCbKjZm5jExFLKtOwt2ImbfCxBbIAzc' -d'{ …
```

Validate entity id at server side

---

public/apps/account/tenant-selection-page.tsx

Fix a security issue that nextUrl could be an external website. If detected the lowercase nextUrl starts with http, redirect to root. It is for the case that a user put an external phishing website in the nextUrl para and send the link to another user.
Following cases are verified to be handled after this change:
http://localhost:5601/gyq/app/login?nextUrl=http://opendistro.github.io
http://localhost:5601/gyq/app/login?nextUrl=HTTP://opendistro.github.io
http://localhost:5601/gyq/app/login?nextUrl=//opendistro.github.io
http://localhost:5601/gyq/app/login?nextUrl=%2F%2Fopendistro.github.io
Following cases are redirecting to invalid url so no need to be handled:
http://localhost:5601/gyq/app/login?nextUrl=/opendistro.github.io -> …

Fix a security issue that nextUrl could be an external website

---

public/apps/configuration/utils/role-mapping-utils.test.tsx

- Add unit test for role mapping util
*UT result:*
```
% yarn test:jest public/apps/configuration/utils/role-mapping-utils.test.tsx --coverage --collectCoverageFrom=public/apps/configuration/utils/role-mapping-utils.tsx
$ NODE_PATH=../../node_modules ../../node_modules/.bin/jest --config ./test/jest.config.js public/apps/configuration/utils/role-mapping-utils.test.tsx --coverage --collectCoverageFrom=public/apps/configuration/utils/role-mapping-utils.tsx
PASS  public/apps/configuration/utils/role-mapping-utils.test.tsx (7.152s)
Role mapping utils
transform role-mapping data
✓ neither external identities nor internal users mapped to role (5ms)
✓ only external identities mapped to role (1ms)
✓ only internal users mapped to …
```

 add unit test for role-mapping util

---

public/apps/account/password-reset-panel.tsx
public/apps/account/tenant-switch-panel.tsx
public/apps/error-utils.ts

This change introduces a util function to construct error message and also applied it to two functions.
*Test*
Tenant switch:
Password reset:

refactor error message for tenant switch and password reset panel

---

public/apps/configuration/panels/tenant-list/edit-modal.test.tsx
public/apps/configuration/panels/tenant-list/edit-modal.tsx
public/apps/configuration/panels/tenant-list/tenant-list.test.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/utils/delete-confirm-modal-utils.test.tsx

Add unit test for tenant list page
Coverage:
Folder-level:
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------|---------|----------|---------|---------|-----------------------------------
All files            |   63.16 |    66.67 |      33.33 |   64.52 |
edit-modal.tsx |   77.78 |       50 |      50 |   77.78 | 53,57  
tenant-list.tsx |   61.63 |       70 |   30.77 |    63.1 | 115-119,123,127-139,144-149,159-164,178-211,229-267,294  
All: 
Before:
-----------------------------------------------------|---------|----------|---------|---------|------------------------------------ …

Add unit test for tenant list page

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/permission-list/edit-modal.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/tenant-list/edit-modal.tsx
public/apps/configuration/types.ts
public/apps/configuration/utils/form-row.tsx
public/apps/configuration/utils/name-row.tsx
public/apps/configuration/utils/resource-validation-util.tsx

Validate resource name (role name, user name, tenant name, permission group name/ single permission name)
*Validation Criteria:*
- The resource name must contain from 2 to 50 characters.
- Valid characters are A-Z, a-z, 0-9, (_)underscore, (-) hyphen and unicode characters.
*Testing:*
> Role name
> User name
> Tenant name
> Permission

Validate resource name

---

public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/user-list.tsx

Show count of filtered table rows on headers.
TODO: refactor to have a shared component for all tables with search bar. Didn't do it in this PR due to high risk on a tight release schedule.
Screenshots:

Show count of filtered table rows on headers

---

public/apps/account/tenant-switch-panel.tsx

Originally we thought that tenant with false attribute is disabled tenant. However, it actually means read only tenant.
Thus this PR removes the false check and allows users to switch to a read only tenant.
*Test*:
We created a user whose role has read only access to a tenant.
This is how the tenant switch panel looks like before the change. Notice that custom radio is disabled.
After the PR,

include read only tenants in tenant switch

---

build_tools/build_plugin.js
kibana.json
package.json
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/user-list.tsx
public/apps/error-utils.ts
server/auth/types/basic/routes.ts
tsconfig.json

*Description of changes:* Update build script.
```
% node build_tools/build_plugin.js 
Building plugin...
CWD: /Users/zengyan/kibana-security-workspace/kibana/plugins/opendistro_security
Cleaning up target directory...
Transpiling typescript soruces...
yarn run v1.22.0
$ /Users/zengyan/kibana-security-workspace/kibana/plugins/opendistro_security/node_modules/.bin/tsc
Done in 21.24s.
Exectuing optimizer...
info Start running JS optimization for plugin at /Users/zengyan/kibana-security-workspace/kibana/plugins/opendistro_security
debg [opendistroSecurity] bundle not cached because [cache disabled]
info initialized, 0 bundles cached
info starting worker [1 bundle]
debg modules [NaN] work units [NaN]
debg [opendistroSecurity] state = "running"
debg …
```

Fix build script

---

public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
public/apps/configuration/panels/auth-view/authorization-panel.tsx

Show count of filtered table rows on authentication and authorization headers.
Screenshots:

Show count of filtered table rows on authc and authz headers

---

server/routes/index.ts

Currently when non admin user calls `restapiinfo` API, the error handling function will fail and log an error log in kibana.log, this change fixed this issue and the response looks like following now
```
{"statusCode":400,"error":"Bad Request","message":"java.lang.UnsupportedOperationException"}
```

Fix error log when non admin user calls restapiinfo API

---

public/apps/configuration/panels/audit-logging/constants.tsx

Add one more option to bring parity with existing audit logging features.
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/opendistro-1.9/lib/configuration/validation/audit.js#L23
*Test*

[AuditLogging] add one more option for disabled_transport_categories

---

lib/configuration/validation/audit.js
public/apps/configuration/base_controller.js
public/apps/configuration/sections/actiongroups/controller.js
public/apps/configuration/sections/internalusers/controller.js
public/apps/configuration/sections/roles/controller.js
public/apps/configuration/sections/rolesmapping/controller.js

- Removed validation of disabled audit categories. This validation will be done on server side based on configuration
- Removed resource name validation check for rolesmapping, roles, internal users and action groups as this limitation is not there in opendistro security backend API and customers can directly make resources with specified resource names (which fail client side validation).
-  URL encode resources to account for non-alphanumeric characters. Double encoding for URL (from https://github.com/angular/angular.js/issues/10479) 
- Creating resources with non-alphanumeric characters such as `%3chtml%3e%3cscript%3etest123%3c%2fscript%3e%3c%2fhtml%3e` does not allow the resource to be accessed via URL and cannot be deleted due to …

Remove client side validation for security resources

---

.github/workflows/cd.yml
.github/workflows/ci.yml
package.json
public/apps/configuration/utils/tenant-utils.tsx
server/auth/types/openid/routes.ts

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/416
*Description of changes:* current Kibana API by default requires to explicitly list all query/url/body parameters, and undeclared parameters will result in request rejected. This change allows session_state and other parameters for OIDC login API to support IDPs that support session management.

Allow arbitrary query parameters for OIDC

---

server/multitenancy/tenant_resolver.ts

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/505
*Description of changes:* the new Kibana platform exposes two `query` fields in `KibanaRequest` while only the `request.url.query` includes the query parameters. Fix this issue to solve tenant parameter not used in url issue.

Fix tenant parameter not appused in url

---

public/apps/configuration/utils/role-list-utils.tsx
server/auth/types/authentication_type.ts

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/503
*Description of changes:*  currently requests to `/bundles` are marked as auth not handled. it can still serve the static files, but dark mode flag in kibana requires request to be authenticated to adopt dark mode, see related kibana code https://github.com/elastic/kibana/blob/82a6d39ba22d9f2abae2b4e3079fdd9869a12e71/src/legacy/ui/ui_render/ui_render_mixin.js#L84-L87

Mark requests to /bundles default authenticated

---

server/auth/types/authentication_type.ts
server/multitenancy/tenant_resolver.ts

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/503
the PR https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/512 will cause login pop up. because `bootstrap.js` is configured using `try` auth. when requesting `bootstrap.js` it will make [a call to get uiSettings](https://github.com/elastic/kibana/blob/019e2ad9a55246f3740eb02deb9f7defe21af62e/src/legacy/ui/ui_render/ui_render_mixin.js#L84-L87) if authenticated, which is essentially a SavedObject call. 
This saved object call requires to be authenticated. So when on log in page, the user is not authenticated, and the saved object call will result in login pop up if auth challenge is configured on ES side.
This fix will still allow …

Fix login pop up when requesting bootstrap.js

---

public/apps/configuration/panels/role-view/index-permission-panel.tsx

DLS can contain $expression which will fail the json parse. Display as it is instead of failing the page.
*Test*:
Before the change, the view role page will be broken with this error
With this change, this is a working page.

add fault tolerance to DLS rendering

---

public/services/chrome_wrapper.js

*Issue #, if available:* #245
When a user switches tenants via the Kibana GUI Plugin, it resets the URL for several of the links (to include discover, dashboards, and visualizations) in the left-hand navigation bar.
Unfortunately, if server.basePath is set in the Kibana config (commonly done when the server is being a reverse proxy), the resulting URL is malformed. For example, it will reset http://staging/my_kibana_server/app/kibana#/discover to http://staging/app/kibana#/discover.
Since nginx doesn't know where to route /app/, this results in a HTTP404.
This PR simply prepends the basePath so that the result is navigable.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Respect server.basePath when re-writing nav bar links.

---

public/apps/configuration/configuration-app.tsx
public/apps/configuration/constants.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/translation-utils.ts

To allow customization of messages and doc links, this PR leverages i18n pgk provided by Kibana.
*Test*
The en.json in Kibana is configured in this way.
`    
"audit.logs.introduction": "Audit logs let you track user access to your Elasticsearch cluster and are useful for compliance purposes. If you enable this feature, Amazon Elasticsearch Service publishes the audit logs to CloudWatch Logs, where you can monitor and search them.",`
`
"audit.logs.storageInstruction": "Amazon Elasticsearch Service publishes audit logs to CloudWatch Logs, where you can monitor and search them. Set up the CloudWatch Logs log group in the Logs section of the Amazon Elasticsearch Service console for this domain.",`
`
"audit.logs.docLink": …

[AuditLogging] use i18n to allow customization of messages and doc links

---

lib/backend/errors/wrap_elasticsearch_error.js

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/283
*Description of changes:* return 401 instead of 500 when credentials in cookie is invalid.
*testing*
by following the steps described in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/283 , the current implementation returns following response when credentials in cookie is invalid:
```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```
after the change, it returns:
```
{"message":"Authentication Exception: Authentication Exception","statusCode":401,"error":"Unauthorized"}
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

return 401 instead of 500 when credentials in cookie is invalid.

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/audit-logging/constants.tsx
public/plugin.ts
public/types.ts
server/index.ts

use Kibana yml for optional configurations. This allows more flexibility for customization.
This is how the new parameters look like in the yml.
`opendistro_security.clusterPermissions.include: ["cluster:admin/ultrawarm/migration/list"]
`
`opendistro_security.indexPermissions.include: ["indices:admin/ultrawarm/migration/get", "indices:admin/ultrawarm/migration/hot", "indices:admin/ultrawarm/migration/warm"]
`
`opendistro_security.disabledTransportCategories.exclude: ["BAD_HEADERS", "SSL_EXCEPTION"]
`
`opendistro_security.disabledRestCategories.exclude: ["BAD_HEADERS", "SSL_EXCEPTION"]
`
*Test*:
Without the configuration above, this is how the UI looks like
With the configuration above, this is how the UI looks like
By submitting this pull …

use Kibana yml for optional configurations

---

public/apps/configuration/panels/tenant-list/tenant-instruction-view.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx

*Issue #, if available:* 521
Currently if multitenancy is disabled, the page still tries to display the same layout as if it was enabled. Thus there is an error shown in the table view which is confusing for customers. Thus this PR would display an instruction view. (The layout of the instruction view refers to that for authentication and authorization view.)
V2
The new screenshot is:
V1
*Test*
before:
after:
As a reference, this is how authentication and authorization view shows instructions.

add instruction view for tenant list when multitenancy is disabled

---

public/apps/account/account-nav-button.tsx

When isInternalUser is false, there is an extra horizontal rule because logout button has a build in horizontal rule.
*Test*
before
after

fix the extra horizontal rule on profile button for non internal user

---

public/apps/account/__snapshots__/account-nav-button.test.tsx.snap
public/apps/account/account-nav-button.tsx
public/apps/account/log-out-button.test.tsx
public/apps/account/log-out-button.tsx
public/apps/account/password-reset-panel.tsx
public/apps/account/utils.tsx
public/types.ts

Some IDP needs additional clear up step, which redirect to custom logout page. This change is to respect `opendistro_security.auth.logout_url` as it used to be.
Test:
* yarn tsc 
* yarn test:jest_ui public/apps/account

Respect opendistro_security.auth.logout_url after logout

---

public/services/chrome_wrapper.js

- While selecting multi-tenant we are incorrectly replacing the urls of the apps kibana:visualize kibana:dashboard kibana:discover timelion
- `subUrlBase` does not have the Kibana base path prefixed. If base path is configured, accessing the above app url complains it cannot find them because 
`/app/kibana#/discover` is used instead of `_plugin/kibana/app/kibana#/discover` if `_plugin/kibana` is the base path. 

Fix nav link replace url to use baseUrl

---

public/apps/configuration/panels/role-mapping/role-edit-mapped-user.tsx
public/apps/configuration/panels/role-mapping/users-panel.tsx
public/apps/configuration/panels/role-view/role-view.tsx

We had a PR to allow external users https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/541
More text descriptions need to be update which is the focus of this PR. 
I will add tech writer to the PR for reviewing the text change and notifying for the doc change.
*Test*
|Before|After|
|--|--|
|<img width="1429" alt="Screen Shot 2020-10-21 at 4 03 39 PM" src="https://user-images.githubusercontent.com/60111637/96800759-ef9fbc80-13ba-11eb-8eb1-433dd6819f45.png">|<img width="1413" alt="Screen Shot 2020-10-21 at 4 16 21 PM" src="https://user-images.githubusercontent.com/60111637/96800521-612b3b00-13ba-11eb-89a8-c4cc7913b132.png">|
|<img width="1411" alt="Screen Shot 2020-10-21 at 4 02 31 PM" …

generalize user descriptions related to role mapping for external users

---

server/auth/types/authentication_type.ts
server/auth/types/basic/basic_auth.ts
server/auth/types/jwt/jwt_auth.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/proxy/proxy_auth.ts
server/auth/types/saml/saml_auth.ts

The existing implementation will ignore browser cookie when auth headers are provided in the request, but this will ignore the tenant selection when customer has a proxy to inject auth header but still auth types like basic auth.
With this change, Kibana will alway try to extract the tenant from cookie when auth header is provided in the request.

always try to fetch security tenant from cookie

---

public/apps/configuration/panels/auth-view/authentication-sequence-panel.tsx
public/apps/configuration/panels/auth-view/authorization-panel.tsx
public/apps/configuration/panels/permission-list/permission-list.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/user-list.tsx

- Added `OR` condition in multi select.
- Issue Fix: If user enters invalid search text (e.g. `(cluster`, `cluster)`, `[cluster`, `cluster]`, etc.) in the search bar, it was causing whole page to disappear. Fix the issue.
Steps to reproduce the issue:
1. Type `name: (tenant2` in the search bar and press enter.
2. Result: Tenant page disappeared. 
After fixing issue:
If user enters invalid search text in search bar, it will return full list and highlight the search bar with red underline.

Fix invalid search

---

public/apps/login/__snapshots__/login-page.test.tsx.snap
public/apps/login/login-page.test.tsx
public/apps/login/login-page.tsx
public/utils/login-utils.tsx

- Add unit test for login page
```
opendistro_security % yarn test:jest_ui public/apps/login** -u           
$ node ./test/run_jest_tests.js --config ./test/jest.config.ui.js public/apps/login -u
PASS  public/apps/login/login-page.test.tsx
Login page
renders
✓ renders with config value (11ms)
✓ renders with default value (1ms)
event trigger testing
✓ should update user name field on change event (4ms)
✓ should update password field on change event (2ms)
handle submit event
✓ submit click event (2ms)
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   2 passed, 2 total
Time:        4.02s
Ran all test suites matching /public\/apps\/login/i.
✨  Done in 8.61s.
```
Before:
File …

Add unit test for login page

---

public/apps/configuration/panels/audit-logging/test/audit-logging.test.tsx

Fix the syntax.
Now the result is 
a483e79af39a:opendistro_security tianleh$ yarn test:jest_ui public/apps/configuration/panels/audit-logging
yarn run v1.22.5
$ node ./test/run_jest_tests.js --config ./test/jest.config.ui.js public/apps/configuration/panels/audit-logging
PASS  public/apps/configuration/panels/audit-logging/test/audit-logging.test.tsx
PASS  public/apps/configuration/panels/audit-logging/test/audit-logging-edit-settings.test.tsx
PASS  public/apps/configuration/panels/audit-logging/test/view-setting-group.test.tsx
PASS  public/apps/configuration/panels/audit-logging/test/edit-setting-group.test.tsx
PASS  public/apps/configuration/panels/audit-logging/test/code-editor.test.tsx
Test Suites: 5 passed, 5 total
Tests:       9 …

fix failed audit logging unit test

---

server/auth/types/basic/routes.ts
server/auth/types/openid/routes.ts
server/auth/types/saml/routes.ts

*Description of changes:* when extending session ttl, we should use session.ttl config instead of cookie ttl, this change fixed this issue.

extend session using session ttl config instead of cookie ttl

---

server/index.ts
server/session/security_cookie.ts

*Description of changes:* Fix `FATAL  Error: "SameSite: None" requires Secure connection` due to cookie sameSite config.
When cookie sameSite is set to `None` explicitly, Kibana will fail to start when secure cookie is off. https://github.com/elastic/kibana/blob/master/src/core/server/http/cookie_session_storage.ts#L112 
This change default to not set the sameSite setting, which will let the browser to determine which option to use. This is also the same behavior as the legacy plugin

Fix default cookie sameSite config

---

common/index.test.ts
common/index.ts
package.json
public/apps/configuration/utils/resource-validation-util.tsx
server/routes/index.ts
test/jest.config.ui.js

User can create some resource name like "a/../../roles/roleName" to inject url manipulation. Previously leading punctuation (including dot) is but it is not complete. It can starts with other chars and then dot (like "a/../../roles/roleName"), and also starts with "/" or "%2F".
This PR does:
1. Replace punctuation script `\p{P}` with some subsets (`\p{Pc}\p{Pd}\p{Ps}\p{Pe}`). Basically it includes `-_()`, see also [link](https://javascript.info/regexp-unicode) for more details.
2. Remove XRegExp as unicode is supported natively since node 8 (kibana 7.9 is using node 10). See [node website](https://node.green/) and search for `"u" flag`.
3. Add unit test to cover unknown cases.
Test:
`yarn test:jest_ui common/index.test.ts` passed.
By …

Fix a url injection issue caused by resource name

---

package.json
server/utils/next_url.test.ts
server/utils/next_url.ts
test/jest.config.server.js

*Description of changes:* Update the `validateNextUrl` function to ensure nextUrl is a relative url.
```
% yarn test:jest_server ./server/utils/next_url.test.ts
yarn run v1.22.0
$ node ./test/run_jest_tests.js --config ./test/jest.config.server.js ./server/utils/next_url.test.ts
PASS  server/utils/next_url.test.ts
test validateNextUrl
✓ accept relative url (4ms)
✓ accept relative url with # and query
✓ reject url not start with /
✓ reject absolute url (1ms)
✓ reject url starts with //
✓ reject url path contains @
✓ accpet url has @ in query parameters
Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        3.036s
Ran all test suites matching /.\/server\/utils\/next_url.test.ts/i.
✨  Done in 9.18s.
```
By submitting this pull …

Update validateNextUrl function

---

public/plugin.ts

*Issue #, if available: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/562
Fix a bug that readonly cannot access tenant switch page by adding the app id to the list.

Fix a bug that readonly cannot access tenant switch page

---

public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx

Display error message given from server on internal user update. Example server response:
~~~JSON
{
"statusCode":400,
"error":"Bad Request",
"message":"Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit, and one special character."
}
~~~
And it is stored in exception.body.
Before:
After:

Display error message given from server on internal user update

---

server/multitenancy/tenant_index.ts

#580
The `forEach` loop iterates over the tenants performing many asynchronous migrations. Switching to a `for..of` loop performs the migrations sequentially.

Perform index migrations sequentially

---

public/apps/account/tenant-selection-page.tsx
public/apps/login/login-page.tsx

If user session is timeout, it will be redirect to login page and a `nextUrl` parameter in url argument is used to redirect back after login. Previously it doesn't care about the hash part. Sample urls:
* http://localhost:5601/app/opendistro_security#/roles
* http://localhost:5601/app/dashboards#/view/7adfa750-4c81-11e8-b3d7-01146121b73d?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:now-24h,to:now))&_a=(description:'Analyze%20mock%20flight%20data%20for%20ES-Air,%20Logstash%20Airways,%20Kibana%20Airlines%20and%20JetBeats',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'%5BFlights%5D%20Global%20Flight%20Dashboard',viewMode:view)
This change …

Preserve hash for nextUrl redirection

---

public/apps/account/account-nav-button.tsx
public/apps/account/tenant-switch-panel.tsx
public/apps/account/test/__snapshots__/account-nav-button.test.tsx.snap
public/apps/account/test/__snapshots__/role-info-panel.test.tsx.snap
public/apps/account/test/__snapshots__/tenant-switch-panel.test.tsx.snap
public/apps/account/test/account-nav-button.test.tsx
public/apps/account/test/role-info-panel.test.tsx
public/apps/account/test/tenant-switch-panel.test.tsx

- Added more unit and functional tests for account menu
*Testing:*
- Ran `yarn tsc`
- Ran `yarn test:jest_ui --coverage `
Folder-level coverage:
File                                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s    
-----------------------------------------------------|---------|----------|---------|---------|----------------------
public/apps/account                                 |   78.31 |    72.06 |   59.18 |   80.75 |                      
account-app.tsx                                    |       0 |        0 |       0 |       0 | 24-40                
account-nav-button.tsx                             |   58.82 |       75 |   45.45 |   66.67 | 92-95,114,144        
constants.tsx …

More test cases for Account menu

---

public/apps/account/tenant-selection-page.tsx

*Issue #, if available:* #552
*Description of changes:* When `securitytenant` is specified in URL, we skip showing the tenant selection dialog.

Skip tenant selection if tenent is specified in URL

---

public/plugin.ts
public/types.ts
server/index.ts

*Description of changes:* When session timeout, server side will return 401 to browser side, this change add an intercepter upon receiving 401 error, browser plugin refresh the page so that the user can re-login to start a new session.

Refresh page to login when session timeout

---

public/apps/configuration/backend_api/client.js
public/apps/configuration/base_controller.js
public/apps/configuration/sections/actiongroups/index.js
public/apps/configuration/sections/internalusers/index.js
public/apps/configuration/sections/roles/index.js
public/apps/configuration/sections/roles/views/index.html
public/apps/configuration/sections/rolesmapping/index.js
public/apps/configuration/sections/tenants/index.js

- PR #502 fixed the navigation and encoding issue of resource names by double encoding it which is an open angular [issue](https://github.com/angular/angular.js/issues/10479).
- Above fix however makes a lot of resource names containing special characters unreadable. 
- Converting route path params into query params. Query params need resource names to be encoded only once. Eg: `internalusers/edit/test123` is converted to`internalusers/edit?resourcename=test123`.
- Change is compatible with (https://docs.angularjs.org/api/ngRoute/service/$routeParams) 
- URL encoding only once before the backend API is called 
Testing:
- Created internal user with `<html><script>test123</script></html>` . Could clone, get and update the user details.
- …

Fix url encoding of resource names

---

public/apps/configuration/panels/role-edit/tenant-panel.tsx
public/apps/configuration/panels/role-edit/test/tenant-panel.test.tsx
public/apps/configuration/types.ts
public/apps/configuration/utils/tenant-utils.tsx
public/apps/configuration/utils/test/tenant-utils.test.tsx

*Description of changes:* `kibana_all_write` indeed means read and write permission, update on the UI, remove write only permission and map Read and Write to `kibana_all_write`

Update tenant permission to Read Only or Read Write

---

.github/workflows/ci.yml

- Use Codecov to visualize the code coverage result
- Add Coverage Report Upload action in `CI workflow`
This change refers to https://github.com/opendistro-for-elasticsearch/index-management/pull/230 for adding Coverage Report Upload action in `CI workflow`

Adds coverage upload

---

common/index.test.ts
common/index.ts
public/apps/configuration/utils/resource-validation-util.tsx
public/apps/configuration/utils/test/resource-validation-util.test.tsx
server/routes/index.ts

Revert removal of resource id restrict and update to only restrict % and control chars.
The current code does not work with `%` as it will be decode twice and raises error.
Control char like `%00` also raises unexpected error.
This PR revert part of 682b45f4f806e2e60058df70363e3e213764c612 and update the regex pattern to disallow `%` and control chars.
Test:  
~~~
[15:04] ~
% curl -u 'admin:!23qweAs' "http://localhost:5603/zlw/api/v1/configuration/roles/t" -XPOST -H 'Content-Type: application/json' -H'kbn-xsrf:abc' -d '{
"cluster_permissions" : [ ],
"index_permissions" : [ ],
"tenant_permissions" : [ ]
}'
{"message":"'t' created."}%      
[15:05] ~
% curl -u 'admin:********' "http://localhost:5603/zlw/api/v1/configuration/roles/t%00" …

Revert removal of resource id restrict and update pattern

---

public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/plugin.ts
public/services/shared-link.ts
server/multitenancy/tenant_resolver.ts

*Issue #, if available:* #591
* add `security_tenant=<tenant_name>` as query parameter to shared urls e.g. `http://localhost:5601/xdj/goto/81eb5d0c993fc4d4a37713383368abb5?security_tenant=global`
* refresh page when admin switch tenant on tenant list page

Add tenant parameter to shared url

---

server/auth/types/authentication_type.ts
server/auth/types/basic/basic_auth.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/saml/saml_auth.ts

*Description of changes:* When session timed out for SAML and OpenID, security plugin returns 302 to redirect the request to IDP for logging in, but this doesn't work for ajax request.
This change returns 401 for ajax request, thus let the browser to handle page refresh, so that it can redirect the browser to login.

Return 401 for ajax calls session when timeout for SAML and OpenID

---

.codecov.yml

explicitly sets main branch as default for codecov

explicitly set main branch as default for codecov

---

public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/role-view/index-permission-panel.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/role-view/tenants-panel.tsx
public/apps/configuration/panels/role-view/test/__snapshots__/index-permission-panel.test.tsx.snap
public/apps/configuration/panels/role-view/test/__snapshots__/role-view.test.tsx.snap
public/apps/configuration/panels/role-view/test/__snapshots__/tenants-panel.test.tsx.snap
public/apps/configuration/panels/role-view/test/cluster-permission-panel.test.tsx
public/apps/configuration/panels/role-view/test/index-permission-panel.test.tsx
public/apps/configuration/panels/role-view/test/role-view.test.tsx
public/apps/configuration/panels/role-view/test/tenants-panel.test.tsx
public/apps/configuration/panels/tenant-list/edit-modal.tsx
public/apps/configuration/panels/tenant-list/test/__snapshots__/edit-modal.test.tsx.snap
public/apps/configuration/panels/tenant-list/test/__snapshots__/tenant-instruction-view.test.tsx.snap
public/apps/configuration/panels/tenant-list/test/__snapshots__/tenant-list.test.tsx.snap
public/apps/configuration/panels/tenant-list/test/edit-modal.test.tsx
public/apps/configuration/panels/tenant-list/test/tenant-instruction-view.test.tsx
public/apps/configuration/panels/tenant-list/test/tenant-list.test.tsx
public/apps/configuration/panels/test/__snapshots__/role-list.test.tsx.snap
public/apps/configuration/panels/test/role-list.test.tsx
public/apps/configuration/panels/test/user-list.test.tsx
public/apps/configuration/panels/user-list.tsx

- Adds more functional test cases for role-view
- Adds more functional test cases for role-list
- Adds more functional test cases for user-list
- Adds more functional test cases for tenant-list
Folder level coverage:
File                                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s      
-----------------------------------------------------|---------|----------|---------|---------|--------------------
public/apps/configuration/panels/role-view          |    92.7 |    76.19 |   86.49 |   93.38 |                        
cluster-permission-panel.tsx                       |     100 |      100 |     100 |     100 |                        
index-permission-panel.tsx                         | …

More functional test cases

---

public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/test/__snapshots__/audit-logging.test.tsx.snap
public/apps/configuration/panels/audit-logging/test/audit-logging-edit-settings.test.tsx
public/apps/configuration/panels/audit-logging/test/audit-logging.test.tsx

- Add more functional test cases for audit logging
Folder level coverage:
File                                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s      
-----------------------------------------------------|---------|----------|---------|---------|---------------------
public/apps/configuration/panels/audit-logging      |   88.96 |     71.7 |    72.5 |   88.96 |                        
audit-logging-edit-settings.tsx                    |    81.4 |    55.56 |   76.92 |    81.4 | 49-50,55-60,131-138    
audit-logging.tsx                                  |     100 |      100 |     100 |     100 |                        
code-editor.tsx                                    |     100 |      100 |     100 …

more functional test cases for audit logging

---

public/apps/configuration/utils/request-utils.ts

Page crashes when server turn empty response body with header `application/json`, it throws a JSON parsing exception and thus body is null. This change is to fix it.
Code referred to:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/9274ab16113a18a6fe504dfbf1970463cf3f25da/public/plugin.ts#L172

Fix a bug of page crash when server turn empty response body

---

public/apps/account/role-info-panel.tsx
public/apps/account/test/__snapshots__/role-info-panel.test.tsx.snap
public/apps/configuration/panels/auth-view/authorization-panel.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/role-mapping/external-identities-panel.tsx
public/apps/configuration/panels/role-mapping/role-edit-mapped-user.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/role-view/test/__snapshots__/role-view.test.tsx.snap
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
public/apps/configuration/utils/role-mapping-utils.tsx

Revert name of external identity back to backend role for backward compatibility.
Screenshots:

Revert name of external identity back to backend role

---

server/auth/types/basic/routes.ts
server/auth/types/saml/saml_auth.ts
server/session/security_cookie.ts

*Description of changes:* Clear `security_authentication` cookie that always use path `/`, and cannot be cleared by the version 7.9 and above.

Clear old version cookies before logging in

---

.github/workflows/cd.yml
.github/workflows/ci.yml
test/constant.ts

- Updates ES and Security plugin version in Constant file for integration testing.
- Uses `set-output` in place of `set-env` in CI/CD workflow.
*Testing:*
```
opendistro_security %  yarn test:jest_server --coverage
Test Suites: 5 passed, 5 total
Tests:       41 passed, 41 total
Snapshots:   0 total
Time:        323.295s
Ran all test suites.
✨  Done in 328.02s.
```

Update CI/CD workflow and ES and security plugin version for IT

---

public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap

- Makes graphics on get started page center aligned
Screenshot:

Make graphics on get started page center aligned

---

server/auth/types/openid/routes.ts
server/index.ts

*Issue #, if available:* #516 
*Description of changes:* Add a config to allow users to choose whether to use `refresh_token` to refresh `id_token`

Add config for OIDC refresh token

---

.github/workflows/cd.yml
kibana.json

* Move to new build process `yarn build`
* Remove the hack for kibana since the new process that does not do typescript check
* Change the name from `opendistro_security_kibana_plugin-{version}.zip` to `opendistroSecurityKibana-{version}.zip` to be consistent with other opendistro plugins
* Update version number to 4 sections (1.12.0 -> 1.12.0.0)
*Test:*
It succeeded in build and failed in "Configure AWS Credentials" due to permission.

Update deployment process for 1.12

---

public/apps/login/login-page.tsx
public/apps/login/test/__snapshots__/login-page.test.tsx.snap

Fix a bug that logo size is improper on login page for some browsers.
Different browser has various default width value for svg image. This change set explicit full width for logo image.
Screenshots:
|Browser|Before|After|
|--|--|--|
|Chrome|![image](https://user-images.githubusercontent.com/63078162/100810494-7a79cb00-33ed-11eb-81d6-6dd50a7821b5.png)|![image](https://user-images.githubusercontent.com/63078162/100810292-07705480-33ed-11eb-98a2-214eb539d5d0.png)|
|Firefox|![image](https://user-images.githubusercontent.com/63078162/100810543-93827c00-33ed-11eb-9df8-5fbf11ac7a6b.png)|![image](https://user-images.githubusercontent.com/63078162/100810309-10f9bc80-33ed-11eb-9c2b-205701a07c42.png)| …

Fix a bug that logo size is improper on login page for some browsers

---

public/plugin.ts

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/639
Allow accessing legacy landing page for readonly user.
With this change, readonly is able to access `/app/kibana` which redirects to `/app/home`.
'short_url_redirect' (`/goto`) is not needed since it is handled by server.

Allow accessing legacy landing page for readonly user

---

README.md

Update build cmd in readme. The build cmd for 1.12 has been updated in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/627.

Update build cmd in readme

---

server/index.ts

This change introduces new unauthenticated route for Kibana reporting stats API **api/reporting/stats**.
The API exposes operational and business metrics for Kibana Reporting plugin. 
See https://github.com/opendistro-for-elasticsearch/kibana-reports/pull/277
Sample response:
```
{
"report": {  
"create": {  # POST /api/reporting/generateReport
"count": 0,
"system_error": 0,
"user_error": 3,
"total": 0
},
"create_from_definition": {  # POST /api/reporting/gemerateReport/{reportDefinitionId}
"count": 1,
"system_error": 0,
"user_error": 0,
"total": 1
},
"download": {  # GET /api/reporting/generateReport/{reportId}
"count": 5,
"system_error": 0,
"user_error": 0,
"total": 5
},
"list": {  # GET /api/reporting/reports
"count": 7, …
```

Add new unauthenticated route for reporting stats API

---

.github/workflows/ci.yml

1. Remove typescript compilation since it has some conflict with current version.
2. Also remove the hack for typescript compilation
3. Update the generated zip file name in CI workflow

Fix github CI workflow

---

server/auth/types/openid/helper.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/openid/routes.ts

*Issue #, if available:* #569
*Description of changes:* Fix the bug where OIDC connection config was not used. Now users can configure the root CA and whether to verify hostnames when connecting to OIDC server

Fix bug of missing some OIDC config

---

kibana.json
package.json

Reverts opendistro-for-elasticsearch/security-kibana-plugin#686
Should merge to opendistro-1.13 instead of main

Revert "Add support for 7.10.2"

---

.github/workflows/ci.yml
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/internal-user-edit/test/internal-user-edit.test.tsx
public/apps/configuration/types.ts
server/routes/index.ts

https://github.com/opendistro-for-elasticsearch/security/issues/996
Omit password field when not updating internal user. 
When updating an internal user, in prior to 1.12, we submit empty password to indicate we're not updating password. Since 1.12, ES security plugin blocks empty password due to deserialization, which causes following error.
This change is to fix this issue.

Omit password field when not updating user

---

.github/workflows/cd.yml

The infrastructure team is separating the production and staging locations into different AWS accounts. Plugins need to modify their workflows to publish to the new locations. This PR changes the CD workflow to add a build number and write the zip artifact to staging.artifacts.opendistroforelasticsearch.amazon.com.
Test Results: 
https://github.com/gaiksaya/security-kibana-plugin/actions/runs/483512658

Change release workflows to use new staging bucket for artifacts

---

.github/workflows/integration-test.yml

Fix github integration test for 1.13.0.1. The (ES) security plugin link is using `1.13.0.0` rather than `1.13.0.1`. This change replace the Build number to 0.

Fix github integration test for 1.13.0.1

---

public/apps/account/tenant-switch-panel.tsx
public/apps/account/test/__snapshots__/tenant-switch-panel.test.tsx.snap

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/718
Save tenant selection by default and remove the checkbox.
|Before|After|
|--|--|
|![](https://user-images.githubusercontent.com/63078162/102422768-55c04e80-3fbc-11eb-80d2-e7228797e4be.png)|![](https://user-images.githubusercontent.com/63078162/102423997-1f380300-3fbf-11eb-83b0-04ee8461f682.png)|

Save tenant selection by default and remove the checkbox

---

.eslintrc.js
.github/workflows/integration-test.yml
opensearch_dashboards.json
package.json
server/auth/types/saml/routes.ts

This PR takes care of the version bump along a few minor changes needed for it to work with core 1.3.0. It also takes care of, as part of a separate commit, downloading instead of building the security plugin. This will shave off a decent chunk of time from our CI. 
Maintenance
Updated version to 1.3.0.0 and dependency on dashboards to 1.3.0
5. __What is the old behavior before changes and new behavior after changes?__ …

Bumped version to 1.3.0.0

---

.whitesource
whitesource.config

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
This is a new feature. 
We @bbarani already enable the access of [WhiteSource integration](https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com) with Github.com for this repo. However, the automatic PR of .whitesource is not created. We asked for the support from WhiteSource side and they suggested we could raise one by ourselves. This PR will also set the WhiteSource integration config mode `LOCAL` so it will be using the `whitesource.config` in the root directory. Dashboards team can modify this configuration on …

Add .whitesource and configs file to activate whitesource integration

---

.github/PULL_REQUEST_TEMPLATE.md

Updated PR template so that it is easier to fill in. Mostly just formatting changes, making it consistent with the backend security plugin repo (https://github.com/opensearch-project/security/pull/1567)
Maintenance
Save a few clicks/keystrokes when filling in PRs.
No behavior changes introduced.
N/A
N/A

Made PR template easier to fill in

---

.github/workflows/backport.yml
DEVELOPER_GUIDE.md

Signed-off-by: Jason <hsiang@amazon.com>
https://github.com/opensearch-project/security-dashboards-plugin/issues/869
[The documentation](https://github.com/tibdex/backport) of how this tool used to automate backporting provides more info.
6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and …

Add auto backport functionality to security plugin

---

.eslintrc.js

Update rule def for @osd/eslint/require-license-header
Previously the rule was defined as:
```json
{
"license": "license",
}
```
Now the format is
```json
{
"licenses": ["license", "..."],
}
```
Test fix
- Resolves #904

Update rule def for @osd/eslint/require-license-header

---

.github/workflows/backport.yml

Signed-off-by: Vacha Shah <vachshah@amazon.com>
Updating the backport workflow to resolve permissions issue opensearch-project/OpenSearch#1712 and allow custom branch naming for backport branches to manage branch permissions.
Using Github App token in the auto-backport workflow to trigger CI on auto-backport PRs since events created by secrets.GITHUB_TOKEN cannot trigger other workflows. Reference: https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250
Bug fix
Fix permissions issue for the backport workflow.
Workflow working in OpenSearch repo, example backport PR https://github.com/opensearch-project/OpenSearch/pull/2079
By submitting this pull request, …

Updating backport workflow with custom branch and github app

---

release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.0.0.md

Backports release notes for version 1.3.0.0 to 1.3 branch
See main PR here: https://github.com/opensearch-project/security-dashboards-plugin/pull/918
Maintenance

[Backport] Adds release notes for 1.3.0.0 (#918)

---

.github/workflows/integration-test.yml
.github/workflows/unit-test.yml

Updates unit and integration test workflow to run on all branches rather than just the main branch
Maintenance
To run test on all PRs

Removes branch filter on test workflow

---

opensearch_dashboards.json
package.json

To be supported within the distribution for OSD 2.0.0-rc1 from the build repo, plugins need to ensure their plugin version is the expected version until https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1398 is addressed. If OSD plugins version does not match the qualifier of the build then the build will fail. 
Maintenance
To build successfully within the build distribution
n/a
n/a
n/a

[Build] bump to 2.0.0.0-rc1

---

server/index.ts
test/jest_integration/basic_auth.test.ts

Signed-off-by: Chang Liu <cgliu@amazon.com>
Enforce authentication on `api/status` route by default.
Bug fix
Secure `api/status` route
Old behavior:
`api/status` route bypasses authentication by default.
New behavior:
Enforce authentication on `api/status` route by default unless user explicitly configures `api/status` as `auth.unauthenticated_routes`.
#945
ITs

Enforce authentication on api/status route by default

---

.github/workflows/integration-test.yml
opensearch_dashboards.json

Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.

Change 2.0-alpha1 to 2.0-rc1.

---

server/index.ts
test/jest_integration/basic_auth.test.ts

Reverts https://github.com/opensearch-project/security-dashboards-plugin/pull/943. The change was planned to be merged after 2.0.0-rc1.

Revert "Enforce authentication on api/status route by default (#943)"

---

.github/workflows/integration-test.yml
server/auth/types/basic/basic_auth.ts
server/auth/types/basic/routes.ts
server/auth/types/jwt/jwt_auth.ts
server/auth/types/openid/openid_auth.ts
server/multitenancy/tenant_resolver.ts
server/utils/next_url.test.ts
server/utils/next_url.ts
test/jest_integration/basic_auth.test.ts

The nextUrl logic was getting back urls that looked like `%2Fgotundefined`  it seems like with the recent node version change there were some breaking changes in the url parsing/processing systems.  I've cleaned up the pattern and confirmed the behavior is correct with new integration tests.
Bug fix
* Related to https://github.com/opensearch-project/security-dashboards-plugin/issues/938
* Resolves https://github.com/opensearch-project/security-dashboards-plugin/issues/936
* _Pending confirmation of many scenarios that are broken_ …

Fix broken `nextUrl=` parameter logic

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.0.0.0-rc1.md

How to repeat:
* `git checkout origin/2.0`
* `git log --pretty=format:"* %s" --since=origin/1.x > release-notes/opensearch-security-dashboards-plugin.release-notes-2.0.0.0-rc1.md`
* Manually organize file sections
* Add Date / Version section (copy + modify from previous release)
* Enhancements/Bug fixes/Maintenance
* Replace pull request ids with full urls via regex
* Find: `#(\d+)`
* Replace: `[#$1](https://github.com/opensearch-project/security-dashboards-plugin/pull/$1)`
* Commit with these steps / modified with additional details …

Generate release notes for 2.0.0

---

public/apps/configuration/constants.tsx

Signed-off-by: Cam McKenzie <camAtGitHub@users.noreply.github.com>
Fix 'openserach' typo. 
This commit has not been tested, however I scanned 'security', 'security-dashboard-plugins, and 'opensearch' repos.
security and its dashboards are the only two occurrences of the word.

Fix 'openserach' typo in constants.tsx

---

public/apps/account/account-nav-button.tsx

The current behavior is that all users will see a message to switch
tenants and if multi-tenancy is disabled, that message will be prompting
the user to ask the admin to enable the feature.  This is causing users
pain that are not interested in using the tenancy features.
* Resolves #838

Select tenant popup only appears when multi-tenacy is enabled

---

public/apps/configuration/constants.tsx

Signed-off-by: Cam McKenzie <camAtGitHub@users.noreply.github.com>
Backport PR #953 to 2.0
bug fix

[Backport to 2.0] Fix 'openserach' typo in constants.tsx (#953)

---

.github/workflows/integration-test.yml
opensearch_dashboards.json
package.json

Fixes broken main build
* Resolves #984 

Fixes broken main build which was caused due to version mismatch

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.0.0.0.md

Signed-off-by: cliu123 <lc12251109@gmail.com>
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation] Maintenance
UTs and ITs

Create release notes 2.0.0

---

public/apps/account/utils.tsx

Signed-off-by: Miki <miki@amazon.com>
OSD uses the browser's `sessionStorage` to store potentially sensitive information. This change clears the `sessionStorage` during logout.
Enhancement
Without this, potentially sensitive information is left in the `sessionStorage`.

Clear the sessionStorage when logging out

---

.github/workflows/integration-test.yml

Signed-off-by: cliu123 <lc12251109@gmail.com>
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation] Maintenance
UTs and ITs

Run integration tests on PRs and Pushes

---

server/auth/types/openid/routes.ts

Signed-off-by: Aozixuan Priscilla Guan <aoguan@amazon.com>
Customized error handling mechanism based on the error message for OIDC routing 
Bug fix
Resolve redirect login looping issues when authentication failures detected.
Old Behavior:
Any exceptions caught during the OIDC authentication process causes redirecting login infinitely.
New Behavior:
If error message includes "authentication error": => return 401: unauthorized 
Else: redirect to login
https://github.com/opensearch-project/security-dashboards-plugin/issues/990
unit testing and integration testing  …

Fix OIDC looping issue - too many redriects

---

DEVELOPER_GUIDE.md

Enhances the dev-guide to be more elaborative and intuitive.
Documentation

Updates Dev guide

---

server/auth/types/saml/routes.ts

Reverts opensearch-project/security-dashboards-plugin#895
To fix breaking SAML auth introduced in this. This change will be re-merged once https://github.com/opensearch-project/security/pull/1936 is merged.

Revert "Replace _opendistro route with _plugins"

---

server/auth/types/saml/routes.ts
server/auth/types/saml/saml_auth.ts
server/session/security_cookie.ts

In Opensearch Dashboards URL Hash encodes the state of a visualization (state could be the filters to apply, the time range etc). Currently for SAML based authentication when User logins-for-the-first-time/re-authenticates the url hash is being dropped because of redirecting to the IDP. This PR ensures that URL Hash is preserved after authenticating with the IDP.
Old Closed PR for reference : https://github.com/opensearch-project/security-dashboards-plugin/pull/1001.
Enhancement
This PR ensures that state of visualization remains consistent after authenticating via IDP.
In the old behavior when the dashboard plugin redirects browser to IDP the hash is lost and User looses their unsaved work. In the new behavior,  before redirecting to IDP the dashboard plugin will store the hash in …

Preserve URL Hash for SAML based login

---

.github/workflows/integration-test.yml
opensearch_dashboards.json
package.json
release-notes/opensearch-security-dashboards-plugin.release-notes-2.1.0.0.md

Increment version to 2.1.1.0

---

MAINTAINERS.md

Following the process in https://github.com/opensearch-project/.github/pull/59, I had nominated Craig Perkins (@cwperks) as a co-maintainer. The maintainers have voted and agreed to this nomination.
Craig has been participating in creating pull requests in both the back-end and front-end security repositories, answering questions and engaging with issue along with providing pull request feedback to keep standards high.

Adding @cwperks to Security maintainers.

---

public/apps/configuration/panels/role-list.tsx

Fixed the column name "Index permissions" on the list of roles page is inconsistent with the field name "Index" on the "Create Role" page
* Resolves https://github.com/opensearch-project/security-dashboards-plugin/issues/922

Fixed the inconsistence of column name on the list of roles page

---

.github/workflows/prerequisite-test.yml

Create a separate workflow and implemented environment variable of version to check for the existence of the OpenSearch Security Plugin artifact
* Resolved https://github.com/opensearch-project/security-dashboards-plugin/issues/1073 
~[CI test case#1 with "403 Forbidden" response](https://github.com/opensearch-project/security-dashboards-plugin/runs/8000467600?check_suite_focus=true)~
~[CI test case#2 with "404 Not Found" response](https://github.com/opensearch-project/security-dashboards-plugin/runs/8000584940?check_suite_focus=true)~
Created a new workflow for "Verify there is matching build of security plugin" by running `prerequisites-test`
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Add the feature of showing useful error message during CI

---

public/apps/account/test/plugin.test.tsx
public/plugin.ts
public/utils/logout-utils.tsx

Fix the issue of user tenant automatically switch back to Private/Global by default after session timeout.
Bug fix
* Resolved https://github.com/opensearch-project/security-dashboards-plugin/issues/1084

Fixed the tenant switching after timeout

---

public/apps/account/tenant-switch-panel.tsx
public/apps/account/test/__snapshots__/tenant-switch-panel.test.tsx.snap

- Add description into the custom tenant selecting dropdown list, and disable the button when there is no valid selection for custom tenant.
- Update the unit test.
Bug fix
* Resolved https://github.com/opensearch-project/security-dashboards-plugin/issues/819

Fix the UI user flow of selecting custom teanant on tenant switch panel

---

opensearch_dashboards.json
public/apps/account/log-out-button.tsx
public/apps/account/test/__snapshots__/log-out-button.test.tsx.snap
public/apps/account/test/log-out-button.test.tsx
public/apps/account/utils.tsx

This fix is for ensuring that tenancy information is read from the local storage in SAML Authentication workflow after a user log out of OS Dashboard. 
Bug Fix
To have a good user experience and ensure their tenancy is reloaded after logging in into a new session in the same browser. 
Tenancy information was not being read from local storage after logout in old behaviour for SAML authentication enabled domains. After the changes, tenancy information will be read from local storage. This is ensured as the session storage variable `pendistro::security::tenant::show_popup` is set to null after logout in SAML Authentication workflow. 
[Issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1057) created for this bug
The changes have been made in …

[ Backport 1.2 ] Tenancy getting Lost in SAML Authentication

---

public/apps/account/log-out-button.tsx
public/apps/account/test/__snapshots__/log-out-button.test.tsx.snap
public/apps/account/test/log-out-button.test.tsx
public/apps/account/utils.tsx

This fix is for ensuring that tenancy information is read from the local storage in SAML Authentication workflow after a user log out of OS Dashboard. 
Bug Fix
To have a good user experience and ensure their tenancy is reloaded after logging in into a new session in the same browser. 
Tenancy information was not being read from local storage after logout in old behaviour for SAML authentication enabled domains. After the changes, tenancy information will be read from local storage. This is ensured as the session storage variable `pendistro::security::tenant::show_popup` is set to null after logout in SAML Authentication workflow. 
[Issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1057) created for this bug
The changes have been made in …

[Backport 1.3] Tenancy getting Lost in SAML Authentication

---

MAINTAINERS.md

Reverts opensearch-project/security-dashboards-plugin#1128
This was accidentally done, we just need to make sure we follow our published process before accepting.  Sorry for the hot/cold on this change.  https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer

Revert "add maintainers"

---

MAINTAINERS.md

This is a PR to add Yan, Bandini and Tianle to the maintainers list as emeritus to recognize their contribution to the creation of the repo in 2021.  This action does not change the active maintainers list, or add any current permissions (but would love for them to become active again)!"

Adding Emeritus folks to maintainer list.  

---

.github/workflows/unit-test.yml
opensearch_dashboards.json
public/apps/account/log-out-button.tsx
public/apps/account/test/__snapshots__/log-out-button.test.tsx.snap
public/apps/account/test/log-out-button.test.tsx
public/apps/account/utils.tsx
server/auth/types/saml/routes.ts

This fix is for ensuring that tenancy information is read from the local storage in SAML Authentication workflow after a user log out of OS Dashboard. 
Bug Fix
To have a good user experience and ensure their tenancy is reloaded after logging in into a new session in the same browser. 
Tenancy information was not being read from local storage after logout in old behaviour for SAML authentication enabled domains. After the changes, tenancy information will be read from local storage. This is ensured as the session storage variable `pendistro::security::tenant::show_popup` is set to null after logout in SAML Authentication workflow. 
[Issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1057) created for this bug
The changes have been made in …

[Backport 1.1] Tenancy getting Lost in SAML Authentication

---

public/apps/account/log-out-button.tsx
public/apps/account/test/__snapshots__/log-out-button.test.tsx.snap
public/apps/account/test/log-out-button.test.tsx
public/apps/account/utils.tsx
server/auth/types/saml/saml_auth.ts
test/jest_integration/saml_auth.test.ts

This backport PR is for the following PRs : 
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1058
[Backport]
Changes need to be back-ported

[Backport 2.x] Fix for Tenancy info getting lost on re-login in SAML Authentication flow 

---

.github/workflows/integration-test.yml
DEVELOPER_GUIDE.md
package.json
public/apps/account/account-nav-button.tsx
public/apps/account/log-out-button.tsx
public/apps/account/test/__snapshots__/account-nav-button.test.tsx.snap
public/apps/account/test/__snapshots__/log-out-button.test.tsx.snap
public/apps/account/test/log-out-button.test.tsx
public/apps/account/utils.tsx
server/auth/types/saml/routes.ts
server/auth/types/saml/saml_auth.ts
server/backend/opensearch_security_client.ts
server/session/security_cookie.ts
test/helper/cookie.ts
test/jest_integration/runIdpServer.js
test/jest_integration/saml_auth.test.ts

This backport PR is for the following PRs : 
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1058
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1088
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1054
[Backport]
Changes need to be backported

[ Backport 2.3 ] 1054, 1058 and 1088

---

opensearch_dashboards.json
public/apps/account/account-app.tsx
public/apps/account/account-nav-button.tsx
public/apps/account/tenant-switch-panel.tsx
public/apps/account/test/account-app.test.tsx
public/apps/configuration/configuration-app.tsx
public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx
public/apps/types.ts
public/plugin.tsx
public/types.ts
server/auth/types/authentication_type.ts
server/index.ts
server/plugin.ts
server/saved_objects/saved_objects_wrapper.ts

Co-authored-by: Craig Perkins <cwperx@amazon.com>
Co-authored-by: Ryan Liang <jiallian@amazon.com>
Co-authored-by: Yan Zeng <zengyan@amazon.com> …

Saved Object Aggregation View

---

MAINTAINERS.md

Adding @RyanL1997 to the maintainers of this repo
[Nomination, vote and interest](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer) have already happened in private email threads with all current maintainers and @RyanL1997 .
Maintenance
@RyanL1997 has been actively making contributions.

Add @RyanL1997 to maintainers

---

public/plugin.tsx

[Feature Branch] Define functions for global and private tenant cases

---

public/apps/account/account-app.tsx
public/apps/account/tenant-switch-panel.tsx
public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx
public/apps/configuration/utils/tenant-utils.tsx
public/plugin.tsx
server/auth/types/authentication_type.ts
server/plugin.ts
server/saved_objects/saved_objects_wrapper.ts

[Feature Branch] Resolve review comments

---

.github/actions/install-dashboards/action.yml
.github/workflows/integration-test.yml
.github/workflows/unit-test.yml

Creates a github action to install and configure Dashboards that is reused within the workflows of this repository, its multi-platform safe.
- Related https://github.com/opensearch-project/security-dashboards-plugin/issues/845
- Related https://github.com/opensearch-project/security-dashboards-plugin/issues/1156
Note: follow up pull request will convert the integration test job to be multi-platform

Support CI for Windows and MacOS

---

server/auth/types/authentication_type.test.ts
server/auth/types/authentication_type.ts
server/multitenancy/tenant_resolver.ts

The Opensearch Dashboards tenant only impacts the saved objects access. The multi-tenant path check in the auth handler was meant to by pass the resolve tenant logic for some APIs which doesn't deal with saved objects. However with the new datasource support feature in OpenSearch Dashboards, Dashboards APIs which used to not dealing with saved objects such as data queries and index resolve operations will require the new data source saved object type under the hood.
This change removes the multi-tenant path check, so that tenant header will be injected to all route handlers. So that all route handlers can work with the right tenant in case they need to deal with any saved objects.
Signed-off-by: Yan Zeng <zengyan@amazon.com>
Bug fix
This change is required for OpenSearch Dashboards data …

Remove multi-tenant path check in auth handler

---

.github/actions/install-dashboards/action.yml
.github/workflows/integration-test.yml
.github/workflows/unit-test.yml

Creates a github action to install and configure Dashboards that is reused within the workflows of this repository, its multi-platform safe.
Signed-off-by: Peter Nied <petern@amazon.com>
(cherry picked from commit a21c7be155c082ede6bb24b9a691805ff1431f03)

[Backport 2.x] Support CI for Windows and MacOS (#1164)

---

.github/actions/install-dashboards/action.yml

Support checkout out #.x branch types
This change was included in change https://github.com/opensearch-project/security-dashboards-plugin/pull/1167 that was merged into 2.x

Support checkout out #.x branch types

---

common/index.ts
public/apps/configuration/utils/tenant-utils.tsx
public/apps/configuration/utils/test/tenant-utils.test.tsx
public/index.ts
server/auth/types/authentication_type.ts
server/multitenancy/tenant_resolver.ts
server/saved_objects/saved_objects_wrapper.ts

[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation] Refactoring
[[List any issues this PR will resolve (Is this a backport? If so, please add backport PR # and/or commits #)]
](https://github.com/opensearch-project/security-dashboards-plugin/issues/1175)
UT, IT, Cypress tests

Move tenant-related utils to common folder

---

.github/workflows/cypress-test.yml
common/index.ts
opensearch_dashboards.json
public/apps/account/account-app.tsx
public/apps/account/account-nav-button.tsx
public/apps/account/tenant-switch-panel.tsx
public/apps/account/test/account-app.test.tsx
public/apps/configuration/configuration-app.tsx
public/apps/configuration/panels/role-edit/cluster-permission-panel.tsx
public/apps/configuration/panels/role-edit/index-permission-panel.tsx
public/apps/configuration/panels/role-edit/tenant-panel.tsx
public/apps/configuration/utils/tenant-utils.tsx
public/apps/configuration/utils/test/tenant-utils.test.tsx
public/apps/types.ts
public/plugin.ts
public/types.ts
server/auth/types/authentication_type.ts
server/index.ts
server/multitenancy/tenant_resolver.ts
server/plugin.ts
server/saved_objects/saved_objects_wrapper.ts

Backport 6c71077b88c08436a385b9debf80892fb4064cb6 from #1146 
Backport 7e2a07c41ed826ec98e7c8d2e0b85188e19ce580 from #1184 
Backport f9b26d82664d7569ca38514fcab8fb574e9d11b9 from #1169

[Backport 2.x] OSD Saved Object Aggregation View

---

test/jest_integration/saml_auth.test.ts

Fixes flaky SAML integration test that tests tenancy persistence on logout. Adds a step to wait for the radio button to be selected before selenium proceeds to confirm the tenant selection modal.
Test fix
https://github.com/opensearch-project/security-dashboards-plugin/issues/1193
To run the flaky test use:
```
yarn run test:jest_server -- saml_auth.test.ts -t "Tenancy persisted after Logout in SAML"
``` …

Wait for tenant radio to be selected in flaky SAML integ test

---

.github/actions/install-dashboards/action.yml
.github/workflows/unit-test.yml

Added a retry around the the bootstrap that previously failed due to network issues.  Ran the new version of this workflow 100 iterations on linux and windows, both passed at 100% [1].
Without the retry during a run of 100 iterations [2], the windows test failed once during the bootstrap.  If we see future issues, we could attempt to add retries to them following this same pattern.
[1] https://github.com/peternied/security-dashboards-plugin/actions/runs/3449518073
[2] https://github.com/peternied/security-dashboards-plugin/actions/runs/3449040181
- Resolves #1211
- Resolves #1195
For more information on following Developer Certificate of Origin and signing off your commits, …

Add retry and enable UTs for Windows

---

public/apps/configuration/constants.tsx
public/apps/configuration/panels/audit-logging/test/__snapshots__/audit-logging.test.tsx.snap
public/apps/configuration/panels/internal-user-edit/backend-role-panel.tsx
public/apps/configuration/panels/role-mapping/external-identities-panel.tsx
public/apps/configuration/panels/role-view/test/__snapshots__/role-view.test.tsx.snap
public/apps/configuration/panels/tenant-list/test/__snapshots__/tenant-list.test.tsx.snap
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap

Replaced URLs starting with `https://docs-beta.opensearch.org/docs/security` to start with `https://opensearch.org/docs/latest/security-plugin` and updates link to multi-tenancy documentation renamed in this PR: https://github.com/opensearch-project/documentation-website/pull/1786
Bug fix
https://github.com/opensearch-project/security-dashboards-plugin/issues/1174
Updated snapshots with old URLs
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develope …

Update URLs referencing old docs-beta site

---

.github/workflows/add-untriaged.yml

Automatically add `untriaged` label on issues
Enhancement
* Related https://github.com/opensearch-project/security/pull/2297
Tested this on my own fork of this repo with two cases:
- Test of reopened issue: https://github.com/RyanL1997/security-dashboards-plugin/issues/1
- Test of opened issue: https://github.com/RyanL1997/security-dashboards-plugin/issues/3

Automatically add `untriaged` label on issues

---

common/index.ts
server/multitenancy/tenant_index.ts
server/multitenancy/test/tenant_index.test.ts

The issue description of https://github.com/opensearch-project/security-dashboards-plugin/issues/1246 explains the issue to be resolved.
The PR title described the approach to fix the issue. 
Bug fix
https://github.com/opensearch-project/security-dashboards-plugin/issues/1246
UTs and ITs

Set order of tenant_template to the highest to avoid being overridden by custom templates

---

.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml

Change security plugin CI build version 'latest' into build version '6705' to include the change of removing jackson-databind in gradle for security plugin.
Test fix
* Related https://github.com/opensearch-project/security/issues/2324#issuecomment-1346908811
* Related https://github.com/opensearch-project/security/pull/2325
GitHub Action

Change security CI build version 'latest' into build version '6705' 

---

common/index.ts
server/multitenancy/tenant_index.ts
server/multitenancy/test/tenant_index.test.ts

Backport dcf75c49543997e0e85dde9be314d5df81e60491 from #1247

[Backport opendistro-1.13] Set order of tenant_template to the highest to avoid being overridden by custom templates

---

common/index.ts
public/apps/account/utils.tsx
server/index.ts
server/multitenancy/tenant_index.ts
server/multitenancy/test/tenant_index.test.ts

Backport dcf75c49543997e0e85dde9be314d5df81e60491 from #1247

[Backport opendistro-1.11] Set order of tenant_template to the highest to avoid being overridden by custom templates

---

.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml

Switching back to using `latest` in routes to download the security plugin for github workflows.
Maintenance
https://github.com/opensearch-project/security-dashboards-plugin/issues/1271

Switch back to downloading latest distribution for cypress and integ tests

---

server/auth/types/openid/helper.test.ts
server/auth/types/openid/helper.ts
server/auth/types/openid/routes.ts

Fixes an issue on openid login that redirects to  `/` when a `opensearch_security.openid.base_redirect_url` is present and a `nextUrl` query param is absent. `opensearch_security.openid.base_redirect_url` is configured in `opensearch_dashboards.yml` and often matches the `server.basePath` which is the root url for OSD. On successful login, the user should be routed to the redirect url if nextUrl is absent. 
Bug fix
https://github.com/opensearch-project/security-dashboards-plugin/issues/1098
Adds 2 new unit tests to test when request.query.nextUrl is present and when it is absent to use the config.openid?.base_redirect_url
By submitting this pull request, …

Fix openid redirect issue to use base_redirect_url when nextUrl is absent

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.5.0.0.md

Add release note for 2.5.0
Maintenance
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1286 

Add release note for 2.5.0

---

MAINTAINERS.md

Stephen Crawford (@scrawfor99) has been an avid contributor to Security plugin & Security Dashboard plugin since October '22, clocking in with 137 contributions in the OpenSearch project.  He has earned his place as a maintainer with the following valuable contributions.
- Created [41](https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity+repo%3Aopensearch-project%2Fsecurity-dashboards-plugin+author%3Ascrawfor99&type=pullrequests&ref=advsearch) pull requests.
- Involved in [55 & 31](https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity+repo%3Aopensearch-project%2Fsecurity-dashboards-plugin+-author%3Ascrawfor99+involves%3Ascrawfor99+&type=pullrequests&ref=advsearch) issues and pull requests respectively.
- Mentioned in …

Adding @scrawfor99 to the maintainers

---

public/apps/configuration/panels/auth-view/instruction-view.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap

The dashboard has references to an old path that does not exist anymore:
`plugins/opensearch-security/securityconfig/config.yml`.  It was
replaced by `config/opensearch-security/config.yml` in this commit:
https://github.com/opensearch-project/security/commit/b44d7eafc1250a0d58828ef6f9cef48b5755fefc
Fix the last occurences of `plugins/opensearch-security/securityconfig`.

Fix plugin configuration path

---

.github/workflows/integration-test.yml
opensearch_dashboards.json
package.json

Increment version to 1.3.8
Maintenance

[1.3] Increment version to 1.3.8

---

package.json
yarn.lock

Upgrade `loader-utils` to 2.0.4 and above to fix [CVE-2022-37601](https://advisories.aws.barahmand.com/advisory/CVE-2022-37601)
Upgrade `loader-utils` to 2.0.4 and above to fix [CVE-2022-37603](https://advisories.aws.barahmand.com/advisory/CVE-2022-37603)
Upgrade `glob-parent` to 6.0.0 and above to fix [CVE-2020-28469](https://advisories.aws.barahmand.com/advisory/CVE-2020-28469)
Upgrade `decode-uri-component` to 0.2.2 and above to fix [CVE-2022-38900](https://advisories.aws.barahmand.com/advisory/CVE-2022-38900)
Maintenance
For more information on following Developer Certificate of Origin and signing off your commits, please …

[1.3] Fix CVE dependencies

---

.github/actions/download-plugin/action.yml

The Security Plugin publishing snapshots of its build through maven.  Switching from the distribution build to these maven based artifacts.
Note; The security plugin does not publish these artifacts for version 1.x so this change should not be backported.
- Resolves https://github.com/opensearch-project/security-dashboards-plugin/issues/1328
This change is tested through GitHub Actions associated with this project

Switch to maven to download plugin snapshots

---

public/apps/configuration/constants.tsx

Adds `indices:admin/close*` to list of permissible index permissions to cover associated close actions like [TransportVerifyShardBeforeCloseAction](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseAction.java). (Action name: `indices:admin/close[s]`)
Bug Fix
https://github.com/opensearch-project/security/issues/1461 …

Add indices:admin/close* to list of permissible index permissions

---

.github/workflows/auto-release.yml

This adds an auto-release workflow to automatically generate a release with the corresponding release notes when a tag is created.
Enhancement
https://github.com/opensearch-project/security-dashboards-plugin/issues/1324
Tested by creating a Github App and running the workflow in my personal fork. I believe the installation_id corresponds to the opensearch-trigger-bot installation, but I'm not positive. The number is also referenced in the backport workflow here: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/workflows/backport.yml#L19-L22
For more …

Add auto-release workflow

---

.github/CODEOWNERS

Fix the format of the codeowners file
All maintainers are considered code-owners instead of only @scrawfor99 :D
Duplicate version of the following PR in the security repo
- https://github.com/opensearch-project/security/pull/2469

Fix the format of the codeowners file

---

DEVELOPER_GUIDE.md

Small update to developer guide to fix issue with the value of `server.host`.
Documentation

Change server.host to 0.0.0.0 for DEVELOPER_GUIDE

---

server/multitenancy/tenant_index.ts
server/multitenancy/test/tenant_index.test.ts

This change replaces the legacy template with the new index template.
**This PR depends on https://github.com/opensearch-project/security/pull/2503, so the https://github.com/opensearch-project/security/pull/2503 needs to be merged first.**
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation] Enhancement
The new index template is the replacement of the legacy template.
https://github.com/opensearch-project/security-dashboards-plugin/issues/1222
UT & IT & Manual Testing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …

Replace legacy template with index template

---

public/apps/configuration/panels/internal-user-edit/backend-role-panel.tsx
public/apps/configuration/panels/internal-user-edit/test/__snapshots__/backend-role-panel.test.tsx.snap
public/apps/configuration/panels/internal-user-edit/test/backend-role-panel.test.tsx

Perform a check on the list of backend roles whether it contains an empty value. If it does, display an error message and don't allow the user to create additional backend roles until the existing blank panels are filled with values.
[Bug fix]
Those changes help to make UX more intuitive and also prevent undesired user behaviour.
Before the changes, new empty backend roles were added every time the "Add another backend role" button was clicked.
After the change, it is checked whether there are any empty fields before adding a new one.
* Resolve: https://github.com/opensearch-project/security-dashboards-plugin/issues/1307
- First case : the user tries to add a new backend role while the last text field is empty.
- Second case: the user tries to add a new backend role while any previously …

No blank backend role before adding a new one in Create User page

---

server/multitenancy/tenant_index.ts

Removes tiny.amazon.com links that are internal.
Maintenance
N/A

Removes tiny.amazon.com links

---

.github/workflows/cypress-test-tenancy-disabled.yml
public/apps/account/account-nav-button.tsx
public/apps/account/test/account-nav-button.test.tsx
public/apps/configuration/panels/tenant-list/manage_tab.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/tenant-list/test/tenant-list.test.tsx
public/plugin.ts
server/multitenancy/tenant_resolver.ts

With https://github.com/opensearch-project/security-dashboards-plugin/pull/1394/files, we removed the use of flag `opensearch_security.multitenancy.enabled in the opensearchdashboard.yaml file`.
This caused some breaking changes like: https://github.com/opensearch-project/security-dashboards-plugin/issues/1412
With this CR, we will ensure that tenancy for Dashboards UI will also be disabled when `opensearch_security.multitenancy.enabled in the opensearchdashboard.yaml file` is disabled.
Bug fix
Fixing: https://github.com/opensearch-project/security-dashboards-plugin/issues/1412
Earlier tenancy was disabled only by making change in SecurityIndex using API or Dashboards UI. With these changes, dashboards tenancy will be disabled with flag `opensearch_security.multitenancy.enabled in the …

Fixing dynamic tenancy changes for issues 1412

---

test/jest_integration/multi_tenancy.test.ts
test/jest_integration/security_entity_api.test.ts

Change the testuser's password in some integration test cases into a stronger password
Test fix
* Resolve https://github.com/opensearch-project/security-dashboards-plugin/issues/1429
* Prerequisites https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/663
* Relate https://github.com/opensearch-project/security/pull/2557

Change the testuser's password in some integration test cases into a stronger password

---

test/jest_integration/saml_auth.test.ts

Adds `.skip` to the SAML Test: `Tenancy persisted after Logout in SAML`. The test passes after many tries, but has a high failure rate which is making it hard to merge PRs in time. All selenium tests are going to be migrated to the opensearch-dashboards-functional-test repo as soon as the Cypress 12 upgrade is complete so that cross-origin testing is supported which is required for SAML testing.

Skip flaky SAML test as it awaits a fix

---

.github/workflows/cypress-test-tenancy-disabled.yml
public/apps/account/account-nav-button.tsx
public/apps/account/test/account-nav-button.test.tsx
public/apps/configuration/panels/tenant-list/manage_tab.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/tenant-list/test/tenant-list.test.tsx
public/plugin.ts
server/multitenancy/tenant_resolver.ts

Backport of https://github.com/opensearch-project/security-dashboards-plugin/pull/1419 to 2.8

[Backport 2.8] Fixing dynamic tenancy changes for issues 1412

---

.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml

[Backport 2.x] Use version from package.json for integration tests

---

public/apps/account/password-reset-panel.tsx
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/utils/password-edit-panel.tsx
public/apps/configuration/utils/test/password-edit-panel.test.tsx
public/types.ts

Companion Security PR: https://github.com/opensearch-project/security/pull/2949
This PR uses the message from `/_plugins/_security/dashboardsinfo` to get the password message from the backend if its configured in `opensearch.yml`. If the setting is not set, the backend will return the default.
Bug fix
https://github.com/opensearch-project/security-dashboards-plugin/issues/1501
Jest tests and manual dashboard testing of both password reset and password edit …

Use password message from /dashboardsinfo

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.9.0.0.md

Add release notes for 2.9.0.0
Documentation

Add release notes for 2.9.0.0

---

.github/actions/install-dashboards/action.yml

Change the version parsing command's regex to handle double digits minor versions
Enhancement
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1532
* Relate https://github.com/opensearch-project/security-dashboards-plugin/pull/1533

Change the version parsing command's regex to handle double digits minor versions

---

.github/actions/install-dashboards/action.yml
opensearch_dashboards.json
package.json

Change the regex command in install dashboard GHA to handle generic format of version numbers. This PR also includes the  version bump to 2.10.0.
Bug fix
* Relate https://github.com/opensearch-project/security-dashboards-plugin/pull/1526
* Resolve https://github.com/opensearch-project/security-dashboards-plugin/issues/1532
Before:
After:

[2.x] Change the regex command in install dashboard GHA + Increment version to 2.10.0

---

public/apps/configuration/_index.scss
public/apps/configuration/panels/audit-logging/_index.scss

There are 2 instances in this repo of hardcoded colors:
```
public/apps/configuration/_index.scss
17:3  ✖  Using the value "#687078" is not allowed. All colors should be inherited from the OUI theme, not hard-coded. Either remove the custom color rule or use OUI SASS variables instead. (no_restricted_values)  @osd/stylelint/no_restricted_values
public/apps/configuration/panels/audit-logging/_index.scss
10:3  ✖  Using the value "#666" is not allowed. All colors should be inherited from the OUI theme, not hard-coded. Either remove the custom color rule or use OUI SASS variables instead. (no_restricted_values)  @osd/stylelint/no_restricted_values
```
This PR either updates or removes the instance of the hardcoded color to comply with …

Update or remove instances of hardcoded colors

---

.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml

CI fixes for adapting admin password change
Test fix
* Relate: https://github.com/opensearch-project/security/pull/3329
* Cypress issue: https://github.com/cypress-io/cypress/issues/27804

CI fixes for adapting admin password change and fix the Cypress browser

---

server/session/cookie_splitter.test.ts
server/session/cookie_splitter.ts

This PR fixes a regression regarding the OIDC refresh token flow, caused by the move to the split cookies here: https://github.com/opensearch-project/security-dashboards-plugin/pull/1352
It closes https://github.com/opensearch-project/security-dashboards-plugin/issues/1522 and is based on the research made by @cwperks in https://github.com/opensearch-project/security-dashboards-plugin/pull/1569.
In short, while the refresh token flow was still working correctly, the cookie splitter would not have access to the new idToken that was written to the cookie in the process of refreshing the token. Even though the new value was written, the cookie splitter could not access that value until the next request lifecycle. This caused a "Token expired" and the user would be unauthenticated.
End to end …

Fix OIDC refresh token flow when using the cookie splitter

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.11.0.0.md

Adds 2.11.0.0 release notes

---

public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-edit/test/role-edit-filtering.test.tsx

Fix custom/kibana/all permission groups missing from dropdown. This was because I had assumed there were only "cluster" and "index" type groups, whereas there are also custom, kibana, and all types for permission groups. This has slight duplication since the custom types will show up in both cluster and index dropdowns, but this fixes the bug.
More details here: https://github.com/opensearch-project/security-dashboards-plugin/pull/1636#issuecomment-1789606810
FIX: https://github.com/opensearch-project/security-dashboards-plugin/issues/1597
By submitting this pull request, I confirm that my contribution is made …

Fix bug where custom permission groups are missing

---

.github/actions/download-plugin/action.yml

Due to recent changes to admin credentials, the integration test task fails with `Password admin is weak. Please re-try with a stronger password.`. See [here](https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/6905876298/job/18789612493?pr=1472#step:11:268) for example.
To fix the CI.
CI is broken without this fix.

Passes `-t` flag to demo-config script in the setup script step to skip password validation

---

.github/workflows/integration-test.yml
opensearch_dashboards.json
package.json

Increment version to 1.3.14.0
Maintenance

[1.3] Increment version to 1.3.14.0

---

.github/workflows/cypress-test-oidc-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml
DEVELOPER_GUIDE.md

Fixes documentation assuming admin password is admin. Also updates the integration tests to work with the new location of the initial admin password.

Update instances of admin:admin in documentation and fix file location

---

.github/workflows/cypress-test-oidc-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml

Recent changes in security backend disallows passing in the initial admin password via a txt file since it is insecure. This removes that step and sets the environment variable to successfully spin up the cluster.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONT …

Remove txt file option and pass in OPENSEARCH_INITIAL_ADMIN_PASSWORD env variable

---

.github/actions/download-plugin/action.yml
.github/workflows/cypress-test-oidc-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml
.github/workflows/integration-test.yml

Consumes changes in 2.x line of security backend plugin that requires admin password to be set via an environment variable. Also changes the CI to run in "test" mode to accept the weak admin password "admin".
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUT …

[2.x] Pass in env variable and -t flag to set "admin" as the initial admin password

---

public/apps/configuration/constants.tsx

Adds the cluster permission to render a search template in the cluster permissions dropdown. 
Render search template was made into a separate transport action in core in this [PR](https://github.com/opensearch-project/OpenSearch/pull/11170)
Maintenance
Related: https://github.com/opensearch-project/security/issues/3672

Add indices:data/read/search/template/render to cluster permissions dropdown

---

.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml

Fixes an error seen on cypress tests runs like [this](https://github.com/cwperks/security-dashboards-plugin/actions/runs/7426340976/job/20209864738):
```
...
Still waiting to connect to Firefox, retrying in 1 second (attempt 58/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 59/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 60/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 61/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to Firefox.
This usually indicates there was a problem opening the Firefox browser.
Error: could not find CRI target
at lazyAssLogic (/home/runner/.cache/Cypress/9.5.4/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
at …
```

Run `cypress-tests` and `cypress-tests-tenancy-disabled` on Chrome

---

.github/workflows/verify-binary-installation.yml

The original PR was missing a block that extracted the version. It still worked since 3.0.0 doesn't need to be switched but 2.x does.

Add block to extract OSD version 2.x from package.json

---

.github/workflows/verify-binary-installation.yml

This PR adds a step to install the dependencies prior to building. This will fix the workflow of installing the binary when the dependent libraries are not installed yet, leading to false-positive failures of the install via binary workflow.
The reason why this was not caught before is that security dashboards plugin's current dependencies are only used in the `server` and `test` folders. In the build process, there is a step to run yarn to install dependencies, but the workflow is erroring out in the @osd/optimizer step when trying to add dependencies that live in the `public` folder. This is because the front end code needs to be bundled and thus when a dependency is not there it will error out. This should fix the build and install workflow for dependencies used in the frontend …

Add step to install dependencies prior to building

---

package.json
yarn.lock

Moves eslint-plugin-cypress to a devDependency since it is only used in formatting cypress files. Runs yarn to update the lock file, but this didn't change anything. 
#1745 

Moves eslint to devDependency

---

.github/workflows/cypress-test-oidc-e2e.yml

[Backport 2.x] Refactor cypress OIDC tests to use Run Cypress Tests action (#1755)

---

MAINTAINERS.md

@derek-ho has been an avid contributor to the security-dashboards-plugin repo since June '23 with 12 Pull Requests merged into main to date. Derek regularly engages on Pull Requests by giving other contributors valuable feedback, helps to maintain all release branches with critical bug fixes and ensuring dependencies are free of known security vulnerabilities, and contributes new features to the security-dashboards-plugin. Some of @derek-ho's notable contributions include:
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1482 - Fix to show only pertinent actions and action groups when looking at cluster_permissions or index_permissions dropdowns.
- https://github.com/opensearch-project/security-dashboards-plugin/pull/1636 - Fix for custom action groups to be visible …

Adding @derek-ho as a maintainer

---

MAINTAINERS.md

This PR is made to revert PR #1758 which added @derek-ho as a maintainer.
While I continue to believe that Derek would be a great maintainer of the project, I was overeager when merging the pull request. The Security and Security Dashboards repositories follow a 1-week "bake" period practice where all nominations for maintainership must wait 1 week before being merged. I was too quick to merge the pull request so unfortunately must revert it.
This is definitely embarrassing on my part but I wanted to correct my mistake.

Revert Adding @derek-ho as a maintainer (opensearch-project#1758)

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.12.0.0.md

Add release notes for 2.12.0.0 release
Documentation
- https://github.com/opensearch-project/security-dashboards-plugin/issues/1606

Add release notes for 2.12.0.0

---

.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml

Figured out the issue was the removal of newline here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5777/files#r1480507232. This caused the first line of server.host to be written into a comment, and thus leaving cypress not able to access OSD. 
Fix: #1779

Clear the contents of opensearch_dashboards prior to putting settings

---

.github/actions/install-dashboards/action.yml
.github/workflows/verify-binary-installation.yml

Coming from: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5675, this PR adds the flag to have loose single-version dependencies. Ideally this should not be enforced for devDependencies, but should unblock the build. 
CI fix.
OSD core added a dependency to cypress 9.5.4 (mismatching with the version in this repo) here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5725/files#r1494915750, leading to error at bootstrap.
Old behavior is that the bootstrap process would fail. OSD core added a dependency to cypress 9.5.4 in this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5725/files#r1494915750. Since we need cypress 13 in order to run our test suites (including cross-origin support), bootstrapping the plugin with OSD fails since …

Add loose flag to OSD bootstrap

---

public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/tenant-list/configure_tab1.tsx
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
public/apps/configuration/panels/test/get-started.test.tsx

This PR adds a toast message for success and failure of the purge cache action. 
Enhancement
Today, there is no indication that a purge cache action succeeded or failed. This can be confusing to the user as they would not know the result unless they have the network tab open or are checking the backend logs. This adds visual indication and brings this action more inline with other actions such as create user. This also acts as a shim for end to end testing which can rely on the new toast to see if some action succeeded or failed.
New behavior shown below:
https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/9c500548-1f85-407f-962a-66269fcdcc14
[List any issues this PR will …

Add toast handling for purge cache action

---

.github/workflows/integration-test.yml
common/index.ts
server/auth/types/authentication_type.ts
server/auth/types/openid/openid_auth.test.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/openid/routes.ts
server/auth/types/saml/routes.ts
server/auth/types/saml/saml_auth.test.ts
server/auth/types/saml/saml_auth.ts
server/index.ts
server/session/cookie_splitter.test.ts
server/session/cookie_splitter.ts
server/utils/compression.test.ts
server/utils/compression.ts
test/jest_integration/saml_auth.test.ts

[Backport 1.3] Split up a value into multiple cookie payload

---

.github/workflows/cypress-test-multidatasources-disabled-e2e.yml
.github/workflows/cypress-test-multidatasources-enabled-e2e.yml
.github/workflows/integration-test.yml
opensearch_dashboards.json
public/apps/configuration/app-router.tsx
public/apps/configuration/configuration-app.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
public/apps/configuration/panels/test/get-started.test.tsx
public/apps/configuration/test/top-nav-menu.test.tsx
public/apps/configuration/top-nav-menu.tsx
public/apps/configuration/utils/request-utils.ts
public/apps/types.ts
public/plugin.ts
public/types.ts
server/backend/opensearch_security_client.ts
server/plugin.ts
server/routes/index.ts
test/cypress/e2e/multi-datasources/multi_datasources_disabled.spec.js
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
test/cypress/support/commands.js
test/jest_integration/security_entity_api.test.ts

Registers the new DataSource picker component from core in the top nav menu for the "Get Started" Tab. 
New feature
- Resolves #1796
- Resolves #1816
- Resolves #1795 
Old behavior is no selector, new behavior is shown in this video: 
https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/6554d631-e5ca-461d-a044-23a7556a5b08
Fix: #1796, Fix: #1816 Fix: #1795 
Manual testing, unit tests added, e2e cypress test added
For more information on following …

Register Datasource Picker in the top nav menu for Get Started Tab

---

.github/workflows/integration-test.yml
common/index.ts
opensearch_dashboards.json
package.json
release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.14.0.md
server/auth/types/authentication_type.ts
server/auth/types/openid/openid_auth.test.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/openid/routes.ts
server/auth/types/saml/routes.ts
server/auth/types/saml/saml_auth.test.ts
server/auth/types/saml/saml_auth.ts
server/index.ts
server/session/cookie_splitter.test.ts
server/session/cookie_splitter.ts
server/utils/compression.test.ts
server/utils/compression.ts
test/jest_integration/saml_auth.test.ts

Synchronizes 1.x branch with 1.3
- Adds missing release notes (cherry-picked commit 307c7a0)
- Increment version to 1.3.15.0 (#1698)(cherry-picked commit fce71db)
- [Backport 1.3] Split up a value into multiple cookie payload (#1831) (cherry-picked commit 5f3efab)
Without cherry-picking it tried to add 10 additional commits which were already picked up in the [last sync](https://github.com/opensearch-project/security-dashboards-plugin/pull/1688). …

[Sync 1.x with 1.3] Cookie splitter, release notes and version increment

---

.github/workflows/cypress-test-multidatasources-enabled-e2e.yml
public/apps/account/utils.tsx
public/apps/configuration/app-router.tsx
public/apps/configuration/panels/auth-view/auth-view.tsx
public/apps/configuration/panels/auth-view/test/auth-view.test.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
public/apps/configuration/panels/test/get-started.test.tsx
public/apps/configuration/test/__snapshots__/app-router.test.tsx.snap
public/apps/configuration/test/app-router.test.tsx
public/apps/configuration/top-nav-menu.tsx
public/apps/configuration/utils/action-groups-utils.tsx
public/apps/configuration/utils/audit-logging-utils.tsx
public/apps/configuration/utils/auth-view-utils.tsx
public/apps/configuration/utils/internal-user-detail-utils.tsx
public/apps/configuration/utils/internal-user-list-utils.tsx
public/apps/configuration/utils/request-utils.ts
public/apps/configuration/utils/role-detail-utils.tsx
public/apps/configuration/utils/role-list-utils.tsx
public/apps/configuration/utils/tenancy-config_util.tsx
public/apps/configuration/utils/tenant-utils.tsx
public/utils/auth-info-utils.tsx
public/utils/dashboards-info-utils.tsx
public/utils/logout-utils.tsx
server/routes/index.ts
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
test/jest_integration/security_entity_api.test.ts

Supports multi datasources for the "Authentication Tab". Lifts the state up to be managed/saved across Get Started and Authentication tabs. 
https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/6dc676fb-52b9-4e1a-86c0-f96f5d0d24b7
Fix: #1797, Fix: #1816 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …

Lift state up one and generalize flow, render picker for auth tab

---

.eslintrc.js
.husky/pre-commit
package.json
public/apps/account/tenant-switch-panel.tsx
public/apps/account/utils.tsx
public/apps/configuration/app-router.tsx
public/apps/configuration/panels/internal-user-edit/test/backend-role-panel.test.tsx
public/apps/configuration/panels/role-edit/test/role-edit.test.tsx
public/apps/configuration/panels/role-mapping/role-edit-mapped-user.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/role-view/tenants-panel.tsx
public/apps/configuration/panels/service-account-list.tsx
public/apps/configuration/panels/tenant-list/manage_tab.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/utils/tenancy-config_util.tsx
public/apps/configuration/utils/tenant-utils.tsx
public/apps/configuration/utils/test/password-edit-panel.test.tsx
public/apps/login/login-app.tsx
public/utils/dashboards-info-utils.tsx
server/auth/types/jwt/jwt_auth.ts
server/auth/types/jwt/jwt_helper.test.ts
server/auth/types/multiple/multi_auth.ts
server/auth/types/openid/openid_auth.ts
server/auth/types/openid/routes.ts
server/auth/types/proxy/proxy_auth.ts
server/backend/opensearch_security_client.ts
yarn.lock

Adds a rule to lint any commits prior to pushing. This should fix cases where work is pushed up but not linted, failing CI. TODO: should we add running tests here? 
Linting was not done automatically and developer cycles were needed to remember to manually run that command
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/1805
For more information on following …

Add husky to pre-lint any commits, remove unused imports

---

public/apps/account/utils.tsx
public/apps/configuration/panels/auth-view/auth-view.tsx
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/internal-user-edit/test/internal-user-edit.test.tsx
public/apps/configuration/panels/test/get-started.test.tsx
public/apps/configuration/panels/test/user-list.test.tsx
public/apps/configuration/panels/user-list.tsx
public/apps/configuration/test/top-nav-menu.test.tsx
public/apps/configuration/top-nav-menu.tsx
public/apps/configuration/utils/action-groups-utils.tsx
public/apps/configuration/utils/audit-logging-utils.tsx
public/apps/configuration/utils/internal-user-detail-utils.tsx
public/apps/configuration/utils/internal-user-list-utils.tsx
public/apps/configuration/utils/request-utils.ts
public/apps/configuration/utils/role-detail-utils.tsx
public/apps/configuration/utils/role-mapping-utils.tsx
public/apps/configuration/utils/tenancy-config_util.tsx
public/apps/configuration/utils/tenant-utils.tsx
public/apps/configuration/utils/test/internal-user-list-utils.test.tsx
public/utils/datasource-utils.ts
public/utils/test/datasource-utils.test.ts
server/routes/index.ts
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
test/helper/entity_operation.ts
test/jest_integration/security_entity_api.test.ts

Supports multi datasources in the user tab, both for fetching user and for creating/deleting/editing users. 
New Feature
To support multi datasources in the users tab
https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/d5878764-7058-42f6-a5cb-d65d675f07cb
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#deve …

Add multi datasource support for the Users tab

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/audit-logging/audit-logging-edit-settings.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/test/__snapshots__/audit-logging.test.tsx.snap
public/apps/configuration/panels/audit-logging/test/audit-logging-edit-settings.test.tsx
public/apps/configuration/panels/audit-logging/test/audit-logging.test.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/test/__snapshots__/app-router.test.tsx.snap
public/apps/configuration/utils/audit-logging-utils.tsx
server/routes/index.ts
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
test/jest_integration/constants.ts
test/jest_integration/security_entity_api.test.ts

This PR adds multi datasource support for the tenancy and audit logging tabs. 
Feature
https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/fb296a44-9745-4d72-9488-c881da6f1865
Resolves: https://github.com/opensearch-project/security-dashboards-plugin/issues/1800
Resolves: https://github.com/opensearch-project/security-dashboards-plugin/issues/1801
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificat …

Add multi datasource support for the tenant and audit log tabs

---

public/apps/account/test/plugin.test.tsx
public/apps/account/utils.tsx
public/utils/logout-utils.tsx

Clear session storage on auto-logout & remove unused saml function
Bug fix
We want to clear the Session storage on auto-logout since they can contain sensitive information. Today this functionality already exists in logout feature. 
* Old Behaviour: Session storage is preserved even after auto-logout. 
* New Behaviour: Session storage is cleared after auto-logout. 
Added unit tests to verify the clear session storage function is called in before landing the login page. 
For more information on following Developer Certificate of Origin and signing off your commits, …

Clear session storage on auto-logout & remove unused saml function

---

public/apps/account/utils.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-edit/test/role-edit-filtering.test.tsx
public/apps/configuration/panels/role-edit/test/role-edit.test.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/role-mapping/role-edit-mapped-user.tsx
public/apps/configuration/panels/role-mapping/test/role-edit-mapped-user.test.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/role-view/test/__snapshots__/role-view.test.tsx.snap
public/apps/configuration/panels/role-view/test/role-view.test.tsx
public/apps/configuration/panels/test/__snapshots__/role-list.test.tsx.snap
public/apps/configuration/panels/test/role-list.test.tsx
public/apps/configuration/utils/display-utils.tsx
public/apps/configuration/utils/internal-user-list-utils.tsx
public/apps/configuration/utils/request-utils.ts
public/apps/configuration/utils/role-detail-utils.tsx
public/apps/configuration/utils/role-list-utils.tsx
public/apps/configuration/utils/role-mapping-utils.tsx
public/apps/configuration/utils/tenant-utils.tsx
public/apps/configuration/utils/test/__snapshots__/display-utils.test.tsx.snap
public/utils/dashboards-info-utils.tsx
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
test/jest_integration/security_entity_api.test.ts

Adds datasource selector capability to Roles tab.
New feature
- Resolves #1798 
- Automated
- Manual [see attached video]
https://github.com/opensearch-project/security-dashboards-plugin/assets/35282393/1b020e68-1a7b-4edd-8b91-ad2423165110

Adds datasource picker for Roles tab and its sub-tabs

---

public/apps/configuration/panels/service-account-list.tsx
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js

Adds selector on service accounts tab
Enhancement
Support multi datasources in the service accounts tab
Selector is introduced with read only behavior to the local cluster. Since this tab does not exist in 2.x line, I kept the changes minimal.
#1799 

Support multi datasources on service accounts page

---

public/apps/configuration/panels/tenant-list/configure_tab1.tsx
public/apps/configuration/panels/tenant-list/manage_tab.tsx
public/apps/configuration/panels/tenant-list/tenant-list.tsx
public/apps/configuration/panels/tenant-list/test/__snapshots__/tenant-list.test.tsx.snap

Updates copy on the tenancy tab to be clear that it is talking about a front end only concept of tenancy. It can get confusing since the security plugin stores tenants as backend objects, but with multi datasource changes coming, we want to clear up that this tab is only talking about the frontend concept (locked to the local instance of dashboards).
Enhancement
Fix: #1878 
Fix: #1878 
Copy changes - no testing needed - update snapshots

Update copy for tenancy tab

---

.github/CODEOWNERS
MAINTAINERS.md

This PR moves Dave Lago from the codeowners file, and moves him from active to emeritus maintainer. We need confirmation from @davidlago somehow on making this change. 
Maintenance
CODEOWNERS file became invalid
CODEOWNERS file was invalid
Fix #1883 
None

Move Dave Lago to emeritus

---

package.json
yarn.lock

Bump jose from 4.11.2 to 5.2.4
Addresses [CVE-2024-28176](https://nvd.nist.gov/vuln/detail/CVE-2024-28176)
Maintenance

Bump jose from 4.11.2 to 5.2.4

---

.github/CODEOWNERS
MAINTAINERS.md

Move myself (peternied) to emeritus

Move myself (peternied) to emeritus

---

.github/workflows/unit-test.yml
public/apps/configuration/app-router.tsx
public/apps/configuration/test/__snapshots__/app-router.test.tsx.snap
public/apps/configuration/test/app-router.test.tsx
public/utils/datasource-utils.ts
public/utils/test/datasource-utils.test.ts
test/cypress/e2e/multi-datasources/multi_datasources_disabled.spec.js

While testing the plugin when MDS is turned off, I noticed a few pages were not working. This was because after the refactor done in #1888, we started enforcing datasourceId as a mandator parameter to all APIs. I noticed that a reason why this may have not been caught is because the existing cypress tests for MDS turned off did not do any check that the API call went through, only that a component did not show up. This fixes the code to work when MDS is turned off, and also adds a cypress test to assert this behavior on a tab that broke but was fixed with this PR. 
Bug Fix
Bug introduced by #1888 in which MDS turned off breaks a few Security dashboard plugin features
When MDS is turned off the security dashboards plugin still functions
Fix:  #1918 , Fix: #1917 
[Please provide details of …

Add fix for data source disabled plugin should work

---

server/auth/types/authentication_type.ts
test/cypress/e2e/oidc/oidc_auth_test.spec.js

This PR fixes OIDC cypress tests after upstream changes on devtools page. 
Maintenance
Upstream changes in OSD introduced new components, we need to specify which component in our test to avoid upstream changes from breaking our tests
OIDC tests will now pass
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/1922
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/1850
Existing tests pass

Fix oidc cypress test and remove doc link

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.14.0.0.md

Release notes for 2.14
- Related https://github.com/opensearch-project/security-dashboards-plugin/issues/1846

Release notes for 2.14

---

public/apps/configuration/panels/tenant-list/tenant-list.tsx
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js

For MDS, tenancy tab is always locked to local cluster. When disabling/removing local cluster, this causes an edge case where local cluster does not exist in the picker, but is still locked to on the page. This PR removes the picker for the tenancy tab altogether, since tenancy is a dashboards concept and does not really apply in MDS world. 
Maintenace
Fix: #1933 
Fix: #1933 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificat …

Remove MDS selector for tenancy tab

---

package.json
yarn.lock

Bumps ejs to 3.1.10 to address: CVE-2024-33883
Bumps express to 4.19.2 to address CVE-2024-29041
Maintenance
Address CVEs
No diff
Don't have one right now
None

Bump ejs and express versions to address CVEs

---

public/apps/login/login-page.tsx
public/apps/login/test/__snapshots__/login-page.test.tsx.snap

Ran this by @kgcreative.
Turns 
Into
Bug fix
Prior to #1980, we had

Make login screen input feels consistent

---

public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/test/__snapshots__/audit-logging.test.tsx.snap
public/apps/configuration/panels/user-list.tsx

A recent backport brought some failures for integration tests for 2.15 release. This PR reverts the necessary changes to make integration tests pass again. 
Bug Fix
Changes from backport #1984 
Integration tests now pass again, see screenshots
Fix: #1999 

Fix 2.15 integration test failures due to backport

---

public/apps/configuration/app-router.tsx
public/apps/configuration/test/__snapshots__/app-router.test.tsx.snap

This PR fixes a duplication issue where upon first navigation to the security dashboards plugin, the /app/security-dashboards-plugin#/ segment would appear twice. 
Bug Fix
Bug Fix
See video here: https://github.com/opensearch-project/security-dashboards-plugin/pull/2004#issuecomment-2166445743
Fix: #1967 
Manual testing

Fix URL duplication issue

---

.github/actions/run-cypress-tests/action.yml
.github/workflows/cypress-test-multidatasources-enabled-e2e.yml
.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml
.github/workflows/verify-binary-installation.yml

Bump JDK version to 21. Remove unnecessary steps in the CI. 
Maintenance
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/2009
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/2009
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/2009
Existing tests pass

Change JDK to 21 for main branch

---

server/auth/types/authentication_type.test.ts
server/auth/types/authentication_type.ts

Fix the issue of capabilities API not supporting carrying authinfo。
Bug fix
When user call `core.capabilities.registerSwitcher` to store certain state which is about authinfo, the request need carry the auth information.

Fix the bug of capabilities request not supporting carrying authinfo

---

scripts/build.sh

Adds custom build script to allow for different cypress version from core. 
Fix: #1786 hopefully
Build repo not making the change so seeing if this will fix it from our end. 
Should build successfully after
Fix: #1786
None possible, this would be picked up by the build infra

Add custom build script to support different cypress version

---

scripts/build.sh

Remove dependency on opensearch build repo libs from custom build.sh
Bug Fix
Closes https://github.com/opensearch-project/security-dashboards-plugin/issues/2030
Test in local.

Remove dependency on opensearch build repo libs from custom build.sh

---

package.json
server/auth/types/openid/openid_auth.ts
yarn.lock

Add http proxy support for oidc
Enhancement
Users of OpenSearch Dashboards in Companies which require use of http proxy struggle to implement OIDC.
ODIC http requests now support proxies.
Resolves: #911
Starting OpenSearch and OpenSearch Dashboards locally. Configure OIDC and set `https_proxy` variable. Then validate that requests are sent to proxy.

feat: http proxy support for oidc

---

opensearch_dashboards.json
package.json
public/apps/configuration/top-nav-menu.tsx
public/utils/datasource-utils.ts
public/utils/test/datasource-utils.test.ts
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js

Manually backports #2051 via commit e9609acc76e7db541eb3701bd53369555a98517c
- manual backport required because of conflicts in yarn.lock (no changes were made in yarn.lock as it is too close to release)

[Backport 2.16] [MDS] Adds datasource filter for version decoupling (#2051)

---

opensearch_dashboards.json
package.json
public/apps/configuration/top-nav-menu.tsx
public/utils/datasource-utils.ts
public/utils/test/datasource-utils.test.ts
test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
yarn.lock

Manually backports #2051 via commit e9609acc76e7db541eb3701bd53369555a98517c
- manual backport required because of conflicts in yarn.lock

[Backport 2.x] [MDS] Adds datasource filter for version decoupling (#2051)

---

.github/workflows/backport.yml

Updates backport workflow to allow adding backport failure labels to failed auto-backports.
Maintenance
To allow easier tracking of failed backport PRs.
No tracking before this change.
- Resolves #2073

Updates backport workflow

---

public/plugin.ts

Add description and change titles of features in new left nav.
Enhancement
For UX consistancy.

[navigation]feat: update title and descriptions

---

server/auth/types/openid/openid_auth.ts
server/auth/types/saml/saml_auth.ts
server/utils/next_url.test.ts
server/utils/next_url.ts

This PR is to adopt the util function `getRedirectUrl` from OSD core to get a unified url after login.
This PR should not merged until https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7600 get merged.
Bug fix
#2069 
#2069 

Use the `getRedirectUrl` from OSD to generate nextUrl

---

public/apps/account/account-app.tsx
public/apps/account/account-nav-button.scss
public/apps/account/account-nav-button.tsx
public/apps/account/test/__snapshots__/account-nav-button.test.tsx.snap
public/apps/account/test/account-app.test.tsx
public/apps/account/test/account-nav-button.test.tsx

Reskins the account button and places it in the left nav when updated layout is used:
Also:
* Fixed a TS error
* Added aria-* to the button
* Put a note for contributors to add aria-label and maybe a tooltip
Enhancement

Conditionally change where avatar shows up

---

server/utils/next_url.test.ts
server/utils/next_url.ts

Fixes a bug when OSD is run with a basepath that basepath is an invalid nexturl, when it should be allowed
Bug fix
Fix: #2097 
now basepath is a valid nexturl
Fix: Fix: #2097 
Added a unit test

Fix a bug where basepath nextUrl is invalid when it should be valid

---

public/apps/configuration/app-router.tsx
public/apps/configuration/panels/audit-logging/audit-logging.tsx
public/apps/configuration/panels/audit-logging/test/__snapshots__/audit-logging.test.tsx.snap
public/apps/configuration/panels/internal-user-edit/internal-user-edit.tsx
public/apps/configuration/panels/role-edit/role-edit.tsx

This PR fixes a few issues with the UX for the new page header/home feature flag. 
It does the following:
- Removes Extra spacing on the audit log page
- Adds the role/user name into the breadcrumbs on the edit page to give context using the breadcrumbs
Enhancement
Fix: #2106 
See screenshots
Fix: #2106 
Existing tests pass, updated snapshots

Ux fixes for page header

---

release-notes/opensearch-security-dashboards-plugin.release-notes-2.17.0.0.md
release-notes/opensearch-security-dashboards-plugin.release-notes-2.17.1.0.md

Add the release note for 2.17.1 and remove the untracked change in 2.17.0 release note
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/2077
* Relate https://github.com/opensearch-project/security-dashboards-plugin/pull/2117

[Backport 2.17] Add the release note for 2.17.1

---

.github/actions/run-cypress-tests/action.yml
public/apps/configuration/panels/get-started.tsx
public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap

Fixes the button label for config.yml documentation on the "Get Started" page
Bug fix
Fix: #2129 
Used to say "Create config.yml", now it says "Config.yml documentation"
Fix: #2129
Existing tests pass

Fix button label

---

public/apps/login/login-page.tsx
server/auth/types/authentication_type.ts
server/auth/types/jwt/jwt_auth.ts
server/auth/types/multiple/multi_auth.ts
test/constant.ts
test/jest_integration/jwt_multiauth.test.ts

Allows JWT to be included in a multiple-authentication configuration.
Enhancement
Previously one cannot use basic auth and JWT auth together
OSD error when basic auth and JWT auth are configured
#1814 

Add JWT authentication type to MultipleAuthentication

---

.github/CODEOWNERS
MAINTAINERS.md

Move @stephen-crawford to emeritus maintainer
Maintenance
@stephen-crawford 
@stephen-crawford 
None
None

Move Stephen to Emeritus maintainer

---

package.json
yarn.lock

Forward ports CVE fixes for express, micromatch, body-parser, etc.
Maintenance
CVE fixes
None
None
None

Forward port CVE fixes to main branch

---

server/multitenancy/tenant_resolver.ts
server/multitenancy/test/tenant_resolver.test.ts

Fixes a bug where the tenant was defaulting incorrectly based on the ordering of opensearch_security.multitenancy.tenants.preferred, whereas it should be on the basis of default tenant.
Bug fix
Fix: #2019 
Old behavior: 
If `opensearch_security.multitenancy.tenants.preferred: ["Global", "Private"]` and default tenant is `Private` the user will be logged into Global tenant.
New behavior:
The user will be logged in as the default tenant (which is Private in the above example)
Fix: #2019 
Manually tested the behavior …

Fix issue: tenant is defaulting incorrectly based on the ordering of: opensearch_security.multitenancy.tenants.preferred #2019

---

.github/actions/download-plugin/action.yml
.github/workflows/cypress-test-multiauth-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml
test/cypress/e2e/saml/saml_auth_test.spec.js
test/cypress/support/commands.js

There were 2 issues that needed fixing:
1. The download of the security plugin was failing due to using a deprecated -Ddest setting in the mvn command
2. SAML Tests were failing because the backend couldn't fetch metadata. I had to switch to IPv6 address for the metadata url, but then ran into another issue where cypress couldn't understand IPv6. To fix that I wrote an interceptor to convert between IPv6 and localhost
Maintenance
Resolves: https://github.com/opensearch-project/security-dashboards-plugin/issues/2168 …

Fix CI failures related to security plugin download

---

package.json
yarn.lock

The yarn.lock file currently has 7.0.3 which is associated with https://nvd.nist.gov/vuln/detail/CVE-2024-21538.
This dependency comes transitively from `cypress` through `execa:4.1.0`, but there isn't an upgrade available so I'm opting to forcibly resolve it instead.
Maintenance

Forcibly resolve cross-spawn to 7.0.5

---

release-notes/opensearch-security-dashboards-plugin.release-notes-3.0.0.0-alpha1.md

Adds 3.0.0-alpha1 release notes

---

package.json
release-notes/opensearch-security-dashboards-plugin.release-notes-3.0.0.0-alpha1.md
yarn.lock

Fixes CVE-2025-29774 CVE-2025-29775 and GHSA-vjh7-7g9h-fjfh

---

package.json
yarn.lock

Removes typescript dependency, pulls from core instead
Enhancement
Prevent future dependency conflicts
None
Fix #2197 

Remove typescript dependency

---

public/apps/configuration/panels/role-edit/role-edit.tsx
public/apps/configuration/panels/role-edit/test/role-edit.test.tsx
public/apps/configuration/panels/role-list.tsx
public/apps/configuration/panels/role-view/role-view.tsx
public/apps/configuration/panels/role-view/test/role-view.test.tsx
public/apps/configuration/panels/test/role-list.test.tsx

Changes to remove tenant panels from roles pages when multitenancy is disabled
Bug fix
Tenant Panel is not required on role view, edit, and list pages when multitenancy is disabled.
Tenant Panel is present on role view, edit, and list pages when multitenancy is disabled.
- Added unit tests
- Completed manual testing
- Case 1: When multitenancy is enabled [in config and from dashboards]: Tenant Panel is present on role view, create, edit, duplicate and list pages
- Case 2: When multitenancy is disabled [ either from config or from dashboards]: Tenant Panel is not present on role view, create, edit, duplicate and list pages
Roles view and Role list page when multitenancy is enabled:
Roles view and Role list page when multitenancy is disabled:
By submitting this pull request, I confirm that …

Changes to remove tenant panels from roles pages when multitenancy is disabled

---

public/apps/configuration/constants.tsx

With introduction of [CatShardsAction](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsAction.java#L20), the _cat/shard call requires extra cluster permission cluster:monitor/shards for a non-admin user to call the API which was not required for versions prior to 2.17. 
Adding the new action to list of cluster permission that can be granted to a user.
Bug fix
Add granular cluster:monitor/shards permission to list of cluster permission that can be granted to a user via opensearch dashboard.
None. A wildcard permission cluster:monitor/* could be given to non-admin user to access _cat/shards API.
N/A
N/A
- [N/A ] New functionality includes testing
- [N/A] New functionality has been documented
By submitting …

Add cat shard api permission

---

package.json
yarn.lock

Signed-off-by: Derek Ho <dxho@amazon.com>
(cherry picked from commit 5d890b920b6655cdcb71fe12bc89e967831c0f12)
Backport https://github.com/opensearch-project/security-dashboards-plugin/pull/2200 to 2.19.

[Backport 2.19] Bump babel (#2200)

---

public/apps/account/password-reset-panel.tsx
public/apps/account/test/password-reset-panel.test.tsx
public/utils/password-reset-panel-utils.tsx
public/utils/test/password-reset-panel-utils.test.ts

- Changes to disable reset button when current or new password is empty
- Changes to prevent page reload on invalid current password validation during reset password
Notes: This function is used currently to validate current password: https://github.com/nishthm/security-dashboards-plugin/blob/main/public/utils/login-utils.tsx#L19 which is causing the issue. Using the actual login endpoint (/auth/login) might triggers browser authentication behavior
through the normal HTTP client, a 401 Unauthorized will trigger the built-in auth‐interceptor—which assumes session has expired and does a full page reload. So when validateCurrentPassword gets a bad password back (401), the client reloads dashboards page.
Bug fix
- The Reset password button should be disabled if the user doesn't input any …

Changes to prevent page reload on entering invalid current password and   to disable reset button when current or new password is empty

---

.github/actions/run-cypress-tests/action.yml
.github/workflows/cypress-test-multiauth-e2e.yml
.github/workflows/cypress-test-multidatasources-disabled-e2e.yml
.github/workflows/cypress-test-multidatasources-enabled-e2e.yml
.github/workflows/cypress-test-oidc-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml
.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml
.github/workflows/verify-binary-installation.yml

This PR updates Github workflows to 3.1.0.
Ideally the version increment automation should include these in the autocut PRs for version increments. atm I'm not sure why the version increment automation is not updating these instances.
Maintenance

Update Github workflows to 3.1.0

---

.github/actions/run-cypress-tests/action.yml
.github/workflows/cypress-test-multiauth-e2e.yml
.github/workflows/cypress-test-multidatasources-disabled-e2e.yml
.github/workflows/cypress-test-multidatasources-enabled-e2e.yml
.github/workflows/cypress-test-oidc-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml
.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test.yml
.github/workflows/verify-binary-installation.yml

This PR undoes some of the changes from https://github.com/opensearch-project/security-dashboards-plugin/pull/2190 to get this version centrally from opensearch-dashboard's package.json file.
This PR resolves an issue seen on version increment PRs where the automation is not getting these hardcoded instances of the version.
Maintenance

Get OPENSEARCH_VERSION from upstream package.json file

---

.github/dependabot.yml
.github/workflows/dependabot_pr.yml

Taken from https://github.com/opensearch-project/opensearch-js/pull/905, this PR adds a dependabot workflow that runs weekly to automatically update any outdated dependencies in the package.json file
Maintenance

Add dependabot workflow to monitor and upgrade outdated dependencies

---

.github/workflows/cypress-test-multiauth-e2e.yml
.github/workflows/cypress-test-multidatasources-disabled-e2e.yml
.github/workflows/cypress-test-multidatasources-enabled-e2e.yml
.github/workflows/cypress-test-oidc-e2e.yml
.github/workflows/cypress-test-saml-e2e.yml
.github/workflows/cypress-test-tenancy-disabled.yml
.github/workflows/cypress-test.yml

Fixes the cypress verify errors seen in CI runs like https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/15593291155/job/43917469898?pr=2259
References:
- https://stackoverflow.com/questions/63667880/cypress-verification-timed-out-after-30000-milliseconds
- https://docs.cypress.io/app/references/command-line#cypress-verify
Failure
```
[STARTED] Task without title.
[FAILED] Cypress verification timed out.
[FAILED] 
[FAILED] This command failed with the following output:
[FAILED] 
[FAILED] /home/runner/.cache/Cypress/9.5.4/Cypress/Cypress --no-sandbox --smoke-test --ping=66
[FAILED] 
[FAILED] ----------
[FAILED] 
Cypress verification timed out.
This command failed with the following output:
/home/runner/.cache/Cypress/9.5.4/Cypress/Cypress --no-sandbox --smoke-test …
```

Increase cypress verify timeout to 60s

---

CHANGELOG.md
public/apps/configuration/constants.tsx

Added required index permissioms
[Bug fix]
The required index permissions are missing from the list
```
"indices:data/read/scroll"
"indices:data/read/scroll/clear"
"indices:data/read/mget*"
"indices:data/read/msearch"
"indices:data/read/msearch/template"
"indices:data/read/mtv"
"indices:data/read/mtv*"
"indices:data/read/search/template/render"
"indices:data/write/bulk*"
"indices:data/write/bulk"
```
All these permissions are now available in index permissions list.
- Completed Manual Testing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …

Added required index permissioms

---

public/apps/configuration/constants.tsx

Added a new [agent update API](https://github.com/opensearch-project/ml-commons/pull/3820/files) in ML plugin in 3.1, therefore adding the action here as well.
Maintenance
Need for 3.1 release

Update constants.tsx to include agent update

---

.github/workflows/delete_backport_branch.yml
CHANGELOG.md

This PR updates the delete_backport_branch workflow to automatically delete branches that start with 'release-chores/' after they are merged, in addition to the existing condition for 'backport/' branches.

Update delete_backport_branch workflow to include release-chores branches

---

.github/actions/run-cypress-tests/action.yml

Specify cypress version in run-cypress-tests action to v13 for node compatibility
Maintenance
Resolves error seen on https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/17978381267/job/51137498114?pr=2310
```
yarn add v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error cypress@15.3.0: The engine "node" is incompatible with this module. Expected version "^20.1.0 || ^22.0.0 || >=24.0.0". Got "18.19.0"
error Found incompatible module.
```
Seen during version increment to 2.19.4.
For more information on following Developer Certificate of Origin and …

[2.19] Specify cypress version in run-cypress-tests action to v13 for node compatibility
